### ISSUE TITLE
engineRequestModel crash

### ISSUE THREAD

**Issue by Xenius97** [multitheftauto/mtasa-blue#1137]
**Describe the bug**
If i request new models for custom skins with engineRequestModel("ped"), then mta crashes randomly above 80-100 players. 

**Reproduce**
I have requested 104 skins. After that I make a custom element data with player skin ID, and i put that skin with setElementModel client side on player.

**Crash logs**
https://pastebin.com/tPAxTzvz
Dumps: https://upload.mtasa.com/u/341718374/dumps.zip_
MTA doesn't make crash log on every crashes. MTA window randomly just quit without saying crash report or something.

**Version**
All versions above r20147

**Comment by qaisjp** [comment]
The only crash in your pastebin relevant to `engineRequestModel` will be the `gta_sa.exe` crash, not the `libcef.dll` crashes:

```
** -- Unhandled exception -- **
 
Version = 1.5.7-release-20308.0.000
Time = Sun Oct  6 19:01:14 2019
Module = D:\Games\GTA San Andreas\gta_sa.exe
Code = 0xC0000005
Offset = 0x00349BCB
 
EAX=00000000  EBX=2ACFA348  ECX=00000000  EDX=0086D168  ESI=00000000
EDI=00000008  EBP=0177F890  ESP=0177F7F4  EIP=00749BCB  FLG=00010246
CS=0023   DS=002B  SS=002B  ES=002B   FS=0053  GS=002B
 
** -- End of unhandled exception -- **
```

**Comment by Xenius97** [comment]
MTA doesn't make crash log on every crashes. MTA window randomly just quit without saying crash report or something.

**Comment by Dutchman101** [comment]
> Offset = 0x00349BCB

.. which is a known crash that can happen due to a bad skin model. If you received this crash on your own server as well (@Xenius97), then you gotta be aware of that, as there might be a corrupted one. But if it happened in the context of this issue (engineRequestModel) under the new feature of allocating ped ID's dynamically ( 475544f ), we still gotta make sure it's not a new crash that happens to be on the same offset as it handles skins, so please **provide us a crash dump** (corresponding to your core.log entry) for that one.

Note: it would be helpful if in case you're using custom skin models on the ID you're requesting the model of, to send us the model as we may want to check if it contains corruption (for the aforementioned reason).

Although it would be difficult to investigate the unhandled "poof, client gone" crashes without crash dialog, what can help is this:

- As soon it happens again, do not re-launch the client right after crashing.
Go to `C:\ProgramData\MTA San Andreas All\1.5` and open **report.log**.

Now, copy and provide us the line that contains: `* End` which will contain the exit code. If the MTA process ended unexpectedly and abnormally, it will be a software exception code, which may hold clues for us.

**Comment by Xenius97** [comment]
@Dutchman101 

```
7411: 2019-10-27 17:21:30 [9.20339.0.000 6.2(10.0) a] [05572-14644] - CClientGame::SetFileCacheRoot - Is shared 'D:\Games\MTA San Andreas\mods\deathmatch'
567: 2019-10-27 17:21:34 [9.20339.0.000 6.2(10.0) a] [05572-14644] - CAnimManager::ms_aAnimAssocGroups Address - CAnimManager::ms_aAnimAssocGroups = 0x23051fbc
7059: 2019-10-27 17:22:43 [9.20339.0.000 6.2(10.0) a] [05572-14644] - Resource file modifed by script (fileDelete): ex_protect\protectLoaderC.luac 213.181.201.216:22003
6211: 2019-10-27 17:23:08 [9.20339.0.000 6.2(10.0) a] [05572-14644] - WaitForSingleObject timed out with 00000428 and 4000ms
7059: 2019-10-27 17:23:36 [9.20339.0.000 6.2(10.0) a] [05572-14644] - Resource file modifed by script (fileDelete): ex_icons\meta.xml 213.181.201.216:22003
8645: 2019-10-27 17:25:30 [9.20339.0.000 6.2(10.0) a] [05572-14644] - Error in render list: IsPlaceable:0 HasRwObject:0
8645: 2019-10-27 17:34:48 [9.20339.0.000 6.2(10.0) a] [05572-14644] - Error in render list: IsPlaceable:0 HasRwObject:0
8645: 2019-10-27 17:36:18 [9.20339.0.000 6.2(10.0) a] [05572-14644] - Error in render list: IsPlaceable:0 HasRwObject:0
7104: 2019-10-27 17:41:57 [9.20339.0.000 6.2(10.0) a] [05572] - Loader - Finishing
8070: 2019-10-27 17:41:57 [9.20339.0.000 6.2(10.0) a] [05572] - CheckService 5 result: 1
1044: 2019-10-27 17:41:57 [9.20339.0.000 6.2(10.0) a] [05572] - * End (0x1)* pid:5572
```

**Comment by Brian9221** [comment]
Hello,
 I've faced MTA quitting itself when combining engineRequestModel + engine functions to apply custom models inside an "onClientStreamIn" event. I was forced to separately request a custom model ID, then apply the custom model (everything while the ped isn't streamed in) and only on a thrid moment switch to the custom model ID. 

I've excluded models being corrupt by manually adding mods with runcode on normal peds. 

If you delay applying the mod on a custom ID, in order to give MTA client ability to process the engineRequestModel's request, everything works fine.
