### ISSUE TITLE
If possible, let setFPSLimit be at least 300 fps at maximum

### ISSUE THREAD

**Issue by PlatinMTA** [multitheftauto/mtasa-blue#1149]
**Is your feature request related to a problem? Please describe.**
Although having a server running over 60,70fps~ will cause the players some weird bugs (unable to aim and move, impossible to turn the sirens on and many others) I guess it would be good to change the max fps limit to, for example, 300fps. I think all mta players and server owners should be able to decide the max fps allowed on their client/server, even if it bugs out some things.

I don't know if this is mainly capped because of Renderware or because of some syncing issues, if that is the case, is it possible to change it? And, if it's possible to change it, could it generate new bugs even if using lower fps?

**Describe the solution you'd like**
Change setFPSLimit max limit to 300fps.

**Comment by Haxardous** [comment]
100 is the highest value you can really feel the game as playable, anything above that number is a disaster. You’re able to change your client frames limit “manually” by typing “fps_limit=number”(0 will make you have unlimited fps) in-game console & reconnect to server, keep in mind that the server should also allow that, same thing 0 for unlimited & you can type a value that’s more than 100 in server.

I’ve been working on finding the issues while going above the fps that GTA made with (25) & even 1 frame can make a difference in-game physics, you can know more by visiting the “projects” tab & “framerate fixes” here in MTA Blue’s repository.

**Comment by Dutchman101** [comment]
The first serious 'high FPS' GTA bugs appear after the mark of 74 FPS, and they get worse as you come closer to 100 FPS.

> Change setFPSLimit max limit to 300fps.

If you pass 100 FPS, you will get the most serious bugs that deliver an awful gameplay experience. For example, if you release accelerate, cars will automatically brake like if you were holding down spacebar, and have less engine power when accelerating.

> I think all mta players and server owners should be able to decide the max fps allowed on their client/server, even if it bugs out some things.

Considering what i just said, it would make no sense for MTA to assist servers in producing awful gameplay experiences, for the heck of it (because these FPS limits cannot be measured with the human eye).

Feel free to recreate or re-open this issue in the future if MTA has more progress in fixing high FPS bugs, including above 100 FPS. Right now it brings no benefits and only disadvantages that cannot be justified with only "server owners should be able to decide".
