### ISSUE TITLE
Enable setTrainTrack for earlier builds of MTA 

### ISSUE THREAD

**Issue by Brian9221** [multitheftauto/mtasa-blue#1190]
**Is your feature request related to a problem? Please describe.**
Usage of trains in MTA is so limited due to setting a correct train track not being possible. There could be thousands of new features with trains usage, yet it is widely limited due to having 2 working tracks and one being completely bugged. In fact, excluding San Fierro's tram track, GTA offers 2 train tracks that go around the map, but one makes trains float in air near LS to LV train bridge. The train will start floating in air on an invisible track that reaches SF docks. 

Currently spawning in train tracks is completely random.

**Describe the solution you'd like**
We had a hope with the function https://wiki.multitheftauto.com/wiki/SetTrainTrack so that a misplaced train could be reset to the correct train track. All I request  is to enable this particular function, as well as its counterpart "getTrainTrack". I guess many servers will benefit from this.

**Describe alternatives you've considered**
We've been trying setElementPosition, but the function won't effectively work. 

**Additional context**
![image](https://user-images.githubusercontent.com/923242/71311573-cbc8be80-2417-11ea-9a2e-77aef2a4e6bd.png)

![image](https://user-images.githubusercontent.com/923242/71311574-cff4dc00-2417-11ea-9766-e29cf19201d2.png)

![image](https://user-images.githubusercontent.com/923242/71311576-d2efcc80-2417-11ea-8535-d9e4b5d254ac.png)

![image](https://user-images.githubusercontent.com/923242/71311585-d7b48080-2417-11ea-8b90-0fe0c7fcb6ca.png)

**Comment by qaisjp** [comment]
Hello,

The ability to change tracks will come along with the custom train tracks update (which has no timeline).

The reason we've disabled these functions is because we're not happy with the current API. If we enable the function in this current form we will be forced to support the API.

Not an ideal solution, but you should be able to build a custom server to enable this feature — you just need to uncomment the lines declaring these functions, [here](https://github.com/multitheftauto/mtasa-blue/blob/18277d579221946600ed88dfd6896b78d79d7658/Server/mods/deathmatch/logic/luadefs/CLuaVehicleDefs.cpp#L108). It should _just work_ since clients support the sync code.

There's some work we could do to formalise unreleased features (such as engineRequestModel, xmlLoadString, etc) as "beta" on the wiki — this way scripters are aware that their script could break at any time. I'm open to enable these train track functions under that sort of model.

**Comment by PlatinMTA** [comment]
> Hello,
> 
> The ability to change tracks will come along with the custom train tracks update (which has no timeline).
> 
> The reason we've disabled these functions is because we're not happy with the current API. If we enable the function in this current form we will be forced to support the API.
> 
> Not an ideal solution, but you should be able to build a custom server to enable this feature — you just need to uncomment the lines declaring these functions, [here](https://github.com/multitheftauto/mtasa-blue/blob/18277d579221946600ed88dfd6896b78d79d7658/Server/mods/deathmatch/logic/luadefs/CLuaVehicleDefs.cpp#L108). It should _just work_ since clients support the sync code.
> 
> There's some work we could do to formalise unreleased features (such as engineRequestModel, xmlLoadString, etc) as "beta" on the wiki — this way scripters are aware that their script could break at any time. I'm open to enable these train track functions under that sort of model.

I would be nice to just enable this functions if the code just kinda works, like with engineRequestModel(). I think that the few scripters and servers that will use these type of functions know really well that they could change in the next version of MTA, adding a warning on the wiki would be a plus tho.
