### ISSUE TITLE
`passwordHash` doesnt work properly when specifying symbols as salt

### ISSUE THREAD

**Issue by ghost** [multitheftauto/mtasa-blue#1206]
**Describe the bug**

MTA's `passwordHash` implementation doesnt work when providing a custom salt with symbols. Only a-z, A-Z, 0-9 seem to be working.

When specifying them, `passwordHash` will return a string containing `*0` which comes from here: https://github.com/multitheftauto/mtasa-blue/blob/master/vendor/bcrypt/crypt_blowfish.c#L672

**To reproduce**

Execute the following snippet:
```lua
iprint(passwordHash("hello", "bcrypt", { salt = ("!"):rep(22) }))
```
**Expected behaviour**

`passwordHash` should return `$2y$10$ISEhISEhISEhISEhISEhIOiC8CRE5gZCStVAw4bAuMNSn7gm8bbtu` rather than `*0`

**Additional context**

Other programming languages such as PHP work just fine using the following code:
```php
<?php
    echo @password_hash("hello", PASSWORD_BCRYPT, array("salt" => str_repeat('!', 22)
));
```

// cc: @Jusonex

**Comment by qaisjp** [comment]
I can confirm this, and have submitted a patch that ensures that "*0" does not get returned.

Why do you need to set salt parameter yourself?

**Comment by ghost** [comment]
> I can confirm this, and have submitted a patch that ensures that "*0" does not get returned.
> 
> Why do you need to set salt parameter yourself?

My account registration is being processed by a forum software which generates and uses custom salt for each user individually for security reasons.

**Comment by qaisjp** [comment]
> which generates and uses custom salt for each user individually for security reasons

bcrypt by default already does this, storing the salt in the returned hash. This is why `passwordVerify` does not need a `salt` setting.

I don't think you need to set the salt. The following scenarios should work without manually setting the salt:
- creating an account in the game server server and logging in with the same details on the forum
- creating an account in the forum and logging in with the same details on the game server

[It's worth noting that PHP has deprecated the salt option as users cannot be trusted to generate one themselves.](https://stackoverflow.com/questions/40993645/understanding-bcrypt-salt-as-used-by-php-password-hash)

Which forum software do you use?

**Comment by ghost** [comment]
Well, i'm using IPS and i just took a look into IPS and they're doing the following by default:

```php
if ( password_verify( $password, $member->members_pass_hash ) === TRUE )
```
(`system/Login/Handler/Standard/Standard.php` (Line `126` for me)

So i guess a custom salt is not required here.

Maybe MTA should drop custom salt from being generated but this would mean that we would break backward compatibility. I would suggest to simply add a warning message and ignore custom salts from being used.

**Comment by qaisjp** [comment]
> Maybe MTA should drop custom salt from being generated but this would mean that we would break backward compatibility. I would suggest to simply add a warning message and ignore custom salts from being used.

Agreed. By the way in case you're not doing that already, make sure to use a higher cost when using `passwordHash`. According to [this](https://invisioncommunity.com/forums/topic/433297-security-passwordsalt-in-the-database-and-cost/?tab=comments#comment-2659886), in 2016 the cost was set to 13. It might be higher now.

Obviously, it will still work with a lower cost (since the cost is in the hash too). But it would mean that passwords generated on your server would be less secure than those generated on the forum, which is not ideal!

[For now, I have updated the wiki to describe the salt parameter as deprecated.](https://wiki.multitheftauto.com/index.php?title=PasswordHash&type=revision&diff=64892&oldid=64124)

Feel free to send a PR so that we can throw warnings. In the future we can ignore the parameter entirely.

**Comment by qaisjp** [comment]
@xLuxy, can we close this? This could probably be fixed but since we're deprecating it, it's not worth the effort.

(also maybe it expects a base64'd salt instead of a pre-base64'd salt)
