### ISSUE TITLE
Assimp asset library

### ISSUE THREAD

**Issue by CrosRoad95** [multitheftauto/mtasa-blue#1211]
**Is your feature request related to a problem? Please describe.**
Weak support of custom models

**Describe the solution you'd like**
Add Assimp asset library, instead of separeted library for each file format

**Describe alternatives you've considered**
/

**Additional context**
For long time i'm thinking what could be the best solution to render custom models in mta, Jusonex suggested Assimp library, it supports most common models files.
http://assimp.sourceforge.net/lib_html/index.html list of supported extensions

### Here's example set of functions i could introduce ( not full list )
1. loadAssetModelpath/raw data, type = ".obj/.fbx/...", options) -- i don't know it is possible to detect extension for raw data
2. assetModel createAssetModel( asset, x,y,z, rx,ry, rz, options) -- creates instance of model, will bahave almost the same as createObject except will not support default gta collision ( right now ), options will used to select how object will render ( example you have 10 models in one file, you can spawn each of them separetly )
3. set/getAssetProperties( asset, key, value) -- set/get different properties if exists
4. set/getAssetData( asset, ...) -- could be used to read/modify model mesh ( vertices, faces ), 
5. set/getAssetModelProperties(assetModel, key, value) -- same as above but for things like textures
6. renderAssetModel(...) -- freely render models in 3d and 2d just like object_preview

### Other
because i don't know how works different types, i prefer enable only `obj` and `fbx` right now, only modify .obj to disallow load .mtl files from pathes outside mta

**Comment by qaisjp** [comment]
Principally I am in favour of introducing something like this, as long as the API is well-designed.

I hate SourceForge, so I've found a few links for assimp on better platforms:
- [GitHub](https://github.com/assimp/assimp) (they use the wiki here too)
- [readthedocs](https://assimp-docs.readthedocs.io/en/latest/)

You should get feedback on this from @saml1er. I think he had his reservations about #1093.

> `loadAssetModel(path/raw data, type = ".obj/.fbx/...", options)`
> i don't know it is possible to detect extension for raw data

- [PLY files](https://en.wikipedia.org/wiki/PLY_(file_format)#The_file_format) can be in binary or plain text, but they always start with a `ply` header in ASCII.
- [OBJ files](https://en.wikipedia.org/wiki/Wavefront_.obj_file#File_format) are in plain text only, and there does not seem to be a discernible header.
- [FBX files](https://en.wikipedia.org/wiki/FBX#File_format) are binary or plain text, and is a proprietary file format. Blender has [released an unofficial spec](https://code.blender.org/2013/08/fbx-binary-file-format-specification/). The binary format has a clear FBX header, the plain text format does not seem to.

It is worth noting that assimp has their own pages about each format on their GitHub wiki: [fbx](https://github.com/assimp/assimp/wiki/FBX-File-format), [obj](https://github.com/assimp/assimp/wiki/Obj-file-format), etc.

> Here's example set of functions i _could_ introduce (not full list)

Please can you format this properly and spell check? It's a large proposal! 

You describe `set/getAssetData(asset, ...)` as accessing model mesh data, but then say that an `asset` can contain multiple objects, so you'd need to select which one when calling `createAssetModel`.

Please can you describe the difference between `asset` and `asset model`? Is `asset` more like an `asset library`?

Assuming this proposal is provisionally accepted, it would be good if we had a list of everything you'd like to introduce.

You don't need to document and propose an API for everything at once, but it would be good if we settled on an initial API before you implement each bit. That way we can focus on reviewing your code instead of the idea, and we can do it all in bite-sized chunks.

Obviously it's not possible to get the API perfect before it's implemented, but planning it beforehand means we spend less time afterwards changing and "perfecting" the API.

**Comment by CrosRoad95** [comment]
Initial release:

```lua
asset loadAssetMode(path, options)
```
- if possible, i would implement multithreading for it to provide smooth loading, this one will just load file with model,
  ```lua
  assetModel createAssetModel( asset, position, rotation, options)
  ```
  where `options` would be custom textures/shaders set, lighting settings, render distance, what meshes you want ect.
- function to get general information about file, such a meshes/textures count, color, normals, amount of faces/vertices ect ect. 
- assetModel should support all function which original object support
- i'll blacklist all files except .fbx .obj .ply

**Comment by CrosRoad95** [comment]
I'm thinking about way to pass options to for rendering, i'm consider two ways: table with settings individual for each instance, 2. groups in https://wiki.multitheftauto.com/wiki/EngineSetModelPhysicalPropertiesGroup style

i'm going to add 2 functions, something like "dxDrawModel" and another which will render models attached to any element eg. original objects

In first scenario code would looks like:
```lua
assetRender(someNode, 0,0,3, 90,0,0, 1, 1, 1, {
  ["doublesided"] = true,
  ["renderdistance"] = 100,
  ["someOtherOption"] = 123,
})
```
in second:
```lua
assetSetGroupProperties(1, "doublesided", true) -- first argument is group id.
assetSetGroupProperties(1, "renderdistance", 100)
assetSetGroupProperties(1, "someOtherOption", 123)
assetRender(node, 0,0,3, 90,0,0, 1, 1, 1, 1) -- render some node/model at position 0,0,3, rotation 90,0,0, scale 1,1,1, use group 1
```
up to 4294967296 ( unsigned int limit ) groups, if you use group without any properties set, it will get default ones.
groups should be shared between all assets you load.

**Comment by ghost** [comment]
@CrosRoad95  I like it. I'd say, go with it.
