### ISSUE TITLE
Remove forks from masterlist

### ISSUE THREAD

**Issue by ghost** [multitheftauto/mtasa-blue#1212]
Forks such as MTA:Province shouldnt be listed in Masterlist since an official (or nightly) build is not able to connect to these servers and i personally dont see why they should remain being on the server list.

(This issue was requested by qais on [Discord](https://discordapp.com/channels/278474088903606273/366384007535001612/667387074017624095)

**Comment by qaisjp** [comment]
Makes sense to me. I'm not sure how hard this will be to implement. Any objections?

**Comment by Woovie** [comment]
I agree with this but, at the same time I'd like to maybe see that we offer them their own list. Could we have the masterlist advertise for unofficial builds their own custom list perhaps? Like a keyword that says what list the server should appear in.

This would allow forkers to adjust said keyword, and have their own masterlist, still running on the main masterlist that we operate.

Note that I don't expect us to help them with serverlist spam or name faking. Otherwise they should just operate their own masterlist.

**Comment by ccw808** [comment]
The in-game server browser only shows the servers that the client can connect to. So what is the advantage of removing custom builds from the master list?

**Comment by ghost** [comment]
Well, didnt knew that, but one advantage would be to get more accurate player stats for example.

**Comment by qaisjp** [comment]
I only meant the in-game server list (which according to https://github.com/multitheftauto/mtasa-blue/issues/1212#issuecomment-575219266 is already done). I don't see a particular reason to remove them from the master list  . (@xLuxy — Woovie has been experimenting with a new stats page, perhaps he'll introduce a filter for forks?)

**Comment by Woovie** [comment]
If our stats differentiate forks from non-forks, I could, but last time I looked at the DB, it certainly does not.

**Comment by qaisjp** [comment]
> The in-game server browser only shows the servers that the client can connect to. So what is the advantage of removing custom builds from the master list?

**Comment by Dutchman101** [comment]
> If our stats differentiate forks from non-forks, I could, but last time I looked at the DB, it certainly does not.

Just for the record, it does. I just know that because I know how things work, but if you really want to confirm it, perform this test: when MTA release build displays that there are, for example, 30,000 players online at a certain moment (like usually in the evening, on a daily basis), you can find all of these players on servers that are visible (while the client only shows servers that you can connect to: non-forks).

MTA players stats like we put in [https://forum.mtasa.com/topic/68546-player-stats-for-mta/](https://forum.mtasa.com/topic/68546-player-stats-for-mta/) are taken from a source that matches what you'll see in the client server browser if you compared a particular timestamp between the two.. the client only counts total servers and thus total players for the servers that client can connect to. If you see 30,000 players in-game, if we would actually count forks, that would have probably exceeded like 150,000 since there are a few major russian MTA forks with insane popularity.

But rather than that, you see only similar player counts between what we can pull from stats metrics and what you can read from the server browser. No huge differences, about the same.. so this is the 3rd way the truth verifies itself. If you take a look at the DB and see something different, then there is probably no information at a lower level on how the DB feeds the data to begin with, or you didn't understand it entirely.. there is a lot of the infrastructure that's not connected to your boxes.
