### ISSUE TITLE
People with Killer Network Drivers get auto-kicked

### ISSUE THREAD

**Issue by Hahnfruh** [multitheftauto/mtasa-blue#1235]
People who have hardware requiring "Killer Network" drivers now get kicked from servers with the following message:
"Disconnected: You were kicked by (VF #33 NetLimit (Killer Networking / Control Center).
Any reasonable solution for this issue would be greatly appreciated.

**To reproduce**
1) Own Hardware requiring Killer Network Drivers
2) Install said drivers (i.e. Killer Control Center)
3) Connect to any MTA server with anticheat enabled
4) Immediately after connecting or after a few minutes, you will be kicked.

**Version**
Multi Theft Auto v1.5.7-release-20358.2

**Comment by Haxardous** [comment]
what are the consequences if they've used this solution: https://forum.mtasa.com/topic/121873-vf-33-netlimit-killer-networking-control-center/?do=findComment&comment=970951 ? is it going to toggle something important to their hardware to make it even unusable?

**Comment by Hahnfruh** [comment]
The point is that a legitimate piece of driver software should not be causing issues like this. I'm sure there is a good reason for it being detected at all but considering that many people are not even aware of what is installed on their computer, this can be a great problem for many users.

**Comment by Dutchman101** [comment]
> People who have hardware **requiring** "Killer Network" drivers now get kicked from servers

Not true:
1) only some servers opt-in to the detection (SD in mtaserver.conf)
2) hardware doesn't require "Killer Network" software to function
* the network adapter drivers are fine to run (therefore, you don't require the software).. it's the bandwidth shaping driver (e.g RfeCo10X64.sys) that is prohibited under SD #<span></span>33, because it allows the Killer Control Center to be used as a lag switch for games.

The thing is that issue reports like this are invalid. I will try to explain why:
1) read [https://updatesa.mtasa.com/sa/trouble/?tr=netlimiter](https://updatesa.mtasa.com/sa/trouble/?tr=netlimiter)

2) special detections [info here](https://wiki.multitheftauto.com/wiki/Anti-cheat_guide#.3Cenablesd.3E.3C.2Fenablesd.3E) exist to help servers stop certain types of potential abuse.. the category SD #<span></span>33 is for software of the category "Net limiter" and software that contains the capability to "choke" an application (reduce available bandwidth, cause packet loss, all of which can result in deliberate lag).

We just know that players who want to use a lag switch have gotten smarter over time, and now we're offering servers tools to stop that.

> The point is that a legitimate piece of driver software should not be causing issues like this

We are only blocking the component that allows you to use Killer Control Center as a lagswitch. That means like I said earlier, the bandwidth shaping driver itself. For the claim of it being 'legitimate', please read the note behind SD #<span></span>33 on the MTA anti-cheat guide wiki page that I linked.

Servers **have the right** to use it. It's opt-in. If they want to be safe, they want to be safe from that type of stuff.. then all they need to do is educate their players on how to remove the offending software, if they are having difficulties (like pointing them [here](https://forum.mtasa.com/topic/121873-vf-33-netlimit-killer-networking-control-center/?do=findComment&comment=970951)). Servers can read the SD #<span></span>33 entry in the wiki page, to understand that net limiters/bandwidth shapers can obviously also be used for legit purposes (e.g to actually reduce lag) but they just have the desire to be safe from the opposite usage potentials.

If you don't like it, then please contact the owner of the server that decided to use this special detection.

**Comment by AlexTMjugador** [comment]
Just a note to server owners whose threat model is extensive: I wouldn't assume a server will be free of players using lag switches just because this special detection is enabled.

A malicious player with basic networking knowledge can perform traffic shaping without any hardware or software modification in the PC that runs MTA, and as far as MTA is concerned it would be a normal network situation (I'm being intentionally vague to not give clues in how to do it). I'd use that SD in a defense in depth model, but trusting that alone is not enough if security requirements are high.
