### ISSUE TITLE
option to use executeBrowserJavascript at non-local webiste

### ISSUE THREAD

**Issue by CrosRoad95** [multitheftauto/mtasa-blue#1263]
**Is your feature request related to a problem? Please describe.**
You can't use executeBrowserJavascript if browser is not local. It could helps with cef guis.

**Describe the solution you'd like**
Make if webiste contain meta tag example:
```
<meta name="mtaserver" content="localhost;127.0.0.1:222003;123.123.123.123:12345">
```
localhost and server of ip and port 123.123.123.123:12345 can use function executeBrowserJavascript. it let you whitelist which pages has allowed javascript, which not
**Describe alternatives you've considered**
/

**Additional context**
No way to hack this, you have to be owner of website to set this tag.

**Comment by MegadreamsBE** [comment]
Should make sure to disallow the execution of JavaScript in iframes from the parent page then. Either that or use this same logic for that. This would be to prevent the website creator from loading in a 3rd-party website and getting around this restriction.

**Comment by prnxdev** [comment]
> You can't use executeBrowserJavascript if browser is not local. It could helps with cef guis.

How?

**Comment by sbx320** [comment]
This is by design. Servers cannot be allowed to execute javascript on remote pages, as otherwise a server could do things on the users behave. For example someone could steal your Github password if you logged into Github from a MTA client by reading the password input field and sending the password to the server. 

And no meta tag would be able to help us here, as it'd still open up remote requests for JS injections in the users context.
