### ISSUE TITLE
MTA is crashing when adding changed model upgrades to vehicles in new version

### ISSUE THREAD

**Issue by Grafu** [multitheftauto/mtasa-blue#1288]
**Describe the bug**

Installed a new nightly and my MTA started crashing due to this:
![image](https://user-images.githubusercontent.com/11540828/76422498-fa6a8b80-63ad-11ea-9241-4e6be315b9d3.png)

Reverted afterwards back to my  previous client version (Multi Theft Auto v1.5.7-release-20358.5.001) and it just works fine with that one. Looks like a regression.

It is happening in 1.5.7 nightly.

**To reproduce**

1. I have replaced models of the vehicle and its upgrades. Probably that's why it is crashing on the new nightly.

**Expected behaviour**

Should not crash.

**Comment by qaisjp** [comment]
Related to 275eae917eb0f39abd69f7e0133ffed02f318335 and dfa9b5086a256aeb8eea01ee5aba2414cc14c964

**Comment by ghost** [comment]
> Installed a new nightly and my MTA started crashing due to this:

Thanks for the report, but do you know which version of nightly you installed?

EDIT: @Grafu Please consider downloading the latest nightly from nightly.mtasa.com and see if you are still crashing. More importantly, the issue was fixed in 5138de085dd379d2361f71d26e96b81672554f85.

**Comment by Dutchman101** [comment]
> Thanks for the report, but do you know which version of nightly you installed?

What happened is that he received the nightly build through the auto-updater (having set `nightly` in MTA advanced settings), which as you just added in, didn't include the fix yet. The nightly channel for auto-updater is usually behind..

So i guess this can be closed?

**Comment by ghost** [comment]
This crash was fixed in 5138de085dd379d2361f71d26e96b81672554f85, however, calling `engineRestoreModel` before `engineReplaceModel` can also trigger this crash. I fixed the vehicle model memory leak by forcing MTA to call `engineRestoreModel` when calling `engineReplaceModel`. 

The crash happens in `CVehicle::CreateUpgradeAtomic`. After investigating the crash further, I found out that the model information of the wheel model gets unloaded. I think we can fix the crash in `CVehicle::CreateUpgradeAtomic` by loading the model information if it's not loaded already.

**Comment by ghost** [comment]
@Dutchman101 informed me that this is an old crash. I checked the crash stats, it's pretty low for `CVehicle::CreateUpgradeAtomic`. So, I guess the issue has been resolved in 5138de085dd379d2361f71d26e96b81672554f85.
