### ISSUE TITLE
It should be possible to install MTA without admin access

### ISSUE THREAD

**Issue by commanderagu** [multitheftauto/mtasa-blue#1323]
I'm really frustrated that there isn't a way to install MTA without admin access. My brother has admin control on my PC due to my poor achievement in my mock exam. My main exam was coming up but that is cancelled due to covid-19. My brother is still not willing to give me the password to my own computer. 
I believe that there should be a way to install MTA without admin access for such reasons like this or other factors
An alternative for this is to bypass the admin access which is kinda useful in a way.

**Comment by qaisjp** [comment]
on 31st Jan 2020 I said:

> Just reinstall your PC

you responded:

> big risk man, he'll beat the shit out of me lol

----

You might be able to add a new admin account via recovery? Try following "Way 1" here - https://www.isumsoft.com/windows-10/create-administrator-account-when-cant-sign-in-windows-10.html

You could also make that admin account hidden so that your bro can't tell that you did something — https://superuser.com/questions/278219/how-to-hide-admin-account-and-only-show-main-user-at-logon-screen-in-windows/278221#278221

**Comment by Haxardous** [comment]
lol.. even If someone chose to make a "portable" version of MTA it won't run as it should be because some features require administrator permissions.

**Comment by commanderagu** [comment]
Thanks for your assistance @qaisjp 
I can now play MTA
