### ISSUE TITLE
xmlLoadString has memory leaks

### ISSUE THREAD

**Issue by qaisjp** [multitheftauto/mtasa-blue#1373]
**Describe the bug**

xmlLoadString has memory leaks

**To reproduce**

see conversation from https://discordapp.com/channels/278474088903606273/366384007535001612/698366807148331068

**Expected behaviour**

no memory leaks

**Comment by Pirulax** [comment]
I got so bored while trying to fix this. Its a whole clusterfuck, anyone who here, who understands hows this thing implemented? 

TiXmlDocument is whats leaking the memory(the one created in 
```cpp
CXMLImpl::ParseString(const char* strXmlContent)
```

So, we need to delete that element, instead of storing and deleting the returned root element, because deleting that doesnt propagate the 'delete' to the document, thus the document isnt deleted.

**Comment by qaisjp** [comment]
Also, if you look at how xmlLoadFile (or whatever it's called) works, it stores the nodes in some list, which is cleared when CLuaMain is destroyed. xmlLoadString doesn't do that

**Comment by Pirulax** [comment]
I tried the same at first glance, but then I figured out I need to store the TiXmlDocument somehow, which was messy af, because I needed to return it somehow(returned it thru a function paramater at the end), then include the whole tinyxml into CLuaMain, because I coudnt call 'delete' on it otherwise, and... its jusy messy, and Im not sure that the right solution.
