### ISSUE TITLE
Release next version as 1.5.8 instead of 1.6

### ISSUE THREAD

**Issue by qaisjp** [multitheftauto/mtasa-blue#1377]
This is a proposal. Please share your opinions by 19th April.

**Description**

By the time we release 1.6 it'll be almost a year since 1.5.7.

I propose we instead:
- rename 1.6 milestone to 1.5.8
- move all **unmerged** features in 1.5.8 to 1.6
- feature freeze and work on bug/crash fixes only
- release 1.5.8 mid-May (or a little later if stability is a problem - no rush)

The idea is that we release what we have rather than waiting for ambitious 1.6 features.

**Additional context**

Some discussion here: https://discordapp.com/channels/278474088903606273/366384007535001612/698295340050415626

cc @multitheftauto/blue-collaborators and @multitheftauto/mta-team

**Comment by jhxp** [comment]
I agree, we should do that. It's been a while since the last release, so having an intermediate one soon won't hurt.

**Comment by Dark-Dragon** [comment]
Pushing some fixes sooner instead of later seems like a good idea, especially if license struggles are keeping a major release out of the picture for now.

I gotta say though that I also see some value in the "larger special release, also leaving XP behind" that was brought up.

There are definitely some noteworthy fixed bugs already under the 1.6 milestone, like the long awaited ped's can't be jacked fix #58 or memory leaks regarding txd and model replacing #1275 #359  , with a couple more still open, like enter/exit animations for some special vehicles #70 #1318 more engine load cleanup #1155 and the annoying bug which currently prevents kick votes from working #1301 . There are also a couple fixes for xml load string and dx draw primitive, but I'm assuming those wouldn't be shipped, as they were implemented with this version. There were also a bunch of crash fixes, but I didn't list them because I lost track about which of those weren't also introduced after the last official release or related to new stuff we'll be holding back.

Overall I'd say I'm slightly in favor of a small release.

**Comment by thisdp** [comment]
will there be MTA 1.5.10?

**Comment by patrikjuvonen** [comment]
> will there be MTA 1.5.10?

No, and neither will in the foreseeable future. We have a technical limitation at the moment so we only support single digit semantic versioning.

**Comment by ffsPLASMA** [comment]
> 
> 
> will there be MTA 1.5.10?

Imagine MTA 1.5.9.1

Jokes aside, yes bug fixing should be the major focus for now.

**Comment by thisdp** [comment]
> > will there be MTA 1.5.10?
> 
> Imagine MTA 1.5.9.1
> 
> Jokes aside, yes bug fixing should be the major focus for now.

In Minecraft, after 1.9 is not 2.0, 1.10 instead. :joy:

**Comment by fresholia** [comment]
Lol, this is too slow, a suggestion; 1.5.7.1 -_-

**Comment by qaisjp** [comment]
Feature freeze is applied, milestone updates have been done, and the new milestone deadline is currently 6th of June. Please only fix bugs and not do any _scary_ vendor updates or feature merges.

**Comment by MrDadosz** [comment]
I think #1130 should be fixed in this version. You can't fully fix it by script.
