### ISSUE TITLE
Unknown Error

### ISSUE THREAD

**Issue by RouatbiH** [multitheftauto/mtasa-blue#1386]
Version = 1.5.7-release-20508.0.000
Time = Tue Apr 14 16:09:17 2020
Module = C:\Windows\SysWOW64\ntdll.dll
Code = 0xC0000005
Offset = 0x0002E4F3

EAX=00000000  EBX=BE250001  ECX=96E2164D  EDX=000096E2  ESI=085E3FB0
EDI=BE250000  EBP=0028F97C  ESP=0028F948  EIP=77DFE4F3  FLG=00210286
CS=0023   DS=002B  SS=002B  ES=002B   FS=0053  GS=002B

**Comment by Dutchman101** [comment]
@lamjed001 

1. This is an issue with your PC (hardware, software, drivers) or OS
2. In the past, you made a lot of invalid issues on the tracker. You didn't stop when we asked.
3. I just deleted a comment you made on a commit (you double posted something, into the wrong place). It was a different subject, so I think you wanted to start helping MTA out again with various reports/notifications.

Thanks for trying to make us aware of this all, but I think it's better if you not use the issue tracker at  this point. Closing because this is also invalid (per line 1).
