### ISSUE TITLE
Hunter camera bug

### ISSUE THREAD

**Issue by Tomba120** [multitheftauto/mtasa-blue#1387]
**Describe the bug**
The problem is in rendering players while being in Hunter, when you are using different type of camera. For example when you are in first person camera, you can see players much sooner than player that is using third person camera.  https://imgur.com/a/0Wvggg3

**To reproduce**
If you want to reproduce this problem, you must be atleast 2 people. Fly side to side and one of you use first person camera.

**Expected behaviour**
I would suggest to change start position of rendering from camera to vehicle position.

**Video**
https://www.youtube.com/watch?v=h5ilyeNgB0U

**Version**
Any version

**Comment by Dark-Dragon** [comment]
I mean I see how this is causing an imbalance in this situation, but to me this looks like the expected/intended behavior. Render distance is obviously based on the camera position, not the player position. Do you propose the render distance should depend on the player position instead? It's probably possible, but I'm not sure if this won't lead to more problems as a side effect.

**Comment by Einheit-101** [comment]
I can see only 1 issue here, thats the very limited draw distance of ~250-300 meters for vehicles.

We can set vehicle LOD Distance to an absurd value of 500 (1070 for aircraft/trains), but all vehicles vanish into thin air after ~250 meters. You can increase this limit to ~400 meters by using setElementStreamable(vehicle, false), but use that function with caution. 400 meters is still low, but at least its more than the range of the Hunter rockets.

The vehicles will start lagging at some point because the sync is very bad at greater distance. To fix this lag, use setElementStreamable(playerDrivingTheVehicle, false), this also needs caution but at least it makes the sync somewhat smooth. I wish we had better control over the sync in that regard.

**Comment by sbx320** [comment]
Not a bug for the above reasons.
