### ISSUE TITLE
dimension and interior functions not working with collision

### ISSUE THREAD

**Issue by LightSrc** [multitheftauto/mtasa-blue#1400]
**Describe the bug**
setElementDimension and setElementInterior functions doesn't set dimension and/or interior for example if used with createColRectangle and due to this collision rectangle is visible in all dimensions. I tested only server side, possibly this bug happens also client side.

**To reproduce**
```
local HospitalCol = createColRectangle( 1166, -1384, 52, 92 )
setElementDimension(HospitalCol, 0)
setElementInterior(HospitalCol, 0)
```

**Version**
server - Linux 1.5.7 R5 (build 20423)

**Comment by qaisjp** [comment]
Possible duplicate of #1209 - colshapes are known to be dimensionless.

> visible in all dimensions

I assume this means `showcol` with development mode enabled.

The colshape will exist in all dimensions, even if you use `setElementDimension`, so it wouldn't make sense to hide the `showcol` outline, because that colshape still triggers script events.

-----

Please can you confirm it is a duplicate?

**Comment by LightSrc** [comment]
> Please can you confirm it is a duplicate?

Yes, it is a duplicate

**Comment by qaisjp** [comment]
Duplicate of #1209
