### ISSUE TITLE
onPlayerVehicleExit, onVehicleExit event returns forcedByScript nil

### ISSUE THREAD

**Issue by LightSrc** [multitheftauto/mtasa-blue#1401]
**Describe the bug**
Sometimes and I don't know why onPlayerVehicleExit, onVehicleExit event forcedByScript returns nil instead of true or false. This bug happens randomly, even if im the only one in the server and I just sit afk in the car.

**To reproduce**
```
function setRealNotInVehicle(vehicle, seat, jacked, forcedByScript)
	if (source) then
		if forcedByScript == nil then
			outputChatBox("why?")
		end
	end
end
addEventHandler("onPlayerVehicleExit", getRootElement(), setRealNotInVehicle)
```

**Version**
server - Linux 1.5.7 R5 (build 20423)

**Comment by qaisjp** [comment]
I've checked our code. All calls to `CElement::CallEvent` with `"onPlayerVehicleExit"` and `"onVehicleExit"` include four arguments, so it seems unlikely that this is a bug in MTA.

Please check your code to confirm:

- you are not using `triggerEvent("onVehicleExit")` or `triggerServerEvent("onVehicleExit")`, and check for `"onPlayerVehicleExit"` too
- you are not calling `setRealNotInVehicle` yourself, and forgetting to set the fourth parameter

Also, I recommend just doing `if forcedByScript then` instead of `if forcedByScript == true then`.

> This bug happens randomly, even if im the only one in the server and I just sit afk in the car.

Are you saying that the event fires even when you haven't left the vehicle?

**Comment by LightSrc** [comment]
Thanks for advice, I checked code with notepad++ "find in files" and found that I'm using
`triggerEvent("onVehicleExit", vehicle, player, seat)`
and that is causing me forcedByScript to return nil. All arguments for trigger are valid.

**Comment by qaisjp** [comment]
> and that is causing me forcedByScript to return nil.

> All arguments for trigger are valid.

I am not sure if the second quote here makes sense in this context. is this an issue with MTA or nah?

**Comment by LightSrc** [comment]
If that's normal forcedByScript returns nil instead of boolean then that is not issue with MTA. I just looked in wiki and I was expecting to get true or false instead of nil.

**Comment by qaisjp** [comment]
MTA itself should not be triggering the event with `nil`.

But if you have code like this:

```lua
triggerEvent("onVehicleExit", vehicle, player, seat)
```

That's not triggered by MTA, that's triggered by you!

I would recommend against triggering MTA's default events unless you absolutely know what you are doing.
