### ISSUE TITLE
Crash in C:\Windows\System32\WMNetMgr.dll

### ISSUE THREAD

**Issue by haron4igg** [multitheftauto/mtasa-blue#1745]
Player reports this issue after update to 1.5.8 MTA ( 10 crashes since 18.10.2020 ) together with https://github.com/multitheftauto/mtasa-blue/issues/1718

appears after ~30-40 minutes in game.

[MTADiag](https://pastebin.mtasa.com/824206192)

** -- Unhandled exception -- **

Version = 1.5.8-release-20668.0.000
Time = Sun Oct 18 13:19:51 2020
Module = C:\Windows\System32\WMNetMgr.dll
Code = 0xC0000005
Offset = 0x0005C426

EAX=00000004  EBX=00000000  ECX=00000000  EDX=00265000  ESI=00001938
EDI=15537918  EBP=A887EF08  ESP=A887EF08  EIP=770FA225  FLG=00010282
CS=0023   DS=002B  SS=002B  ES=002B   FS=0053  GS=002B

** -- End of unhandled exception -- **

[core.log](https://github.com/multitheftauto/mtasa-blue/files/5417050/core.log)

[dumps/public.zip](https://github.com/multitheftauto/mtasa-blue/files/5417024/WMNetMgr.zip)

could be related? https://bugs.mtasa.com/view.php?id=9777

**Comment by Dutchman101** [comment]
From the other open issue that you linked:
> track record of blaming MTA (and for each issue, pinpointing a certain build that you figured is when it started)

you again pinpointing 1.5.8 (WnMetMgr.dll crash): 
> Player reports this issue after update to 1.5.8 MTA

> Offset = 0x0005C426

The same offset: [https://www.google.com/search?q=0x0005C426+mta](https://www.google.com/search?q=0x0005C426+mta)
Some information: [https://www.google.com/search?q=WmNetMgr+mta](https://www.google.com/search?q=WmNetMgr+mta)

So, no, it's an old crash. We have investigated these crashes since 2017, and even ccw spent hours looking into it to conclude that it must be some sort of Windows 10 issue. Individual cases are usually resolved after the user updates their Windows 10 to the latest major build. 

There's a dim chance it is memory issue-related rather than OS bug.

Advise users to get the latest Windows 10 release, in this case they may as well go for one that got released yesterday.. Windows 10 October 2020 Update: [https://blogs.windows.com/windowsexperience/2020/10/20/whats-new-in-the-windows-10-october-2020-update/](https://blogs.windows.com/windowsexperience/2020/10/20/whats-new-in-the-windows-10-october-2020-update/)

**Comment by Dutchman101** [comment]
Comparison between 1.5.8 and 1.5.7:
![stats](https://user-images.githubusercontent.com/12105539/96801635-5d260a00-1408-11eb-89c1-d3679f9b425f.png)
Both examples are from well-circulated builds.. 1.5.7 even wins in terms of crash popularity. That is because even though they are similarly circulated, stats have been collected for longer on 1.5.7 since people only just started being on 1.5.8. So it would turn out to be the same..

This proves my point that it's not a new crash. I will reinforce that by doing the same thing, but with a much older 1.5.8 build (r20582 from June 2020) which was also well-circulated:

![stats2](https://user-images.githubusercontent.com/12105539/96802027-4207ca00-1409-11eb-8c28-43b4df30d7d9.png)
So now that point is proven, it means we can fall back on the fact that devs already investigated these crashes, and determined it's not an MTA issue.

**Comment by haron4igg** [comment]
I'm really sorry if i offended you. I didn't mean to. All i did - is forwarded player observations over this issue, as he explained it.
When i googled it - i found old mantis bug closed as 'unable to reproduce'. So i raised this issue.

> Advise users to get the latest Windows 10 release, in this case they may as well go for one that got released yesterday.. Windows 10 October 2020 Update: https://blogs.windows.com/windowsexperience/2020/10/20/whats-new-in-the-windows-10-october-2020-update/

Thank you, i'll contact back this player and will update this thread if problem is solved.

**Comment by Dutchman101** [comment]
No, don't worry, you didn't.. i just gotta motivate why i close these things (quicker). Dragging the background over to new issues can justify jumping to conclusions or show why a case that can otherwise bring doubt from a development perspective, is most likely nothing after all. So purely practical, nothing personal.. sorry if I made you feel that way.

Btw, players say all kind of things, all the time. That (their words directly ending up on our tracker), together with the environment your players are in (a server with scripts and mods that ain't easy on memory or performance, and additionally massive CEF usage to cause further instability for a group of users) is the perfect cocktail for a flow of confusing, utterly random, non reproducible issues. Basically, you'll be hitting a certain, very specific bottom of issues and crashes, which ain't easy for me to put into the right words. 

I was trying to set a precedent for future issues, as I was worried about devs taking them to heart so much that it would affect MTA due to strings of experimental rollbacks..
