### ISSUE TITLE
Refresh rate limited at 60Hz in full screen mode

### ISSUE THREAD

**Issue by StrixG** [multitheftauto/mtasa-blue#1905]
**Describe the bug**
Refresh rate limited at 60Hz in full screen mode.

**To reproduce**
1. Set server FPS to 100.
2. Check refresh rate on monitor that supports more than 60Hz.

**Expected behaviour**
MTA should use available refresh rate and work with adaptive-sync.

**Screenshots**
![az9hzG8lolU](https://user-images.githubusercontent.com/8400907/101267559-9faa6880-3762-11eb-969d-7a7d5e6a62d3.jpg)

**Version**
From https://github.com/multitheftauto/mtasa-blue/commit/ee9a827fe6a34a29bd0262d29b06281cf38ad262

**Comment by Einheit-101** [comment]
I just checked it, i get a lot of stutter when using anything higher than 60 fps in Fullscreen mode because MTA really seems to output only 60Hz. As soon as i go to borderless window mode, i can set my fps up to 75 and i cant get any higher, but MTA successfully outputs 75 fps (I dont see stutter anymore).

So i see 2 issues here:
- MTA not going beyond 60Hz in fullscreen mode, but being able to render up to 100 fps
- MTA not going beyond 75fps in borderless window mode, but being able to render infinite Hz (My monitor is overclocked to 83Hz)

The only reason why i never saw this issue before is simply because i never get more than 60 fps anyway in MTA due to bad performance outside of map editor, my server is locked at 50 :D :D 

€DIT: I recommend just using 59 for minimum stutter and input lag in fullscreen mode and a maximum of 70 when using borderless window mode (Anything beyond 70 causes gameplay bugs anyway)

€DIT2: I have no OSD in my monitor to check the Hz, but i can clearly tell the difference between 83Hz@59fps and 83Hz@75fps or 60Hz@100fps with my eyes.

**Comment by Dutchman101** [comment]
Aside from the fullscreen issue, I believe that if technically possible, MTA should make it a project to raise the refresh rate limits, even if GTA doesn't support more than 60, respectively 75Hz.

A lot of people these days have monitors that go up to 144Hz as well. We added a lot of cool stuff like DPI awareness, custom FOV, and more.. we can probably do this as well.

**Comment by AlexTMjugador** [comment]
Also, however this is fixed, I think a proper fix would play nice with custom resolutions (i.e. video modes that a user added manually in cooperation with the video driver, and are not reported by display EDID). This would respect user refresh rate overclocking and similar things properly. I don't know what APIs we can use, though.

**Comment by Einheit-101** [comment]
Custom resolutions work fine, but not custom hz. I can Set 2k downsampling but i cant get beyond 75fps in window mode.

**Comment by Pirulax** [comment]
~~ I easily had 120+ fps (I've removed the fps limiter). ~~
Nvm, I was't using custom refresh rate.

**Comment by Haxardous** [comment]
![image0](https://user-images.githubusercontent.com/30158626/102019572-68047780-3d85-11eb-8ec4-76482a1312af.jpg)
Borderless keep res

**Comment by Einheit-101** [comment]
So you get 144Hz in window mode but do you get more than 75fps? If yes, then MTA locks the frame rate to the stock screen refresh rate when windowed

**Comment by Haxardous** [comment]
I managed to run MTA on 144hz with standard (fullscreen mode) using software called "RefreshLock" so far it's flawless. can be found here https://www.softpedia.com/get/Tweak/Video-Tweak/RefreshLock.shtml

**Comment by Haxardous** [comment]
> 
> 
> So you get 144Hz in window mode but do you get more than 75fps? If yes, then MTA locks the frame rate to the stock screen refresh rate when windowed

Yes, I do get more than 75fps on windowed mode (actually more than 300fps)

**Comment by Allerek** [comment]
Is it possible to change it with https://docs.microsoft.com/en-us/windows/win32/direct3d9/d3dpresent-parameters
  `UINT                FullScreen_RefreshRateInHz;`
?

**Comment by Dutchman101** [comment]
Through a support interaction on MTA discord, @Lpsd researched and found the exact place where MTA hardcodes the game to run at 60hz only. This is new information (we didn't realize that MTA hardcodes it), and instead of hardcoding it, he also noted that it should be returning a value using EnumAdapterModes instead.. so depending on the monitor's hZ capability or rather the user's current refresh rate in Windows.

Either way, the places it gets hardcoded:
1) [https://github.com/multitheftauto/mtasa-blue/blob/c58c3678f263d810f61eb5aecba48e6c4b4dce0c/Client/core/DXHook/CProxyDirect3D9.cpp#L421](https://github.com/multitheftauto/mtasa-blue/blob/c58c3678f263d810f61eb5aecba48e6c4b4dce0c/Client/core/DXHook/CProxyDirect3D9.cpp#L421)
2) [https://github.com/multitheftauto/mtasa-blue/blob/c58c3678f263d810f61eb5aecba48e6c4b4dce0c/Client/core/DXHook/CProxyDirect3D9.cpp#L446](https://github.com/multitheftauto/mtasa-blue/blob/c58c3678f263d810f61eb5aecba48e6c4b4dce0c/Client/core/DXHook/CProxyDirect3D9.cpp#L446)

If someone finds more places or other code that needs to be updated for fixing this issue, feel free to put it here. 

This also deals with initiating the refresh rate: [https://github.com/multitheftauto/mtasa-blue/blob/c58c3678f263d810f61eb5aecba48e6c4b4dce0c/Client/core/Graphics/CVideoModeManager.cpp#L203](https://github.com/multitheftauto/mtasa-blue/blob/c58c3678f263d810f61eb5aecba48e6c4b4dce0c/Client/core/Graphics/CVideoModeManager.cpp#L203) but not with hardcoding it as the other file does.. although it still may be relevant to the one that's going to fix it.
