### ISSUE TITLE
Upgrade LuaVM to LuaJIT

### ISSUE THREAD

**Issue by fresholia** [multitheftauto/mtasa-blue#1950]
We might want to take a closer look at LuaJIT.  It is obvious that it made a difference to other versions in the tests performed, I didn't see many errors in the tests I did in my local mta build.

According to the tests, it will be great for MTA to work with LuaJIT as a result of a long-term structuring. 

The tests I've done locally on the MTA are as follows:

The code:
```lua
local a = {}
local tick = getTickCount()
local i = 1
while true do
    if i > 500000 then
        break
    end
    a[i] = {x=i, y=-i}
    i = i + 1
end
print("Tick: "..getTickCount()-tick)
```
Lua 5.1: ```Result: 272-290ms```
LuaJIT: ```Result: 74-92ms```

**Comment by Einheit-101** [comment]
Looks like this could improve performance of large scripts by the factor of two... Nice.

**Comment by patrikjuvonen** [comment]
#903

@ccw808 said roughly 2 years ago LuaJIT has been attempted before but it didn't show any significant performance boosts on **a typical server.** He requested practical full script examples that will actually benefit from this.

So a test loop showcase is irrelevant since there is no real use case example. I believe there have been better arguments on #903 and Discord over time.

LuaJIT is one of the top most hot developer wanted features on MTA according to the chats. It keeps coming up.

**Comment by Pirulax** [comment]
Duplicate.
