### ISSUE TITLE
Detailed VF/AC kick messages

### ISSUE THREAD

**Issue by turret001** [multitheftauto/mtasa-blue#1974]
**Is your feature request related to a problem? Please describe.**
People are mostly frustrated when they get kicked because of a non-allowed-program-running (like  VF#33 Server blocks cFosSpeed / LAN manager NetLimit)

**Describe the solution you'd like**
Most of the people already know what program causes it and they're able to close it, but when someone who doesn't comes and asks what the issue is, we have to ask for an MTA Diag log and hand-pick the program causing it. It would be nice if MTA could log the exact process name & process install location to its report.log. Maybe it could also show what process is causing the issue to the end-user as well.

**Describe alternatives you've considered**
1) MTA Client could offer to terminate these processes and wait for user input to allow or disallow it
2) A more detailed error output could be used with instructions on how to end the process. I don't think this is possible considering how small the error popup window is.
3) More clear wording could be used in the error message. This user got 3 program names (cFosSpeed, LAN manager and NetLimiter) but it was only MSI_Gaming_Lan_Manager.exe

**Additional context**
confused players asking for help on Discord:
https://media.discordapp.net/attachments/675939577281773568/794933803231084574/20210102_172248.jpg

case about this guy: he probably had a virus and it has installed a iqvw64e.sys on his system. when you Google what iqvw64e.sys is, you get this result: https://www.file.net/process/iqvw64e.sys.html
guy not only had this program installed, he also didn't have anything related to this program in its system32 folder. turns out, this file was located in C:\Users\username\AppData\Local\Temp\. I had to contact Dutchman to help me figure out where it was installed. I doubt if any end-user knows this file path exists.
There were 3 others that asked for help about this file, if we had its location reported in report.log or somewhere else, I wouldn't have had to disturb Dutchman about it and could've just solved the issue myself.
https://media.discordapp.net/attachments/675939577281773568/794279208141979678/unknown.png

**Comment by Dutchman101** [comment]
It would be a security risk to show a detailed reason (e.g violation technical details, filename or location) for AC kicks in general, because it allows people to debug our detections. Instead, we already have the option to display help pages (e.g [https://updatesa.mtasa.com/sa/trouble/?tr=netlimiter](https://updatesa.mtasa.com/sa/trouble/?tr=netlimiter)) that we can add to detections for which it won't be a security risk.

The list of these help pages, which will be displayed right after getting kicked for a violation to which a help page is linked, is always growing as we can continuously add more of them when manpower is available.

> More clear wording could be used in the error message. This user got 3 program names (cFosSpeed, LAN manager and NetLimiter) but it was only MSI_Gaming_Lan_Manager.exe

Using more clear wording is difficult, as MTA uses generics for many detections of prohibited programs (setting it aside from cheats, which are based on a vulnerability or method for which we use different patching and detections) and therefore it can even match, both on SD (Special Detection) and AC level, tools and programs of the same category we intend to prohibit but which we've never seen before. Therefore, if we always point to the right file, bad people will be able to isolate the detection vector in specific detections, and eventually for example end up with a custom file that contains only something to trigger detection, so they will have isolated it and can use it to work around it.

For your particular example (cFosSpeed / Netlimiter type of programs) there's already such a page with more details (the one mentioned above in this post) and it compensates for the kick message with the more details it provides. We even have split particular Netlimiter software so that it's immediately clear for the most popular of such software: [https://updatesa.mtasa.com/sa/trouble/?tr=lt-netlimiter](https://updatesa.mtasa.com/sa/trouble/?tr=lt-netlimiter) is a different link.

Besides the help pages for individual detections & detection types, we always try to use specific kick messages (after the code.. e.g "AC #4 ToolViolation") wherever possible, to include as much information without giving a hint that's too sensitive. Adding more of these specific kick messages and improving existing ones to include more information, is also subject to manpower and is an ongoing process.

If users really can't figure out what is happening, the AC team is always available to them for support, or through other MTA staff that can contact AC team. That's not an issue to 'bother' them, we are more than happy to help.. as was one of your concerns. But then we can tell them what's going on in our own wording, to avoid telling people too much about the AC (e.g as I mentioned, there are generic detections and also those VF codes you mentioned are things like hooking/manipulating/writing memory to MTA by external software or cheats, viruses - so it's never the same, and we really cannot just provide raw information without security and information fishing risks)

So yeah, thanks for the suggestions but you couldn't know they are impossible because you have insufficient knownledge about how the AC works. I know more reasons why none of this can be practically realized, but because we don't provide information about how the AC operates, i cannot post that in public, but I can still determine it's not feasible because I know that.
