### ISSUE TITLE
DDOS Protection

### ISSUE THREAD

**Issue by talhatugsat** [multitheftauto/mtasa-blue#1975]
It would be nice if MTA had cloudflare-like protection system. There would be the main machine where you would set your server up and install resources there. That main machine would only contact to a cloudflare hosted server and users would download from the cloudflare machine without having to directly connect to the main server. I'll attach an example diagram in this post.

There are only 2 downsides of this system:
1) Users might have higher pings
2) Data could be corrupted while in transfer.

But these downsides are nothing compared to the benefits.

Example image: (my extraordinary paint skills)

![FXZXW5](https://user-images.githubusercontent.com/22572159/103460340-1749c400-4d1e-11eb-9101-7a150dee118e.png)

**Comment by Disinterpreter** [comment]
Hi! Thanks for you ideas. But it is not simple how it looks.

1. Did you try some of UDP proxy?
2. There's no FQDN implementation in MTA so if proxy works bad there aren't another ways.

Did you tried: https://www.cloudflare.com/products/cloudflare-spectrum/

**Comment by talhatugsat** [comment]
what I mean is that my server is growing and I don't have the money to afford it. Big server owners are attacking small servers should never grow, and we are losing the already few players altogether.

What I want to tell you is that a system like this can come to mta.

I'm sorry for my bad english.

**Comment by Disinterpreter** [comment]
> 
> 
> what I mean is that my server is growing and I don't have the money to afford it. Big server owners are attacking small servers should never grow, and we are losing the already few players altogether.
> 
> What I want to tell you is that a system like this can come to mta.
> 
> I'm sorry for my bad english.

So, when you have a time, could you test some UDP-proxy? Just, theoretically it must work fine. (But I don't know what will do ASE)

**Comment by PlatinMTA** [comment]
Sadly I don't think is feasible, altought it would be nice.

MTA is as much protected as it gets when it comes to exploits about flooding your MTA Server with fake download requests and such. There are hosts with special types of anti-DDOS for MTA that, in my case, worked flawlesly. In mid 2018 we used to have a lot of DDoS attacks (mostly from SAMP servers i suppose) but after getting one hosting with special anti-DDOS we didn't get that problem ever again. This can't be said for other platforms, like SAMP, where there are still ways to fuck you up.

Thinking again of the idea, there is one problem. The number one way to connect to an MTA Server in some countries is by giving an IP address with a port. Seeing that you want to maintain your server IP address unknow, you should have an extra IP set up in order to "have a direction". We could also have DNS support as I proposed some time back #1314

**Comment by patrikjuvonen** [comment]
DDoS protection isn't free, and MTA can't do much about it because it's beyond what MTA can do.

If you want DDoS protection, you need to be able to afford it. Cheaper solutions like round-robin DNS should work with MTA if you configure your `mtaserver.conf` correctly. The only issue with them is it requires some manual setup and some networking and routing knowledge.

There really isn't anything we can effectively do about it.

Related to #828
