### ISSUE TITLE
car physics behaviour depends on fps (The rolling inertia of the car depends on the fps)

### ISSUE THREAD

**Issue by Smodaily** [multitheftauto/mtasa-blue#2043]
Dear developers of MTA! I'm here to ask you to fix old and annoying GTA bug. I'm talking about car physics distortion when framerate value is higher than 35. Car brakes intensively when not accelerating , and higher framerate value causes shorter engine braking distance (car just loses inertia and stops almost instantly when you let it go and not pushing brake or gas buttons). This problem has already been solved in single player and sa-mp with the help of this script - FramerateVigilante (https://github.com/GTAmodding/FramerateVigilante). It's so uncomfortable to play with bad car physics and high fps or normal physics with 35 fps.
[Check this](https://youtu.be/6vv65Ldzu70)

**Comment by LosFaul** [comment]
it's well known, but you can't simply change the physics
because you would break massive amout of race maps specially DM maps which are fps dependent

so, it would need to be scriptable, which cars should be in fixed physics mode and which not


about this "FramerateVigilante":
the solution it uses is something that shouldn't be used at all
it has a lot random values in the code which is one of the worst solutions you can try to make in order to fix physics
and it would still not solve the fps dependency issues properly

**Comment by sbx320** [comment]
Ideally we'd entirely decouple "Render FPS" and "Physics FPS". That way scripts could still run at e.g. 50 "Physics FPS", while the game renders at 150 "Render FPS". That'd make playing MTA a lot nicer since it'd allow us to get rid of all kinds of FPS-related issues, while also improving visual quality. 

I'd expect that to be possible, since we're already able to render independantly of physics updates.

**Comment by Haxardous** [comment]
duplication of #929
