### ISSUE TITLE
Bone rotating bugs

### ISSUE THREAD

**Issue by jey-banned** [multitheftauto/mtasa-blue#2046]
**1. Bone's rotation doesn't work with CJ skin.**
*Just use example code from [wiki page](https://wiki.multitheftauto.com/wiki/SetElementBoneRotation) and change skin ids using default admin resource.*

**2. Weapon position and rotation don't take into account bone's position and rotation.**
*This bug cause wrong shot position and it's direction. As the result it affects on functions such as [getPedTargetStart](https://wiki.multitheftauto.com/wiki/GetPedTargetStart) and [getPedTargetEnd](https://wiki.multitheftauto.com/wiki/GetPedTargetEnd). This probably requires additional functions.*

*Screenshot*

**![image](https://user-images.githubusercontent.com/35895532/105729498-57c3e880-5f3e-11eb-94cb-d50764bb03ac.png)**

*Code*
```Lua
addEventHandler ( "onClientPedsProcessed", root, function ( )
	if localPlayer:getTask ( 'secondary', 0 ) ~= 'TASK_SIMPLE_USE_GUN' then return end -- may be deleted
	local bone = 2 -- Pelvis
	local rot = 30
	local yaw, pitch, roll = getElementBoneRotation ( localPlayer, bone )
	setElementBoneRotation ( localPlayer, bone, yaw, pitch - rot, roll + rot )
	updateElementRpHAnim ( localPlayer )
end )

addEventHandler("onClientPreRender", root,  -- Adds the Handler
    function ()
        if getPedTargetStart(localPlayer) then --Checks if there is a Point to start From.

        local x, y, z = getPedTargetStart(localPlayer) -- Gets the Point to start From
        local sx, sy, sz = getPedTargetEnd(localPlayer) -- Gets the Point where the Target Ends

        dxDrawLine3D(x, y, z, sx, sy, sz) -- Draws the Line
    end
end
)
```
*Client: v1.5.8-release-20779
Server: v1.5.8-release-20817*

**Comment by Dutchman101** [comment]
cc @saml1er as the author of PR #1673 which introduced this scripting function. Even though he retired, maybe he knows what the problem could be and mention it

**Comment by jey-banned** [comment]
I've discovered that rotating CJ's bones works with [onClientPreRender](https://wiki.multitheftauto.com/wiki/OnClientPreRender) event only for some reason. The second bug is quite nasty however it can be partially fixed by creating a new weapon element and using bone_attach resource (with updated functions).

**Comment by ricksterhd123** [comment]
I tested this with rot = 0 and the functions getPedTargetStart and getPedTargetEnd seem to align correctly with the crosshair, same with rot = 30 (when aiming down sight)

**Comment by Allerek** [comment]
> I've discovered that rotating CJ's bones works with [onClientPreRender](https://wiki.multitheftauto.com/wiki/OnClientPreRender) event only for some reason. The second bug is quite nasty however it can be partially fixed by creating a new weapon element and using bone_attach resource (with updated functions).

It is because GTA updates positions right before onClientPreRender is called, and then draws the world.
https://wiki.multitheftauto.com/wiki/Game_Processing_Order

**Comment by ricksterhd123** [comment]
As for the issue with CJ, I suspect it's something to do with updateElementRpHAnim not working with CJ skin within onClientPedsProcessed because setElementBoneRotation is changing the rotation but it's not being updated. https://github.com/multitheftauto/mtasa-blue/blob/c661810a4d9c329b1769b3ee27aa8021aa658b54/Client/game_sa/CEntitySA.cpp#L36-L39

**Comment by ghost** [comment]
> 1. Bone's rotation doesn't work with CJ skin.

It doesn't work for CJ because the shoulders of the CJ model are handled a bit differently. To fix this issue, add this code:

![image](https://user-images.githubusercontent.com/10183157/106639683-0d2e1600-65a7-11eb-803d-e75b8efa4263.png)
![image](https://user-images.githubusercontent.com/10183157/106639886-3fd80e80-65a7-11eb-9a6e-8a56d0b759a8.png)

This fixes the problem, but the only problem is that `CPed::ShoulderBoneRotation` is a heavy function. We shouldn't call it more than once for a model. It won't cause that much lag, but it's still not nice. This function is already called in `CPed::PreRenderAfterTest`. Skinning is already pretty slow in GTA SA since it's handled on the CPU rather than the GPU (shaders). Anyways, maybe that's just me. But yeah, this will fix the issue.

> 2. Weapon position and rotation don't take into account bone's position and rotation.

GTA SA uses the camera to calculate the target position. That part of the code is executed way before onClientPedsProcessed event. Unless someone is willing to rewrite the bullet fire code for GTA SA, there's no way to fix it.
