### ISSUE TITLE
setVehicleSound function

### ISSUE THREAD

**Issue by talhatugsat** [multitheftauto/mtasa-blue#2065]
please add setVehicleSound function

Normally we can change vehicle sounds by writing very long lines. It would be great if we had the opportunity to use car sounds by typing setVehicleSound instead.

**Comment by botder** [comment]
Please describe the problem the function should solve, what you expect the function to do, how it should be called and how the game should handle it.

**Comment by talhatugsat** [comment]
Normally we can change vehicle sounds by writing very long lines. It would be great if we had the opportunity to use car sounds by typing setVehicleSound instead.

**Comment by botder** [comment]
Please answer my questions properly. You could solve your problem by writing a Lua function and calling that multiple times.

**Comment by PlatinMTA** [comment]
Pretty sure that you want this: #2020

**Comment by talhatugsat** [comment]
> Pretty sure that you want this: #2020

yes is this

**Comment by LosFaul** [comment]
first of all vehicles have multiple sounds
and i personally wouldn't want to disable all sounds of a vehicle
for example keeping tire sounds enabled...

but there is for real missing an function to disable sounds per element
instead of disabling world sounds which even affects multiple models in many cases
