### ISSUE TITLE
Nitro gets active accidentally when switching language on chat

### ISSUE THREAD

**Issue by ghost** [multitheftauto/mtasa-blue#2204]
When I open the chat, switching my language (ctrl + shift) while I'm on a car. The nitro will get activated suddenly.
While if you opened the chat, pressing Ctrl + shift while you are on your foot, the player will not hit.
Why do I believe this is an issue?  Because there are some servers, you have to work a lot to get nitro, and you can only use it once before you buy it again

**Comment by redeibarnabas** [comment]
That's a server specific issue in my opinion. The nitro doesn't get activated when the chat is active.

**Comment by ghost** [comment]
> That's a server specific issue in my opinion. The nitro doesn't get activated when the chat is active.

I've just tested it with Multi Theft Auto v1.5.8-release-20845
at MTA default server (freeroam)
Windows 10 Pro 64 bits Version 1909 (OS build 18363. 1379)

**Comment by Lpsd** [comment]
What do you mean by "change language" with ctrl + shift? This doesn't appear to be a feature related to MTA, unless it's a specific feature of the server you're playing on (which means it's then not an MTA issue).

edit: I just remembered Ctrl + Shift is for changing the Windows keyboard layout. You can ask the server owner to implement a feature which disables your nitro key during the Ctrl being pressed. Or just change your nitro keybind.

We won't change this in MTA, because it would introduce unexpected behaviour with binds and the Ctrl key.
