### ISSUE TITLE
dbconmy.so: undefined symbol: SSL_connect[03:29:31] on latest Ubuntu 20.04 lts Server 

### ISSUE THREAD

**Issue by gta191977649** [multitheftauto/mtasa-blue#2258]
**Describe the bug**

Hello, I'm trying to deploy my server under the latest ubuntu 20.04, however seems the `dbconmy.so` has completely failed to load in my system.
**To reproduce**
1. I grab the latest build of Linux server `multitheftauto_linux_x64-1.5.8-rc-20868.tar.gz` from https://nightly.mtasa.com/
2. deploy it to my server
3. did all Troubleshooting steps from the wiki, installed `libreadline5` , `libncursesw5`  and grab the `libmysqlclient16` from http://nightly.mtasa.com/files/modules/64/libmysqlclient.so.16 put it into the `/usr/lib/`
4. To start my server with the resources that have the MySQL function, it prompts me an error `dbconmy.so: undefined symbol: SSL_connect[03:29:31] ` (for the screenshot is included)

**Screenshots**

![unknown](https://user-images.githubusercontent.com/2988235/121071739-ac903d80-c813-11eb-94fa-8ca719155d93.png)
![QQ截图20210608044408](https://user-images.githubusercontent.com/2988235/121072169-32ac8400-c814-11eb-9f7a-8fe77aba2f7b.png)

**Version**

multitheftauto_linux_x64-1.5.8-rc-20868.tar.gz (latest nightly builds)
I have also tested it with the stable build `MTA SA Linux Server_1.5.8` but same results.

** Additional **
In additional, i did serveral tests. I did a sqlite version, it works just fine also i tested the mta default login & register (the one using internal.db) works fine too, seems the issue are particularly related to the mysql part of functionality.

**Comment by PlatinMTA** [comment]
I'm pretty sure that #2229 is related. Someone call me on it if I'm wrong.

**Comment by gta191977649** [comment]
> I'm pretty sure that #2229 is related. Someone call me on it if I'm wrong.

I don' think `deathmatch.so` is broken on my end (ubuntu 20.04 lts), I only have encountered the issue with `dbconmy.so` if the MySQL-related functions are used but besides that, everything works fine.

**Comment by botder** [comment]
Ubuntu 20.04 LTS doesn't have the GLIBC issue

**Comment by umithyo** [comment]
I am having the same issue on https://github.com/4O4/mtasa-docker. The base image is Debian Testing (slim)

**Comment by Dutchman101** [comment]
> I'm pretty sure that #2229 is related

This is very much related, and also a result of the OVH fire (having to reconfigure our Linux build agents / relevant build server stuff from scratch)

It is the next issue that users of various distributions will run into, after getting #2229 out of the way. That includes Debian.

So being the same story, MTA would effectively drop full support for many distro's if not fixed before the release of 1.5.9, hence this should be a blocker like #2229 was (im adding it as such). MTA server should work out of the box on the wide range of distro's it has done so before - I don't know if this issue will only affect servers using MySQL (im not a linux user & haven't tried) but i got word of server owners failing to update to newer builds due to this.

Maybe @botder who fixed the initial issue #2229 is interested in fixing this one as well?
cc @ccw808 or @Jusonex for any more input? The release of 1.5.9 is really too close to be blocked like this.

**Comment by jushar** [comment]
I don't think this is related to #2229. The build agent image (https://github.com/JetBrains/teamcity-docker-images/blob/master/context/generated/linux/MinimalAgent/Ubuntu/20.04/Dockerfile#L4) is based upon Ubuntu 20.04 so the GLIBC symbols should be available in theory.

It sounds more like a link issue. Perhaps that SSL function was moved into a different system library? You investigate this using the Linux tools `ldd` and `nm`.

**Comment by CrossFire10100** [comment]
I can confirm this issue, it seems it only appears on builds past MTA:SA Server v1.5.8-release-20833 anything before that it works just fine.

**Comment by botder** [comment]
Please try again with nightly 1.5.8-rc-20887

**Comment by gta191977649** [comment]
> Please try again with nightly 1.5.8-rc-20887
`1.5.8-rc-20887` works now 
The issue can be close now

**Comment by CrossFire10100** [comment]
Just tested! It works. Thank you
