### ISSUE TITLE
onVehicleStartExit incorrectly triggers after #1907

### ISSUE THREAD

**Issue by Lpsd** [multitheftauto/mtasa-blue#2335]
I have a simple script which creates a ped, and puts you both in a separate vehicle. If you attempt to leave the vehicle (detected via `onVehicleStartExit`), you'll be killed and your vehicle is destroyed. 

Sometimes, the `onVehicleStartExit` event gets triggered for the ped too, so subsequently they're also killed and vehicle is destroyed. It seems to only occur if you're quite close to the ped, and/or have dealt enough damage to the ped's vehicle recently (unsure on these being the actual criteria for triggering it).

I've uploaded a video below, you can see it's a little inconsistent to trigger. Watch the debug output at the bottom for the event being fired on both the player and ped.

https://streamable.com/5jutas

I've also uploaded a test resource, it's fairly simple. Just (re)start the resource - yourself and the ped will be spawned and placed in vehicles, then go close to the ped / hit the ped's vehicle and attempt to exit your own vehicle, which will kill you (and probably the ped too).

Can reproduce this all the way back to [r20751](https://nightly.mtasa.com/mtasa-1.5.8-rc-20751-20201207.exe), but not [r20749](https://nightly.mtasa.com/mtasa-1.5.8-rc-20749-20201206.exe) or earlier - which is why I believe it's related to #1907 (cc @Zangomangu)

[vehicle.zip](https://github.com/multitheftauto/mtasa-blue/files/7102271/vehicle.zip) <--- test resource

**Comment by Zangomangu** [comment]
It's a weird bug, but it turns out `onVehicleStartExit` isn't triggering incorrectly.

When you destroy the vehicle and kill the ped in this event, you attempt to jack the ped vehicle afterwards (because the player is on foot now and holding F), which in turn triggers `onVehicleStartExit` for the ped (and then your script kills him & destroys the car)

It was inconsistent because you need to hold down F long enough.

Please test #2344 to confirm it's fixed (can download the artifact)
