### ISSUE TITLE
Missing native rain road reflections detail

### ISSUE THREAD

**Issue by gta191977649** [multitheftauto/mtasa-blue#2345]
**Describe the bug**

We all know that Rockstar North does not future-proof their games. GTA is known to have some graphical issues when played on newer PCs - one of these is bugged road reflections. For some reason, they don't show while it's raining anymore unless you use an ancient/AGP video card.

There are several patches managed to fix this issue in single-player being for a long while, one of the most famous patches called **slient patch** done this job pretty well. however, due to the nature of MTA security measurement, the player is not being able to install any custom patch for the game, thus I'd suggest we can include this fix in the native MTA client, enjoy the authentic graphic that the original game offer.

**Screenshots**

![1427018381_1426948187_gallery10](https://user-images.githubusercontent.com/2988235/132128878-16a70d9c-5f65-47bc-be82-5a7415cff76e.jpg)
![05e416d42a5eee5bd41a0285ae33c32ff6dbefcb33f2359bb073b4f29e6a5447](https://user-images.githubusercontent.com/2988235/132129158-f9afc197-e294-45cc-b6ad-efd5b30ddfc1.jpg)

**Version**
MTASA 1.5.8, but I believe this fix was never added to the MTA yet.

**Comment by Timic3** [comment]
SilentPatch sadly isn't open source (correct me if I'm wrong). SilentPatch itself probably won't be added into MTA due to compatibility and security reasons.

**Comment by AlexTMjugador** [comment]
I definitely like how these reflections look, and think that fixing this kind of game bugs is in scope for MTA. However, I also think that in some circumstances it may be desirable to disable this fix for good reasons. For example, users could be using road objects in a custom map, and for aesthetic reasons they don't want the coronas to reflect in the surface during rainy weather, because the road is below a roof, they spawn a lot of coronas for other reasons, or they use shaders already to make things pretty, for example. I think adding a Lua function like `setGraphicsFixEnabled` (or `setGameFixEnabled`, depending on the scope we want the function to have) to toggle this and other similar fixes (like PS2 style godrays, which I think are also bugged in the PC version) would be a good thing.

**Comment by gta191977649** [comment]
> I definitely like how these reflections look, and think that fixing this kind of game bugs is in scope for MTA. However, I also think that in some circumstances it may be desirable to disable this fix for good reasons. For example, users could be using road objects in a custom map, and for aesthetic reasons they don't want the coronas to reflect in the surface during rainy weather, because the road is below a roof, they spawn a lot of coronas for other reasons, or they use shaders already to make things pretty, for example. I think adding a Lua function like `setGraphicsFixEnabled` (or `setGameFixEnabled`, depending on the scope we want the function to have) to toggle this and other similar fixes (like PS2 style godrays, which I think are also bugged in the PC version) would be a good thing.

I'm agree with that approach, to have a custom function that control this fix.
Maybe we should renamed it like `setRoadReflectionEnable()` instead of `setGraphicsFixEnabled` being more specific like the other existing world functions
