### ISSUE TITLE
onClientProjectileCreation won't be called if rocket explodes immediately

### ISSUE THREAD

**Issue by ghost** [multitheftauto/mtasa-blue#2393]
**Describe the bug**
Event won't be called if projectile (rocket) explodes pretty much instantly.

**To reproduce**
1. Run code given below.
2. Get rocket launcher.
3. Shoot directly under your feet.
4. Profit.

```lua
function onClientProjectileCreation()
	local tickCount = getTickCount()

	print(tickCount)
end
addEventHandler("onClientProjectileCreation", root, onClientProjectileCreation)
```

**Expected behaviour**
It should be called.

**Screenshots**
/

**Version**
Client/server: MTA:SA Server v1.5.9-release-21002

**Additional context**
/

**Comment by MegadreamsBE** [comment]
Question: is that projectile ever really created in this scenario?

**Comment by ghost** [comment]
Only explosion occurs, i've tested with getElementsByType and it shows 0 all the time. I (think that) might solve my issue by using onClientExplosion combined with onClientProjectileCreation - because onClientPlayerWeaponFire isn't reliable for rocket launcher.

**Comment by Proxy-99** [comment]
more like a game bug

**Comment by MegadreamsBE** [comment]
> more like a game bug

Not exactly, a bug implies that it wasn't intentional. However, if the explosion happens immediately there's never a need to create a projectile, which is something that R* devs quite likely considered when writing this code. Intentional game design that unfortunately clashes with our implementation of the projectile creation event.

**Comment by FileEX** [comment]
It's not a bug. The event isn't triggered because no projectile is physically created. In the code, there's a check to see if there's any obstacle within a 0.3 radius. 
![Image](https://github.com/user-attachments/assets/65bd1f4c-f5f6-4a97-8b7c-f0acbb36f624)

If an obstacle is detected, no projectile is created, and instead, the function ``CProjectileInfo::RemoveNotAdd`` is called, which immediately creates an explosion
![Image](https://github.com/user-attachments/assets/a7062a6f-edf2-4cef-a5d7-580567e41e65)
