### ISSUE TITLE
2 screens problem

### ISSUE THREAD

**Issue by matiacp** [multitheftauto/mtasa-blue#2395]
**I basically have 2 screens, the game does not have FPS problems, but when I turn the mouse in circles it starts jerking until it goes down to 4 fps, this does not happen when I keep clicking the screen, I tried all the screen modes and I do not know fix.**

**This is how the error happens:
1. on any server, I move the mouse in circles
2. lower the FPS, it's simple**
[example.zip](https://github.com/multitheftauto/mtasa-blue/files/7275104/example.zip)

**don't lower my FPS, it shouldn't happen**

**
![mta-screen_2021-10-01_22-20-34](https://user-images.githubusercontent.com/91858838/135785243-59c03136-d7f8-42d0-9f61-47158e21dbcc.png)

![mta-screen_2021-10-01_22-21-00](https://user-images.githubusercontent.com/91858838/135785300-efae89ee-12d5-4cf1-bd31-975d68082918.png)

**

**-server/client version (1.5.9)**

**Additional context**

**Comment by Lpsd** [comment]
Could be related to #2017 - regardless, this has nothing to do with having 2 monitors.

Are you the server owner? Can you provide a resource of this interior so we can try to reproduce the issue?

**Comment by PlatinMTA** [comment]
> Could be related to #2017 - regardless, this has nothing to do with having 2 monitors.
> 
> Are you the server owner? Can you provide a resource of this interior so we can try to reproduce the issue?

Hi, I am the server owner. I sent the user here to make the issue because he has this problem apparently since the new 1.5.9, but its a global issue (he was streaming his MTA and even in the map editor he was having huge lag spikes).

I read something on the dev discord about a guy having cpu lag spikes on the official build but he wouldnt get this issues if he had compiled MTA on its own. Maybe its related.

Btw is not related to my issue a while back since that interior he is on the screenshots is Mad Dogg's mansion, and it appears to only lag by moving his camera. I also thougth it could be script related (since I made an update a few days back) but it appear to be something else, because this also happens outside our server.

**Comment by Allerek** [comment]
I remember, Minecraft once had same issue, doing circles with mouse caused lags if too much USB devices were connected.
It was associated with mouse polling rate(refresh rate), might be an issue here too?
https://www.youtube.com/watch?v=5v4zMOQ-sSU
