### ISSUE TITLE
playSound no longer plays WebM Opus files

### ISSUE THREAD

**Issue by theSarrum** [multitheftauto/mtasa-blue#2404]
**Describe the bug**
Opus encoded audio files in WebM container stopped playing after the last BASS update.

**To reproduce**
Steps to reproduce:
1. /start [sound_test](https://github.com/multitheftauto/mtasa-blue/files/7311624/sound_test.zip)
2. Type /playsound

**Expected behaviour**
Files should play as before.

**Version**
Client: Multi Theft Auto v1.5.9-release-21006

**Additional context**
The last version in which this worked was 20974. So most likely something changed in BASS (PR #2377) that broke this.

**Comment by Dutchman101** [comment]
I will contact its developer (un4seen studios) to see if they can confirm this. They usually fix things pretty fast, so as long it stays within this week we don't have to make a move..

**Comment by Dutchman101** [comment]
The results:

```
Un4seen:

Please confirm whether you're using BASSWEBM. Another change in the latest
BASS 2.4.16.7 release was to disable Media Foundation's WebM parser
because it has an event handle leak. I've reported that to Microsoft, so
hopefully it can be re-enabled sometime in future. But for now, BASSWEBM
will be required to play WebM files. It is generally better to use BASS
add-ons instead of Media Foundation whenever possible anyway.

Me:

No, we don't use BASSwebM, but apparently some of our users were using BASS to work with WebM audio (which is odd).

Anyways, MTA doesn't float well with things that break backwards compatibility, because of a low manpower capacity. If i ask someone to implement BASSWebM for now to handle it instead, it's unlikely to happen.
So i guess the only option here is for us to use an older release of BASS, or maybe you can compile a custom version that's the latest changes but re-enables the event handler leaking feature.

Un4seen:

The handle leak in the Media Foundation WebM parser happens any time it
looks at a file, not only WebM files, eg. it'll happen with any
unplayable files too. So I don't think it's a good idea to just ignore it.

I also don't think disabling the Media Foundation WebM support is really
breaking back-compatibility because Media Foundation WebM support was
never mentioned in the BASS docs (only AAC and WMA are).

The WebM support was added to Media Foundation in Windows 10 (I'm not
sure if it was from the start or an update). It was never available for
users of older Windows versions.

As well as avoiding the leak, using BASSWEBM instead will allow older
Windows version users to play WebM files too. All you need to do is add
a BASS_PluginLoad call for it in your
CClientSoundManager::CClientSoundManager function:

     if (!BASS_PluginLoad("basswebm.dll", 0) && BASS_ErrorGetCode() !=
BASS_ERROR_ALREADY)
         g_pCore->GetConsole()->Printf("BASS ERROR %d in PluginLoad
WEBM", BASS_ErrorGetCode());
```

Because leaking is a bad idea and they never intended to support WebM playing with BASS, i can understand they don't have a fix until Microsoft fixes the bug, and also don't want to provide a custom release for us that adds it back (MTA also shouldn't choose for having an event handler memory leak, especially now that they clarified it will leak with any type of audio file being played, every single time)

As playing WebM files is undocumented for BASS and again, as Un4seen confirmed was never intended, im pretty sure you were the only user on MTA doing that. Anyone that was doing this or wants to benefit from other WebM audio features, can open a new issue (or PR) that implements BASSWEBM to exist besides our current set of BASS libraries.. as suggested by Un4seen (and in the bottom of their last reply, implied to be an easy task).

@theSarrum
