### ISSUE TITLE
libcef.dll crash on wine with mtasa 1.5.9

### ISSUE THREAD

**Issue by Sommmmy** [multitheftauto/mtasa-blue#2411]
**Describe the bug**

libcef.dll crash upon entering into options > web browser or entering some servers.

**To reproduce**

1. Go to settings > web browser
2. Wait a couple seconds (notice strange lag)
3. Game crash

**Expected behaviour**

For it not to crash

**Screenshots**

![image](https://user-images.githubusercontent.com/59640424/136882320-ea312383-aeaa-42f8-bdfc-bcc868b3dac8.png)

**Version**

client 1.5.9
Wine(Lutris) on linux
**Additional context**

**Comment by kolezka** [comment]
happens also to me
![image](https://user-images.githubusercontent.com/24277846/148098731-d20d61b2-f213-4b29-bbe6-6e9df3748798.png)

**Comment by jolty1** [comment]
Fix CEF section in link below worked for me

[Fix CEF](https://gist.github.com/qaisjp/778ed99ac8a8dcb93f797a28ba5f8303)

**Comment by TheNormalnij** [comment]
This is old wine issue, was fully fixed once in wine 5.12, but latest wine is broken again.

**Comment by kolezka** [comment]
> Fix CEF section in link below worked for me
> 
> [Fix CEF](https://gist.github.com/qaisjp/778ed99ac8a8dcb93f797a28ba5f8303)

Does not help for me :(

**Comment by kolezka** [comment]
https://github.com/multitheftauto/mtasa-blue/issues/1000 workaround helps me

**Comment by Lpsd** [comment]
I'm pretty sure the gist (Fix CEF) has the same fix listed as #1000 - it just creates a symbolic link instead of moving the files.

Did you successfully create the symbolic links? Did you receive a different error after this?

**Comment by Zorono** [comment]
> I'm pretty sure the gist (Fix CEF) has the same fix listed as #1000 - it just creates a symbolic link instead of moving the files.
> 
> Did you successfully create the symbolic links? Did you receive a different error after this?

already tried any workaround possible to solve this situation but nothing made it work... once i try to launch MTA 1.5.9 under WINE 7 it complains about dxgi related errors and then crashes... while it says that GTA SA is already running and i have to terminate it...

[core.log](https://github.com/multitheftauto/mtasa-blue/files/8009479/core.log)
[logfile.txt](https://github.com/multitheftauto/mtasa-blue/files/8009480/logfile.txt)
[Multi_Theft_Auto_d3d9.log](https://github.com/multitheftauto/mtasa-blue/files/8009481/Multi_Theft_Auto_d3d9.log)
[console.log](https://github.com/multitheftauto/mtasa-blue/files/8009485/console.log)

**Comment by kolezka** [comment]
```
Version = 1.5.9-release-21244.0.000
Time = Fri Jun  3 16:42:10 2022
Module = C:\Program Files\MTA San Andreas 1.5\MTA\libcef.dll
Code = 0x80000003
Offset = 0x02A78D99

EAX=00000000  EBX=00000061  ECX=2FD6F420  EDX=2DE94BB0  ESI=2FD6F88C
EDI=2FD6F470  EBP=2FD6F884  ESP=2FD6F430  EIP=27EF8D99  FLG=00000246
CS=0023   DS=002B  SS=002B  ES=002B   FS=0063  GS=006B
```
any updates?

**Comment by patrikjuvonen** [comment]
We do not support Wine and never have.

This issue is only good for whoever loves Wine can go ahead and try to fix it. Worst case scenario is you will need to build a custom client.

Don't expect any updates from us.

**Comment by gamelaster** [comment]
wine-7.11, latest MTA and #1000 solved crash I had 
**NOTE:** Doesn't work anymore, check my latest post.

**Comment by vahook** [comment]
I think I found the root cause of the issue. [According to MSDN](https://docs.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-setdlldirectorya#:~:text=for%20win32%20processes%20that%20are%20not%20running%20a%20packaged%20or%20protected%20process%2C%20calling%20this%20function%20will%20also%20affect%20the%20dll%20search%20order%20of%20the%20children%20processes%20started%20from%20the%20process%20that%20has%20called%20the%20function.) any call to `SetDllDirectory` should also affect the children processes. However, at first glance, wine seems to ignore this, which could cause  problems in `CEFLauncher.exe`.

![image](https://user-images.githubusercontent.com/4653380/177675630-639f823d-da5e-4ca0-94b9-69a420c12a73.png)

Also, I think that the `InitCEF()` function currently achieves nothing in terms of setting the DLL search path correctly.

https://github.com/multitheftauto/mtasa-blue/blob/0c0ecab94e48257124e6a7504b3e828e83288978/Client/ceflauncher_DLL/Main.cpp#L23-L31

This is because `CEFLauncher_DLL.dll` itself is linked against `libcef.dll`, and the reason `CEFLauncher.exe` doesn't crash right away on Windows is because of a previous call to `SetDllDirectory` in MTA (hence setting it again here is redundant). In fact, if you were to launch `CEFLauncher.exe` manually, you would get an error saying it couldn't find `libcef.dll`.

A somewhat hacky fix I came up with is to use [delayed loading](https://docs.microsoft.com/en-us/cpp/build/reference/delayload-delay-load-import?view=msvc-170). This way `InitCEF()` will do its job setting the DLL search directory correctly before trying to load `libcef.dll`. I've tested it, and this fixes the crash on wine and eliminates the need for the proposed workaround in #1000.

There is both an issue with wine and MTA, I think. Not sure if I should open a PR with the fix though.

**Comment by gamelaster** [comment]
Sadly, for some reason, on **Multi Theft Auto v1.5.9-release-21342**, the workaround from #1000 doesn't work anymore, and CEFLauncher.exe is crashing, not sure what happened :frowning_face: 

~~[backtrace.txt](https://github.com/multitheftauto/mtasa-blue/files/9735079/backtrace.txt) (NOTE: Check backtrace on cerr.txt lower)~~
(Check my last post with all debug info)

**Comment by Lpsd** [comment]
Try using a 64-bit Wine prefix instead of 32-bit. This has worked for a user experiencing CEF crashes and been updated on the [Lutris wiki guide](https://wiki.multitheftauto.com/wiki/Client_on_Linux_using_Lutris_Manual)

**Comment by gamelaster** [comment]
@Lpsd Nope, 64-Bit Wine does absolutely the same thing. I have feeling that something changed within the MTA/CEFLauncher, as when I revert back to older version, it works both on 64-bit or 32-bit prefix.
~~[cefdebug.txt](https://github.com/multitheftauto/mtasa-blue/files/9735274/cefdebug.txt)~~
(Check my last post with all debug info)

**Comment by Lpsd** [comment]
CEF was updated in 394d775 ([r21342](https://buildinfo.mtasa.com/?Revision=21342&Branch=))

**Comment by gamelaster** [comment]
I tested releases [r21339](https://buildinfo.mtasa.com/?Revision=21339&Branch=) and [r21341](https://buildinfo.mtasa.com/?Revision=21341&Branch=), where r21339 is not crashing (before CEF update) and r21341 is crashing (after first CEF update).

Those two files contains `cefdebug.txt` and `cli` (command line output with crash info dump)
[r21339.txt](https://github.com/multitheftauto/mtasa-blue/files/9735972/r21339.txt)
[r21341.txt](https://github.com/multitheftauto/mtasa-blue/files/9735973/r21341.txt)

It was tested on 32-bit prefix, but same thing happens also on 64-bit prefix, as stated upper.

**Comment by olivatooo** [comment]
Still with the same issue, idk if it's a wine problem, a CEF problem or a MTA problem

**Comment by ElPinguino99** [comment]
same issue, and also the fix mentions there are certain files that hasn't been there since version 1.5.7, so there's no solution at the moment

**Comment by Lpsd** [comment]
Are you able to confirm specifically what fix and files you are referring to? Thanks

**Comment by ElPinguino99** [comment]
![1](https://user-images.githubusercontent.com/70829644/209250045-c1366876-9cce-49b6-b741-3a4eee376dc1.png)
On 
[https://github.com/multitheftauto/mtasa-blue/issues/1000](url)
> You must COPY the following files from MTA to MTA/CEF to work around this issue:
>cp libcef.dll chrome_elf.dll icudtl.dat **natives_blob.bin** v8_context_snapshot.bin snapshot_blob.bin CEF

Those, specifically  natives_blob.bin isn't on the folder since then, btw if you perform the fix what it does now is not crashing at all however, it shows you up a blank page and doesn't load nothing at all (example)
![2](https://user-images.githubusercontent.com/70829644/209250795-3d5aacf6-daf8-4719-91d1-8ebee6fa5c4e.png)

**Comment by gamelaster** [comment]
This issue is not related to missing files, it is crash in new CEF build.

**Comment by gamelaster** [comment]
Still happens on wine-7.22 (Staging) :frowning:

**Comment by Shivamexe** [comment]
- Wine 7.2, 32 bit
- Multi Theft Auto v1.5.9-release-21476
- https://github.com/multitheftauto/mtasa-blue/issues/1000

Things are working for me. But, CEF will only show a blank page(don't really care about it).

**Comment by ElPinguino99** [comment]
> - Wine 7.2, 32 bit
> 
> - Multi Theft Auto v1.5.9-release-21476
> 
> - https://github.com/multitheftauto/mtasa-blue/issues/1000
> 
> 
> 
> Things are working for me. But, CEF will only show a blank page(don't really care about it).

If you see a blank page then means that is not working so... doesn't crash? I understand, but that doesn't means that is actually working properly/as supossed to be

**Comment by vahook** [comment]
Sorry, I didn't follow up on my previous comment, but I took a break from playing MTA. Today I decided to investigate things further, and after a bit of debugging and digging into chromium's / wine's source code, I've managed to rediscover this issue in V8: https://bugs.chromium.org/p/v8/issues/detail?id=13512 .
Basically, wine cuts some corners when it comes to "emulating" Windows's memory protection (for a bit more detail, see the linked issue). Fortunately, the patch was merged last week, so I'm sure it won't be long before it trickles down into the stable builds.

I also retested my original fix after bumping up CEF's version to 110 (the current beta version available on spotifycdn.com as of writing), and the issue seems to be gone.
![image](https://user-images.githubusercontent.com/4653380/212799704-8bf41740-79fc-46ec-857a-10f92d3cf273.png)

Funnily enough, I've already stumbled upon the same issue when trying to run MTA debug builds on wine. In `SharedUtil.MemAccess.hpp` the assertions for checking the memory protection values will fail on wine for the same reason. I might open a separate issue / PR for this later.
![image](https://user-images.githubusercontent.com/4653380/212787332-88f0bfbb-6b20-43f1-95fb-c7b36cab2bdf.png)

All-in-all I guess wine players will just have to wait a couple of weeks for the new stable CEF version to arrive. In the meantime, I will submit my PR with the delay-loading fix.

**Comment by gamelaster** [comment]
@vahook sweet! Thank you very much! No more starting of VM to play MTA 😁. Also, wanted to ask, how you figured this out? I never debugged Wine nor Windows app running through Wine, so even I wanted to fix this, I really didn't knew, where and how to start.

**Comment by gamelaster** [comment]
Multi Theft Auto v1.5.9-release-21554 seems to use CEF version, which have fix which @vahook mentioned, and now CEF works again perfectly on Wine! (although, I also updated to wine-8.1 (Staging), so this might do the trick).
EDIT:
There seems to be some issue with font opacity in CEF:
![image](https://user-images.githubusercontent.com/1665373/218804274-94c4a869-01b4-43eb-9f32-5008689f681c.png)

**Comment by gamelaster** [comment]
Multi Theft Auto v1.5.9-release-21622 fixes font opacity :partying_face: 
![image](https://user-images.githubusercontent.com/1665373/227285751-4d6e10cb-4523-4460-9e35-f6cde55b03dd.png)

**Comment by gamelaster** [comment]
Multi Theft Auto v1.6-release-21708 works without any changes on Wine x86 :partying_face: 
![image](https://user-images.githubusercontent.com/1665373/230762620-43acce98-45ba-48fd-8a4c-ace443c42363.png)

After v1.6.0 official release, this issue can be closed I guess.

**Comment by kolezka** [comment]
It just took 2 years... At that time I managed to give up playing mta on Linux. And probably many other people
