### ISSUE TITLE
Crash offset 0x001251C9

### ISSUE THREAD

**Issue by haron4igg** [multitheftauto/mtasa-blue#2423]
Game crashed, when, most likely, vehicle variant been switched, player was on driver sit.

this happen 3 times, first on 21020 and then client was updated and also 2 crasshes happen.

the moment before the crash, car (with driver and camera) appeard in the middle of the game world, 
after reconnect car was in initial place.

```
** -- Unhandled exception -- **

Version = 1.5.9-release-21021.0.000
Time = Wed Oct 27 14:09:26 2021
Module = C:\Games\NS-DayZ\GTA San Andreas\gta_sa.exe
Code = 0xC0000005
Offset = 0x001251C9

EAX=00863C40  EBX=20D80BF0  ECX=1F4789B8  EDX=00B1F654  ESI=00B6F19C
EDI=1F4789B8  EBP=00B6F32C  ESP=0177FB8C  EIP=2065646F  FLG=00010246
CS=0023   DS=002B  SS=002B  ES=002B   FS=0053  GS=002B

** -- End of unhandled exception -- **
```

[client_1.5.9-release-21021.0.000_gtasa_001251c9_5_CGNM_E500A8C0_55F3_084_A6EA6_20211027_1409.rsa.dmp.zip](https://github.com/multitheftauto/mtasa-blue/files/7426349/client_1.5.9-release-21021.0.000_gtasa_001251c9_5_CGNM_E500A8C0_55F3_084_A6EA6_20211027_1409.rsa.dmp.zip)

after 3rd crash, wasn't able to reproduce it again( 
can somebody please check the stacktrace?) 
may be there is some insight of what happen exactly :)

**Comment by Dutchman101** [comment]
It's not a new crash, see stats below:

![crash](https://user-images.githubusercontent.com/12105539/139100497-00db9634-3a37-4c2f-bec5-48aed3d072b2.png)

Before, most of these crashes occured on FFS-Gaming.. but that is no longer. So clearly, FFS changed something in their gamemode so that it no longer happens. It's hard to be specific, but on FFS it still happened a lot in June/July 2021, and at some later moment or month it changed to not happen on FFS anymore.

For the best chances of finding out what triggers it, try to figure out a reproduction script or mod.
