### ISSUE TITLE
Remove or Replace Quick Connect button

### ISSUE THREAD

**Issue by turret001** [multitheftauto/mtasa-blue#2469]
Quick Connect is only there for someone to accidentally press it and almost no one knows that you can r-click it to connect to the last server you played on.
We should either remove it or replace the functionality(and text) to connect to the last server user played on.

**Comment by Fernando-A-Rocha** [comment]
Please someone make this :) a button to simply connect to the last server would be so good

**Comment by PlatinMTA** [comment]
What about #2154?

**Comment by Fernando-A-Rocha** [comment]
> What about #2154?

It lets you disable the buttons optionally. I think some just need to be removed entirely / main menu remade.

**Comment by PlatinMTA** [comment]
> > What about #2154?
> 
> It lets you disable the buttons optionally. I think some just need to be removed entirely / main menu remade.

I understand what it does, but I'm wondering what will happen with PR #2154 after all

**Comment by turret001** [comment]
you're right, if @cleoppa finishes his PR, this issue can be marked as solved

**Comment by PlatinMTA** [comment]
> you're right, if @cleoppa finishes his PR, this issue can be marked as solved

afaik it's finished, but it needs a merge, either way I would love that the quick connect just connects you to the last server you went on without doing Rigth Click.

BTW before the revamp menu the quick connect button served a porpuse, but now it really does not, kind of a shame.

**Comment by fresholia** [comment]
> you're right, if @cleoppa finishes his PR, this issue can be marked as solved

Even though it's over, it needs to be checked because I made it long ago. I'll check and update on the PR if anything goes wrong.

**Comment by botder** [comment]
I wouldn't mind if we swap the behavior of the button to reconnect on left-click and open the 'Local' tab of the server browser on right-click.

**Comment by Dark-Dragon** [comment]
I know a similar proposed change was rejected in the distant past, but I believe combining "Quick Connect" and "Server Browser" into a single "Play" or "Join Game" would make the most sense. Left clicking it should have the combined benefits of clicking "Quick connect" where it shows the most recently connected IPs and the ones of clicking "Server Browser" where it focuses the edit field for immediately enabled keyboard inputs. Ideally the server names for the recently connected IPs (which I believe are already cached) would be displayed to help identify them easier. To obstruct the view of the server browser a little less, the recently connected servers could stack upwards from the edit field instead of downwards. The tab selection between "Internet", "Local", etc could simply default to what the user had selected the last time. Right click could then still be used to immediately reconnect to the last server.

If we then want to go the extra mile, we could aim to make basic keyboard-only navigation possible. IE someone who just started MTA could press 'enter' as the equivalent of clicking 'Play' and then use the arrow keys to navigate upwards (to the recently played pop up) or downwards (to the server browser list entries) from the edit field and press enter to connect to their selected server.
