### ISSUE TITLE
MTA:SA 1.5.9 doesn't run on linux with wine

### ISSUE THREAD

**Issue by 0ud** [multitheftauto/mtasa-blue#2484]
**Describe the bug**

MTA:SA 1.5.9 doesn't run on linux.
when installing it on a 32-bit wine prefix it doesn't install due to **loader.dll** error
on 64-bit prefix it installs and runs but when you try to enter a server it shows an error saying: **No such mod installed (deathmatch)** , map editor & host game don't work as well.

**To reproduce**

1- create a new wine prefix ( you can use winetricks or playonlinux)
2- open lutris and create a new game using the (+) symbol on the top
3- choose wine runner and the wine prefix directory to the directory of wine prefix that we created
4- from runner options, turn off DXVK/VKD3D/Esync
5- click save
6- click on the arrow beside the wine glass logo and click "run EXE in this prefix"
7- choose MTA:SA installation exe file

on 32-bit wine prefix, it will install to the middle then shows the "loader.dll" error
on 64-bit wine prefix, the installation will show no errors

8- from the same menu near the wine logo, click winetricks and choose "choose default wine prefix" then "install a font"
then choose Tahoma and Verdana
9- right click on the game from lutris menu -> configure -> game options -> game executable, and choose the Multi Theft Auto.exe file
10- download mta-server binary and run a server for a minute then launch the game

**Expected behaviour**

I expected it to run well as it did before, but I've got an error in the game that says: **No such mod installed (deathmatch)**.
**Screenshots**

![mtasa-error](https://user-images.githubusercontent.com/41761574/147391329-9951d443-f208-43aa-b1c3-7da5faf4fb32.png)

**Version**

game version is 1.5.9, running on Manjaro Linux using wine on lutris (V. 6.21-10)

**Comment by Dutchman101** [comment]
> MTA:SA 1.5.9 doesn't run on linux

I just want to point out that this statement is incorrect. MTA has quite a few players actively playing 1.5.9 on Linux and Wine, we can see that in our metrics, and they are successfully playing. Most of the issues experienced by some can be explained through misconfigurations, or non ideal configuration (something that for some reason, MTA doesn't float well on).. which is exactly the difficult point, and why we set up our knownledgebase like this:


(Below long post is copied from MTA discord, the pin in #help-support channel)

**MTA supports Linux and macOS through Wine, Lutris, PlayOnLinux, on a best-effort basis.. in a technical sense (about it functioning, if you got everything right) and not in an user support sense.**

**Due to the lack of user support and active development efforts to make it easier and more compatible than it already is, you will have to be an exceptionally experienced Wine user, as you are likely to run into a few issues that you'll have to find a workaround for by yourself. Some workarounds are spread by other Wine users, are generic (on the internet) but we are simply not focussed or specialised enough on support for Wine to investigate all possible issues you can run into, and improve compatibility/provide them in user support. We only had a developer that was specialising into it and improving upon compatibility in the past (qaisjp, but they left).**

**We can tell that there's enough Wine users that are experienced enough to make MTA run on their platforms, as we have metrics and see individual players using Wine through our systems. It remains possible for now, given that you don't cause any misconfiguration (which causes the majority of issues that users run into) but that's the thing - if we are not focussed on Wine support, we won't dig into and establish what a 'misconfiguration' (in the sense of optimal compatibility with MTA) is.. you get the point right?**

**Either way, your best bet is to find another Wine user around here to help you, that knows his math (workarounds, optimal configuration) if the following MTA docs on Linux/macOS support won't cut it:
https://gist.github.com/qaisjp/778ed99ac8a8dcb93f797a28ba5f8303
https://wiki.multitheftauto.com/wiki/Client_on_Linux_Manual
https://wiki.multitheftauto.com/wiki/Client_on_Linux_using_Lutris_Manual**

Back to your case @dzr-mo, this means that as we have a lack of experienced users (support providers) on these topics, you gotta wait until one comes by in case you cannot find the right configuration or way of setting up your Linux for use with MTA. Because such a person isn't readily available (neither are there any devs specialized for it), there is also no one to verify exactly why your reproduction steps, which is your personal configuration/set up of the environment, is considered a misconfiguration or unsupported under MTA's current support for Linux.. so as to determine if it should or can be made to work with exactly that. We advise you to read the guides again, and eventually any other users' information provided on the topic in the past.

We apologize for the lack of official support for MTA on Linux, that causes this to be lacking and uncertain. You're welcome to wait for such an experienced user in our support channels at any time (MTA discord invite link: [https://discord.gg/mtasa](https://discord.gg/mtasa))
