### ISSUE TITLE
GTA IV IN MULTI THEFT AUTO CLIENT 

### ISSUE THREAD

**Issue by xxxwissemxxx** [multitheftauto/mtasa-blue#2493]
**Is your feature request related to a problem? Please describe.**
no its not 
my idea will make mta better i guess 

**Describe the solution you'd like**
adding mta to gta 4 if that is possible 

**Additional context**
gta 4 is just and underrated game
and have maaany players who trying to find a good servers but it end up with failure
cz of  bad clients who had no experience in it
they just start a full of bugs one even tho its soo ez to make one
so gta 4 community and i gently requesting you to try to make it possible please <3
PEACE <3

**Comment by gta191977649** [comment]
What do you mean by GTA 4 in MTA? A Map in GTA 4 ?

**Comment by xxxwissemxxx** [comment]
no like this https://www.youtube.com/watch?v=cty5MPxFDUE&ab_channel=MultiTheftAuto
DM me if u want to talk more bout it :)

**Comment by Lpsd** [comment]
The text in the issue was hidden inside HTML comments, I've removed those.

However, this is the mtasa-blue repository - which is not for making requests for entirely new modifications.

We have enough to deal with, including the crossover of some staff with other projects - meaning our manpower is pretty low right now.

Anyway, regardless of manpower - would we even want to work on GTA4? Probably not.

That's besides the point, closing as offtopic. We've had this conversation a million times with other users (and our stance has never changed) but if you want, you can always join the Discord to discuss more (https://discord.com/invite/mtasa)

**Comment by xxxwissemxxx** [comment]
i see i see bro 
well good luck in your client it awesome 
and i already joined ur server from a year ago

**Comment by Vadya963** [comment]
> i see i see bro well good luck in your client it awesome and i already joined ur server from a year ago

https://gtaconnected.com/
