### ISSUE TITLE
Bad return toggleControl(action, state) in ClientSide

### ISSUE THREAD

**Issue by iiroak** [multitheftauto/mtasa-blue#2606]
### Describe the bug

the function returns false when the function was applied

### Steps to reproduce

*for some reason this bug depends on the position you run this*

1. print the result of the function in different parts of the code.

![imagen](https://user-images.githubusercontent.com/55340002/164918271-7b4ebec4-de42-4680-a635-9b069786e785.png)

### Version

Client: Multi Theft Auto v1.5.9-release-21166
Server: Multi Theft Auto v1.5.8-release-20845

### Additional context

UPDATE: if you add the 2 prints as in the image the 2 will return true, but if you remove 1 the 1st will return false, and the 2nd will return true
the function works correctly, but returns inappropriate values to what happened with it

### Security Policy

- [X] I have read and understood the Security Policy and this issue is not security related.

**Comment by CrosRoad95** [comment]
at wiki: "This function true if the control was set successfully, false otherwise." is a bit unclear what it really means. In source code i found: if state of gta control change return true.

toggleControl("look_behind", true) -- returns true
toggleControl("look_behind", true) -- returns false because it is already toggled
toggleControl("look_behind", false) -- returns true again

reference: https://github.com/multitheftauto/mtasa-blue/blob/master/Client/core/CKeyBinds.cpp#L1186

In my opinion: function should return true until you mess up arguments,

**Comment by iiroak** [comment]
Poorly posed, but still I find there is something wrong with the control of this.
