### ISSUE TITLE
Add serverside vehicles.ide support

### ISSUE THREAD

**Issue by AdrianOkay** [multitheftauto/mtasa-blue#2632]
### Is your feature request related to a problem? Please describe.

In order to properly tune some modded cars it's necessary to change their parameters in the vehicles.ide, currently you can't and it leaves the server devs to ''fix'' the models to be more similar to the vehicle they're replacing

### Describe the solution you'd like

If it was possible to add your own custom vehicles.ide to the server a lot of customization options would appear, i assume that if it hasn't been done yet is for a reason, but even then I insist for the feature to looked further and possibly added

### Security Policy

- [X] I have read and understood the Security Policy and this issue is not about a cheat or security vulnerability.

**Comment by ffsPLASMA** [comment]
Can you explain properties which cannot be changed via setVehicleHandling?

**Comment by AdrianOkay** [comment]
The wheel size's hitbox is stored at vehicles.ide and not the model itself, so if you placed a tahoma's model and handling into the caddy, the car would appear to have tahoma's wheels but still having the caddy's wheel hitbox and it would be clipping to the ground.
The animations of the vehicle are also stored there and so is the ID of the name, texture, model, class, handling and some flags.
This also means editing vehicles.ide could allow you to add more vehicles to the game without needing to replace existing ones in the first place

**Comment by ffsPLASMA** [comment]
Wheels can be changed with https://wiki.multitheftauto.com/wiki/SetVehicleModelWheelSize

You cannot simply add new models/vehicles to the game by just adding them to vehicles.ide file.
Im certain majority if not everything can be changed with setVehicleHandling

**Comment by Lpsd** [comment]
Rather than allowing direct replacement of `vehicles.ide` we would probably look to implement these features individually, through Lua functions (either new, or extending existing ones like `setVehicleHandling`). 

We generally try to add some level of abstraction between this stuff.

There's already a way to add more vehicles to the game without replacing existing ones, see[ engineRequestModel](https://wiki.multitheftauto.com/wiki/EngineRequestModel). It's experimental as far as I know - haven't actually used it myself. Anyway like @ffsPLASMA said you can't just add new vehicles by editing the vehicles.ide file.

Most of the stuff you described should already be achievable with [setVehicleHandling](https://wiki.multitheftauto.com/wiki/SetVehicleHandling) (model, class, handling and some flags)

**Comment by Fernando-A-Rocha** [comment]
> There's already a way to add more vehicles to the game without replacing existing ones, see[ engineRequestModel](https://wiki.multitheftauto.com/wiki/EngineRequestModel). It's experimental as far as I know - haven't actually used it myself. 

Check [this resource](https://forum.multitheftauto.com/topic/133212-rel-add-new-models-library/) out. It puts the new model features to use, letting you add peds, vehicles and objects to your server. It's been tested a lot and is being used in real servers nowadays.

**Comment by JesusOkay** [comment]
You are making excuses, just say that you don't want to work and that's it, the only thing we are asking is that you add the vehicles.ide because the wheels do not work well with the hitbox, and no sirs, it is not possible to do it in any way that You are not saying we are not trying to replace more vehicles, we just want to solve that problem with the wheels.

**Comment by Lpsd** [comment]
> You are making excuses, just say that you don't want to work and that's it

Everyone in this discussion has tried to provide genuinely helpful information. We're trying to establish whether what you're trying to do can already be done via various methods. Please adjust your attitude if you want to remain involved in this repository.

> the only thing we are asking is that you add the vehicles.ide

Adding support for direct replacement of vehicles.ide in the way you're describing will never be done. That doesn't mean we won't introduce the functionality you're requesting, it just means that it needs to be implemented in line with the rest of our Lua API.

Plasma pointed this out earlier - have you tried it yet? https://wiki.multitheftauto.com/wiki/SetVehicleModelWheelSize

What about the flags that are already available via [setVehicleHandling](https://wiki.multitheftauto.com/wiki/SetVehicleHandling)? Have you tried these?

Please report your findings from these suggestions. If they don't suit your requirements then tell us why, provide examples of your code & screenshots or videos of what's wrong. This information is essential in order to help you further.
