### ISSUE TITLE
Network Troubles Improvements

### ISSUE THREAD

**Issue by SDabdlmounaim96** [multitheftauto/mtasa-blue#2642]
### Is your feature request related to a problem? Please describe.

the usual *** Network Trouble *** sign in red always bothers me with how Vague and unspecific it is... it's not helpful at all in diagnosis or anything at all...

### Describe the solution you'd like

my suggestion would be to leave the *** Network Trouble *** sign only for actual "Network Troubles" ( delay in communication between client and server )

and create other error signs in red that specify exactly what's going on.. like :

CPU Usage Overload
VRAM Saturated
Shaders Compilation Errors

### Additional context

i came to the conclusion that the network trouble sign is useless when i was on my LOCAL test server and my computer started new softwares and caused lag, then the sign appeared and said Network Trouble when it's a local server on 1 ping latency, so a network trouble in a local server shouldn't happen for example, it should have said 'CPU Usage Overload'

### Security Policy

- [X] I have read and understood the Security Policy and this issue is not about a cheat or security vulnerability.

**Comment by Lpsd** [comment]
If the server is hanging / frozen, regardless of the cause, then the client's connection to the server is lost. This is why you receive the network trouble message.

The problem with what you are proposing, is how the client is going to receive the reason for the server's loss of connectivity, baring in mind the client has no connection to the server at this point because it's frozen for whatever reason.

I guess technically, we could add some extra diagnostics to the server for detecting performance issues - however these would be displayed in the server logs / console, not to the client.

Even if the network trouble is only temporary and the client remains connected afterwards, I still don't think they have any need to know the cause of the network trouble, that should be visible to the server owner only.

Also, the fact you ran this locally makes no difference to hosting a remote server on dedicated hardware, with regards to the "issue".

On second thoughts, if you are referring to the "opposite" issue whereby the client is freezing due to unknown reasons, rather than the server, which causes the connection loss; then you should investigate your resources using IPB to find out what's causing it. If the root problem turns out to be on MTA's side, rather than poor scripting / implementation, you can post a separate issue for that. 

Changing the "network trouble" message here still isn't the solution, because we would rather fix those issues if they're present in MTA (and not just down to poor scripting).

As for CPU / RAM overload on the client, you likely wouldn't receive network trouble for these, as the GTA process will either just be frozen, or you'll crash (with relevant codes and offsets pointing to what happened). So adding an explicit reason for those is pretty useless in most cases.
