### ISSUE TITLE
There was a problem validating your serial [CN01]

### ISSUE THREAD

**Issue by lux01sv** [multitheftauto/mtasa-blue#2705]
### Describe the bug

So, i am linux player, and i can't launch MTA client. I read many guidelines how to install mta using wine and lutris (including official wiki page) and nothing works. Yes, i tried launching mta server with root, but still stuck.

Before the issue i wrote to MTA discord support, ( those guys are best :) ) but they couldnt help me 

See it:

https://user-images.githubusercontent.com/77214650/183716336-c9c193ee-aac6-4fd0-847b-3cde1f89c4bc.mp4

### Steps to reproduce

1. Go to [https://wiki.multitheftauto.com/wiki/Client_on_Linux_using_Lutris_Manual](https://wiki.multitheftauto.com/wiki/Client_on_Linux_using_Lutris_Manual) and reproduce all step by step
2. You will be stuck at step 7

### Version

Client: 1.5.9
Server: 1.5.9 R2 (build 21258)

**Comment by lux01sv** [comment]
So i also noticed that i can play on my local server if the internet is disconnected

**Comment by EXtremeExploit** [comment]
running the mta server without root worked for me, just a suggestion

**Comment by lux01sv** [comment]
> So i also noticed that i can play on my local server if the internet is disconnected

I tried with and without root, still the same error

**Comment by lux01sv** [comment]
Same as #1906

**Comment by Dutchman101** [comment]
Because most of the Linux issues on MTA are caused by user mistakes (stimulated by not having a decent pathway for technical compatibility & support when playing on Linux or Mac), we have this pinned post on the [MTA discord](https://discord.com/invite/RygaCSD) #help-support channel:

![image](https://user-images.githubusercontent.com/12105539/184120276-2608b298-f021-4566-9315-d929ed365eb8.png)

It is very likely that you ran into an issue by making a mistake in the absolute requirements of the Linux serial verification steps, which can be found here: [https://updatesa.mtasa.com/sa/trouble/?tr=serial-validation](https://updatesa.mtasa.com/sa/trouble/?tr=serial-validation), as intepreting them may require specific knownledge and not suffering from common root/no root problems in Linux environments, where the user is misled. Similar goes for understanding the definition of being "outside any VM", especially when your environment is multi layered or hosted outside of your physical control.

Without going deeper into that, what i want to say is that even if this were some edge case (an issue in our backend that handles verification and it being confirmed), i dont see any possibilities because the MTA developer that built these systems and holds required expertise in investigating any related issues, is no longer active due to life priorities. All i can know for sure is that many thousands of Linux & Mac players have successfully completed the serial verification steps without running into such problems, and many of them are playing MTA regularly - so if it already isn't an user mistake, it definately has to be an edge case (or something where a bug is triggered and that state, in our backends, is unrecoverable).

But again, i dont see any of our current devs ready to investigate and tie a rope to it, which still means the issue can remain open until a day that changes. Sorry for not being able to bring closure at this point, im just being realistic. I advise you keep re-reading and retrying the validation steps in different ways. It may also be an unknown incompatibility with specific Linux environments, so changing configuration around can also be worth it.

@lux01sv

**Comment by lux01sv** [comment]
Thank you for this big answer and explanation 😊

**Comment by Heus-Sueh** [comment]
# Running the Game
I managed to solve this problem using the guide to install MTA server leave it running for 1 minute and close then open the MTA client again

![image](https://user-images.githubusercontent.com/98482469/235331865-2f1ae5c0-1c62-4f43-8227-6ff430bde90d.png)

# Issues
But I found another problem, in the mta menu the game is flickering but when changing the game to window mode it "solves" the problem I believe the problem is with DXVK or Nvidia

# Here is my Settings:
- System: Fedora Silverblue
- Wine Manager: Bottles Flatpak
- Wine Dependencies: allfonts, vcredist2010, dotnet48 (I believe these are the ones needed to run the game and the MTA client)

# Extra Solution:
you can try to run the MTA server using Distrobox with the Arch Linux container and follow the tutorial on [how to run the MTA server on Linux](https://wiki.multitheftauto.com/wiki/Installing_and_Running_MTASA_Server_on_GNU_Linux) to avoid installing old dependencies on the current system this was the method I used because I use an immutable system, if you continue to have a problem with a serial error, try to install the client again.

**Comment by Heus-Sueh** [comment]
another thing, to solve the flickering in the menu you have to enter a server and that's it, after that the menu is normal but every time you open the mta you have to do this process

**Comment by mpesaa** [comment]
Sadly I am using Ubuntu 22 and wine 8 latest, and I have the problem too, been trying to run mta server in my ubuntu as root but no luck yet. I would like to know what dependency might be missing in wine that triggers these issues in serial validation.

what actually should do mta server? it validates what serial? if the serial is inside wine?.

**Comment by Heus-Sueh** [comment]
> Sadly I am using Ubuntu 22 and wine 8 latest, and I have the problem too, been trying to run mta server in my ubuntu as root but no luck yet. I would like to know what dependency might be missing in wine that triggers these issues in serial validation.
> 
> what actually should do mta server? it validates what serial? if the serial is inside wine?.

Can you take a print of the error that happens when you try to run the mta server?

**Comment by mpesaa** [comment]
here is a screenshot 
![Screenshot from 2023-08-17 18-22-03](https://github.com/multitheftauto/mtasa-blue/assets/117742634/467cdf0e-165d-4139-9cf7-63c89cec0706)

**Comment by Heus-Sueh** [comment]
> here is a screenshot ![Screenshot from 2023-08-17 18-22-03](https://user-images.githubusercontent.com/117742634/261372537-467cdf0e-165d-4139-9cf7-63c89cec0706.png)

If I'm not mistaken, you leave the server on and you enter the mta client and it will be able to validate your computer

**Comment by Heus-Sueh** [comment]
sorry maybe I confused with the problem you are having, you are trying to run the MTA server and not the MTA client right?

**Comment by Heus-Sueh** [comment]
see my old comment again, I've updated it with new information.
https://github.com/multitheftauto/mtasa-blue/issues/2705#issuecomment-1528919999

**Comment by Gravarty** [comment]
I've been playing MTA on Linux for a while now, I know how to set up the server, vailidate my serial, etc. But today for some reason it randomly stopped working. Even when I start a new MTA installation, the error message still pops up. I have managed to keep MTA running while being disconnected from the internet and then connected to my local server, which then allows me to connect to any server after reconnecting, this is really weird.

**Comment by CosmicFusion** [comment]
> I've been playing MTA on Linux for a while now, I know how to set up the server, vailidate my serial, etc. But today for some reason it randomly stopped working. Even when I start a new MTA installation, the error message still pops up. I have managed to keep MTA running while being disconnected from the internet and then connected to my local server, which then allows me to connect to any server after reconnecting, this is really weird.

Same issue on all my 4 systems, running Ubuntu, pikaos, arch, arch

**Comment by CosmicFusion** [comment]
But reconnecting presents me with serial error again, so I can only play local server with internet on

**Comment by ja0n** [comment]
> So i also noticed that i can play on my local server if the internet is disconnected

Thanks for that information, it led me to a workaround using systemd-run mentioned in my comment in #3351

**Comment by phz1nnn** [comment]
capeeeeetaaaaaaa

**Comment by gamelaster** [comment]
Hi, I am playing on my ArchLinux MTA, and it works just fine. If you will have any question, let me know.

**Comment by antoniosousadev** [comment]
@gamelaster I have this problem, I use the Manjaro distro. Can you help me?

**Comment by gamelaster** [comment]
@westsidedev did you launched MTA Linux Server through sudo before running the client? Can you also provide more info about what you did in terms of installation?

**Comment by antoniosousadev** [comment]
@gamelaster I hadn't done this before, I had only run the client with wine hahahah but I did what you said and it worked, thank you 👍

**Comment by Fernando-A-Rocha** [comment]
FYI this MTA website is useful 
https://help.multitheftauto.com/sa/trouble/serial-validation/

**Comment by gamelaster** [comment]
@westsidedev Great! Also, I recommend you to checkout this: https://wiki.multitheftauto.com/wiki/Client_on_Linux_Manual I written here many nice tips and tricks which improves many stuff.

**Comment by not0zj** [comment]
I found a solution to the problem
The problem is that there is no space on the disk
You have to provide 3.7 GB space
But I don't think it is enough. Provide 10 GB space

**Comment by Gravarty** [comment]
> I found a solution to the problem The problem is that there is no space on the disk You have to provide 3.7 GB space But I don't think it is enough. Provide 10 GB space

I have plenty of free space but it seems it's broken again with the latest version.
