### ISSUE TITLE
MTA Updater sometimes not working

### ISSUE THREAD

**Issue by Xenius97** [multitheftauto/mtasa-blue#2707]
### Describe the bug

Updater not working

### Steps to reproduce

Press "Check for updates" and MTA will say no update available when there are.
This happens with default & nightly too. You need always to download updates manually from nightly.mtasa.com

### Version

All version (not new bug)

### Additional context

https://i.imgur.com/vq0pqSa.png

### Security Policy

- [X] I have read and understood the Security Policy and this issue is not security related.

**Comment by Xenius97** [comment]
Maybe the problem is nightly version don't updates at https://nightly.mtasa.com/ver/
Don't know how its working but current nightly version is 21282, not 21261

**Comment by PlatinMTA** [comment]
This is intended behaviour. At least thats how it worked through all of 1.5

**Comment by patrikjuvonen** [comment]
> Maybe the problem is nightly version don't updates at https://nightly.mtasa.com/ver/
> Don't know how its working but current nightly version is 21282, not 21261

That is because we are working on renewing our code signing certificate but the process takes some time with back and forth.

**Comment by Dutchman101** [comment]
It's not an issue.. any of the update channels don't move automatically, but when we decide to. For example, the nightly channel is used for specific nightly revisions that we feel can use some testing & monitoring with more users.. so it can be stuck in an older nightly for weeks (despite a new build each day), until devs want something else to enter a testing phase. Users that really want the latest one can go to [https://nightly.mtasa.com/](https://nightly.mtasa.com/)

'Default' update channel in advanced settings is also directed by [https://nightly.mtasa.com/ver](https://nightly.mtasa.com/ver), and again its at our labelling of a certain build as fully stable & therefore to enter the main release.. we use an "MTA as a service" model for years (it's not widely known) which means that we can have multiple of those new stable builds a year and they are sent to all players through auto-updater, without having a new major version. For example, one such updates per 3 months has sometimes packed hundreds of changes from master, so all players can receive regular performance, security updates & get used to the new features before we made an 1.5.x version release announcement, which then becomes more of a heads up of what MTA devs have been up to (everyone gradually got the changes over the preceding year).

You are not getting above r21161 because that's our current designated stable (main release build). Compare the 1.5.9 release date with that build's date, which is almost 1 year apart, with r21161 being from a month ago.
Your incorrect impression that auto updater isn't working is caused by that due to it being the main release build, you will get that build (r21161) by downloading MTA from [https://multitheftauto.com/](https://multitheftauto.com/), therefore letting the auto updater check and see you got the exact build it's currently set to distribute.. not doing anything as intended.

To confirm, can't reproduce:
[https://i.imgur.com/ry1QyIm.mp4](https://i.imgur.com/ry1QyIm.mp4)
Proper repro attempt in the light of what i explained, is manually downloading an earlier revision than you can get from main site DL.. - through [https://nightly.mtasa.com/mtasa-1.5.9-rc-21259-20220708.exe](https://nightly.mtasa.com/mtasa-1.5.9-rc-21259-20220708.exe) in this case - before checking the ingame updater on 'Default' or nightly channel. Because right now, both channels are on r21261. The result of this is as expected, the updater works properly.

* Note: as patrik said, we are planning to bump the update channels as soon we renew the build server cert.. but this is unrelated to the purported issue, which is the proper functioning of auto updater & MTA settings menu updater check, at our direction. We didn't give it direction yet (in a way that affects your impression there's a problem), so there is no bug.
