### ISSUE TITLE
Dynamic ped shadows

### ISSUE THREAD

**Issue by fixlly65** [multitheftauto/mtasa-blue#2799]
### Describe the bug

![obraz](https://user-images.githubusercontent.com/74411430/197557521-2e1ef39a-f553-4818-b16c-d2197f7372b4.png)

With the "Dynamic ped shadows" option turned on, when we get on any bike, the shadow of the character is in the air and it does not look realistic.

### Steps to reproduce

`/`

### Version

Client: v1.5.9-release-21370 (Windows, 32-bit)
Server: v1.5.9-release-21370 (Windows, 64-bit)

### Security Policy

- [X] I have read and understood the Security Policy and this issue is not security related.

**Comment by CrosRoad95** [comment]
64bit client?!

**Comment by lopezloo** [comment]
I know it's closed but I would like to comment: there is not much we can do about that. This is how it works. You can enable "volumetric shadows" option so you will have vehicle dynamic shadows too. It looks a bit weird because in single player it's not possible to configure it in such way (disabled dynamic vehicle shadows and enabled dynamic ped shadows).

We could disable dynamic ped shadows for peds which are on bikes when vehicle volumetric shadows are disabled. But not sure if we should.

**Comment by lopezloo** [comment]
Reopening. Looking for feedback for implementing this:
> We could disable dynamic ped shadows for peds which are on bikes when vehicle volumetric shadows are disabled. But not sure if we should.
