### ISSUE TITLE
Movement bug.

### ISSUE THREAD

**Issue by 9R123** [multitheftauto/mtasa-blue#2878]
### Describe the bug

Bug name: Moving while shooting bug.
Date found: Since MTA increased the FPS.
Description: When you start shooting with a weapon and tried to move left or right you'll be stuck.
Steps to reproduce: It happens randomly, Just aim with a weapon and try to move left or right.
Screenshots/videos:
https://streamable.com/jsnku1
https://streamable.com/7zuqpe

[hr]
https://imgur.com/pPMghFc
https://wiki.multitheftauto.com/wiki/SetFPSLimit

### Steps to reproduce

No need.

### Version

Lastest version 

CIT2 server

### Additional context

I reported the bug to my server admins and they told me it was MTA's bug which they can't fix 

### Security Policy

- [X] I have read and understood the Security Policy and this issue is not security related.

**Comment by Fernando-A-Rocha** [comment]
@9R123 
MTA didn't "increase the FPS", it's in mtaserver.conf
Set the max FPS on your server to 70. Above that bugs will happen afaik

**Comment by 9R123** [comment]
So you guys can't fix it?

**Comment by Dutchman101** [comment]
> So you guys can't fix it?

We can't fix bugs that dont exist. I don't know if its something from the scripts on a specific server (e.g CIT), or their words on it, led you to believe it.. but you should always test in a local server before drawing conclusions

> Set the max FPS on your server to 70. Above that bugs will happen afaik

It's no longer relevant, as that (walking sideways on higher FPS) got fixed in https://github.com/multitheftauto/mtasa-blue/pull/2663 - i will also rid the wiki page he linked of that example where its 'fixed' with script before the MTA fix. On a related note @9R123, i suspect that CIT scripts designed to counter the strafing issues before the MTA fix, are now conflicting with gameplay. Please go back to CIT admins for support
