### ISSUE TITLE
Screen flickering (with CrystalMV's NPC traffic script)

### ISSUE THREAD

**Issue by tkajejebrazorf** [multitheftauto/mtasa-blue#2882]
### Describe the bug

When running the CrystalMV's NPC traffic script, or similar resources that simulate traffic, in some situations (especially when there are multiple vehicles near) the screen starts flickering. By decreasing the traffic density, the problem is reduced but does not disappear. 
Depends on what? How can I fix?
I know of other servers where there is a script that generates traffic (I don't know if it's the same as mine) but there is no problem there.

https://user-images.githubusercontent.com/123834917/215286832-bcbbc2e1-1205-4957-9bb6-e7cdc24326df.mp4

![20230128_200149](https://user-images.githubusercontent.com/123834917/215287175-4d73c7cd-6c98-4f00-9955-c047ed336ee9.jpg)
![20230128_200005](https://user-images.githubusercontent.com/123834917/215287177-624c5c81-66c8-46c4-95a9-694a03527146.jpg)

### Steps to reproduce

1. start CrystalMV's NPC traffic script (or similar resources)
2. travel by roads
3. in some situations you find the bug

### Version

Server: 1.5.9 release-21545
Client: 1.5.9 release-21545

### Security Policy

- [X] I have read and understood the Security Policy and this issue is not security related.

**Comment by HotCandy69** [comment]
Can confirm, I have the same issue happening at my SAPDFR Online server where we're using CrystalMV's resource as a base. In addition to that I just spotted it happening in Joshimuz's recently uploaded youtube video https://youtu.be/mKGgV6UahXY?t=313 (timestamped it). 

Unlike the case of yourself and myself, Joshimuz played on a server with no AI traffic whatsoever but it did occur in a location where lots of players with different vehicle models were present so perhaps it's just the GTA:SA engine not being happy with a bigger variety of vehicles in the area?

**Comment by ffsPLASMA** [comment]
Had this issue for years on ffs, not sure what is causing this though.

**Comment by PlatinMTA** [comment]
This problem is old, but yeah we needed a gh issue on it. Prime Freeroam also suffers from this. Afaik is because there are too many elements streamed in and it breaks the game somehow, that's the only way to reproduce it.

Also I haven't seen it happen on my server with more than 100fps, maybe its less noticeable

**Comment by jlillis** [comment]
iirc it really comes into play when there a large number of different models (rather than elements) streamed in at one time. This occurs frequently when using NPC traffic resources as they are spawning peds and vehicles of random models across the entire range of available models. In single player, the default behavior was to spawn from a limited pool of models based on what part of the map you were in (i.e "poor" vehicles, gangsters/drug dealers/street peds in LS). I notice it happens more frequently with crystalmv's npc traffic resources which have none of this logic vs Prime Freeroam which does some selection of models based on map position.

**Comment by MegadreamsBE** [comment]
Sphene has a similar issue when it plays the scene on the start where CJ is sitting in the cop car and being driven to the start point where you take the bicycle. A few different cars are spawned in during this scene mostly with different models.

**Comment by Zangomangu** [comment]
Same flickering issue as reported in #1326 

To reproduce, spawn peds:

```
ids = getValidPedModels()
x, y, z = 0, 0, 3

for i = 1, 50 do
	createPed(ids[math.random(#ids)], x+math.random(-20, 20), y+math.random(-20, 20), z)
end
```

- The flickering happens for up 5 seconds after ped models are streamed in. Moving the camera seems to provoke it.
- Some skins seem to trigger it more than others, for example fire crotch (87) and clucknbell (167)
- CJ skin never triggers it
- Flickering also happens if you only spawn the same skin ID
- Not specific to peds - also triggers with players
- Been like this for many years so not related to recent changes

As mentioned above, this issue is particularly annoying for servers with traffic, as you are constantly spawning and despawning peds and triggering the flickering a lot.

**Comment by PlatinMTA** [comment]
Does it happen with custom skin models?

**Comment by tkajejebrazorf** [comment]
It happens with custom skin models, but even if I disable all of them.

Yes, actually it should be given by the presence of many types of vehicles and skins very close together on the map. In addition, the kind of "filter" that is present in the singleplayer that limits the variety of models in specific areas of San Andreas is missing.
To fix, I'm trying to thin out the vehicle models and skins that can spawn with the script, maybe even reducing the maximum number of peds in cars to 1 or 2.
Hopefully we'll find a way to fix it permanently because (especially for small servers) a bit of traffic makes everything more alive :)
Thanks so much everyone for the help, the community is awesome.
I will let you know if the changes improve the situation, thanks again everyone.

**Comment by ffsPLASMA** [comment]
From my experience on FFS, it happens sometimes when a new map starts and a decent amount of players (10-30) get spawned as peds inside vehicles at the same time. So it has something to do with alot of elements getting streamed in at once. Not sure if its limited to peds only, maybe vehicles as well. Also not sure if its due to a large amount of unique model IDs as well.

**Comment by lopezloo** [comment]
Duplicate of #1326
