### ISSUE TITLE
Memory leak. Vehicle models are loaded into memory forever

### ISSUE THREAD

**Issue by pentaflops** [multitheftauto/mtasa-blue#2917]
### Describe the bug

If you get/set wheels size of a vehicle that is not loaded into memory, then this model will be forcibly loaded into memory forever
![image](https://user-images.githubusercontent.com/32583328/223076780-a212c1b4-2e1f-4349-a4ab-661f723cee49.png)

Affected functions:
```
CModelInfoSA::GetVehicleWheelSize
CModelInfoSA::SetVehicleWheelSize
CModelInfoSA::GetVehicleDummyDefaultPosition
CModelInfoSA::GetVehicleDummyPosition
CModelInfoSA::SetVehicleDummyPosition
```

### Steps to reproduce

```
local veh = createVehicle(any_model, any_position)
veh.dimension = 666
addVehicleUpgrade(veh, 1083)
```

### Security Policy

- [X] I have read and understood the Security Policy and this issue is not security related.

**Comment by pentaflops** [comment]
Pay attention to "Models in memory"

https://user-images.githubusercontent.com/32583328/223078536-c55cd7e6-4ff8-4fc5-a72c-e7e1acec1ebd.mp4

**Comment by tederis** [comment]
Does **engineStreamingFreeUpMemory** unload these models?

**Comment by tederis** [comment]
**CModelInfoSA::Request** isn't increasing a model's ref count. In theory, GTA streamer should take care about it and unload weak models when more memory needed. In addition, MTA has a model cache that keeps vehicle models for some period of time.

**Comment by pentaflops** [comment]
> **CModelInfoSA::Request** isn't increasing a model's ref count. In theory, GTA streamer should take care about it and unload weak models when more memory needed. In addition, MTA has a model cache that keeps vehicle models for some period of time.

These models hang in memory with 0 refs. They do not get into the MTA cache (see on "Model cache" in video). Streaming GTA does not process them in any way and does not clean them up, even if the streaming memory is over

**Comment by AlexTMjugador** [comment]
I dug up a bit into the cause of this leak. @tederis remark about unreferenced models being candidates for eventual cleanup by the game, or at least by `CStreaming::MakeSpaceFor`, makes sense. I'd say it's correct after some initial investigation.

Interestingly, I noticed that the affected functions end up calling `CStreaming::RequestModel` with the `STREAMING_GAME_REQUIRED` (0x2) and `STREAMING_MISSION_REQUIRED` (0x4) flags set:

![Code screenshot](https://user-images.githubusercontent.com/7822554/227387252-a121b52b-a26b-4a4b-8502-56f06627b550.png)

I don't think that these flags prevent `CStreaming::MakeSpaceFor` from unloading these models, but methods like `CStreaming::CarIsCandidateForRemoval` definitely seem to exclude models loaded with these flags.

On the other hand, the `CClumpModelInfo::CreateInstance` method, which is called by `CVehicleModelInfo::CreateInstance`, calls `CBaseModelInfo::AddRef`. I'm not sure whether MTA or GTA call `CreateInstance` at all, but it seems likely, and it would explain why `engineStreamingFreeUpMemory` doesn't free up that model: it always has at least one reference.

The only reason why `CModelInfoSA::Request` was called in `set/getVehicleModelWheelSize` was to avoid a null pointer dereference in the `m_pInterface` accesses that follow. However, examining the assignments to `m_pInterface` reveals that it is assigned from the value of `ppModelInfo[m_dwModelID]` all over the place, even though it is initially set to `NULL`, with no guarantee that I can see for it being initialized on the affected methods.

Therefore, a fix for the original null pointer dereference issue could be to call `CModelInfoSA::GetInterface` instead of accessing `m_pInterface`, which ensures that this initialization is done, instead of loading the model, which is troublesome. This approach should be tested, and probably someone more knowledgeable about GTA: SA internals should chime in, but I would not mind submitting a PR for it.

**Comment by TheNormalnij** [comment]
Affected Lua functions:
* [getVehicleModelDummyDefaultPosition](https://wiki.multitheftauto.com/wiki/GetVehicleModelDummyDefaultPosition)
* [setVehicleModelWheelSize](https://wiki.multitheftauto.com/wiki/SetVehicleModelWheelSize)
* [getVehicleModelWheelSize](https://wiki.multitheftauto.com/wiki/GetVehicleModelWheelSize)
