### ISSUE TITLE
setCursorAlpha can change the cursor transparency when the main menu or console is visible

### ISSUE THREAD

**Issue by xLive** [multitheftauto/mtasa-blue#2944]
### Describe the bug

As the title says, [setCursorAlpha](https://wiki.multitheftauto.com/wiki/SetCursorAlpha) function can modify cursor transparency when the main menu/console is visible. The cursor should always be fully visible when they are shown, and servers should not have control over its transparency.

### Steps to reproduce

1. Open the main menu or the console.
2. Use [setCursorAlpha](https://wiki.multitheftauto.com/wiki/SetCursorAlpha) to change the cursor transparency while the main menu or console is visible.

### Version

v1.5.9-release-21622

### Additional context

https://user-images.githubusercontent.com/30420446/229906643-35e39904-0716-43cb-84fe-4ea715f0f87d.mp4

### Security Policy

- [X] I have read and understood the Security Policy and this issue is not security related.

**Comment by Lpsd** [comment]
I think the best way to handle this would be to queue any calls to `setCursorAlpha` whilst the main menu or console is visible. There should only be one "call" in the queue at any time (the latest one). 

When the player leaves the main menu / console, the cursor alpha is then applied.

**Comment by Einheit-101** [comment]
> I think the best way to handle this would be to queue any calls to `setCursorAlpha` whilst the main menu or console is visible. There should only be one "call" in the queue at any time (the latest one).
> 
> When the player leaves the main menu / console, the cursor alpha is then applied.

But then you need to make the cursor visible again as soon as the player opens console again

**Comment by Lpsd** [comment]
> But then you need to make the cursor visible again as soon as the player opens console again

This is already the case. See [here](https://github.com/multitheftauto/mtasa-blue/blob/2d9e03324b07e355031ecb3263477477f1a91399/Client/core/CGUI.cpp#L385) and [here](https://github.com/multitheftauto/mtasa-blue/blob/2d9e03324b07e355031ecb3263477477f1a91399/Client/core/CGUI.cpp#L434)

But actually upon further inspection, we don't even need to do what I suggested, since it already restores the server's current cursor alpha upon closing the console/menu. We simply need to stop calls to [CStaticFunctionDefinitions::SetCursorAlpha](https://github.com/multitheftauto/mtasa-blue/blob/e50822ac3041267913d4494d855d8fb650752844/Client/mods/deathmatch/logic/CStaticFunctionDefinitions.cpp#L5029) if the main menu or console is currently visible.

**Comment by xLive** [comment]
> We simply need to stop calls to [CStaticFunctionDefinitions::SetCursorAlpha](https://github.com/multitheftauto/mtasa-blue/blob/e50822ac3041267913d4494d855d8fb650752844/Client/mods/deathmatch/logic/CStaticFunctionDefinitions.cpp#L5029) if the main menu or console is currently visible.

If I'm not wrong, we also need to update the value of [m_fCurrentServerCursorAlpha](https://github.com/multitheftauto/mtasa-blue/blob/09baa24d6b1c20e05c07625a6bf214429634a4e1/Client/gui/CGUI_Impl.cpp#L502). Otherwise, this will lead to unexpected behavior for scripts that use `getCursorAlpha` and `setCursorAlpha`.
