### ISSUE TITLE
EngineLoadIMG raw support

### ISSUE THREAD

**Issue by Xenius97** [multitheftauto/mtasa-blue#2947]
### Is your feature request related to a problem? Please describe.

Currently all engine* functions are supporting raw data except this. Possible to add raw data support to engineLoadIMG? Cause if you wan't to protect your models, you need to compile it with some method like tea, aes128 and impossible to load if function doesn't supporting it.

### Describe the solution you'd like

-

### Describe alternatives you've considered

Some way to protecting models and use this feature too.

### Security Policy

- [X] I have read and understood the Security Policy and this issue is not about a cheat or security vulnerability.

**Comment by AlexTMjugador** [comment]
While I find that this feature can be useful, I think it's worth pointing out that IMG files can get quite large (the default `gta3.img` file is almost 1 GiB in size), so storing them in a binary Lua string can be pretty memory-intensive. Other engine functions work with much smaller data, so they are less likely to cause unstability problems due to exhausting the limited virtual address space of a 32-bit process.

**Comment by Xenius97** [comment]
Another solution could be if engineImageLinkDFF/TXD could support raw data. Idk how it works, @TheNormalnij is there any way to solve this?

**Comment by JeViCo** [comment]
Some sort of loading by chunks?

**Comment by quiret** [comment]
The GTA:SA engine is using special Win32 overlapped I/O to read data from IMG containers. I highly doubt this is possible without rewriting that part.
