### ISSUE TITLE
playercolors irregularity

### ISSUE THREAD

**Issue by F2BShady** [multitheftauto/mtasa-blue#3076]
### Describe the bug

https://imgur.com/eE8xYYC

I downloaded the latest version mta server file and started localhost server but it gave an error as shown in the screenshot, I think it needs minor editing by mtaserver.conf.

### Steps to reproduce

mtaserver.conf file can be edited

### Version

MTA:SA Server V1.6-release-21852

### Security Policy

- [X] I have read and understood the Security Policy and this issue is not security related.

**Comment by jlillis** [comment]
Strictly speaking, this is not an error but just an advisory notice that playerblips will be using the blip color defined by the resource setting rather than the nametag color that would be set by playercolors if it was running. Whether or not mtaserver.conf should be edited to launch playercolors by default is a good question.

**Comment by F2BShady** [comment]
yes true but what I want to point out is that I downloaded the new mtaserver version and just ran it and saw this warning

**Comment by F2BShady** [comment]
and I did not edit or start the file I specified
