### ISSUE TITLE
Data file d3dcompiler_43.dll is modified error

### ISSUE THREAD

**Issue by Xenius97** [multitheftauto/mtasa-blue#3200]
### Describe the bug

![image](https://github.com/multitheftauto/mtasa-blue/assets/6568348/edf0542e-9a7a-4960-b483-84aa682305b5)

### Steps to reproduce

Update MTA

### Version

1.6.0-9.22259.0

### Additional context

Before update i had no error like this, no virus on my pc.

### Security Policy

- [X] I have read and understood the Security Policy and this issue is not security related.

**Comment by Xenius97** [comment]
@Dutchman101 i think its caused by https://github.com/multitheftauto/mtasa-blue/commit/b7c73744bc24791cfff7bb3bedc44dc225485159

**Comment by botder** [comment]
Are you on Windows 10 or 11, or older?

**Comment by Xenius97** [comment]
Windows 11 latest

**Comment by Xenius97** [comment]
![image](https://github.com/multitheftauto/mtasa-blue/assets/6568348/407fe72b-e1f9-45b9-aadb-e69a79c02e2d)

**Comment by Dutchman101** [comment]
Thanks for reporting, it's caused by the nightly updater channel (you're using it) and we got it under control now. This revision has been pulled from nightly channel until we sync DLL's in the updater package.

Anyone that selected nightly channel (what is also known as "If you like to be filling out bug reports"/experimental versions) can fix it for themselves by running mtasa-1.6.0.exe from https://multitheftauto.com > "Download" button
