### ISSUE TITLE
Issue with displaying custom Discord RPC status

### ISSUE THREAD

**Issue by ghost** [multitheftauto/mtasa-blue#3222]
### Describe the bug

If i'm connected to a server where the custom Discord RPC AppID is enabled and turn on the RPC in the settings, the default MTA:SA message appears instead of the custom message.

### Steps to reproduce

1. Connect to a server that uses the setDiscordApplicationID function.
2. Enable Discord Rich Presence in the MTA settings.

### Version

Multi Theft Auto v1.6-release-22279 (latest nightly)

### Security Policy

- [X] I have read and understood the Security Policy and this issue is not security related.

**Comment by Dutchman101** [comment]
Please take a closer look at the announcement in [MTA Official Discord](https://discord.gg/mtasa):
![ann](https://github.com/multitheftauto/mtasa-blue/assets/12105539/3fec07ac-79d6-47bc-ad9a-b1cec99d8c6c)

Make sure to understand and follow the prerequisites, like that not only the client, but also server has to be updated to the corresponding Nightly (test) build, **which is the most likely culprit**.

I don't think there is a way you're not making a mistake somewhere, because we are watching other server owners successfully do what you are trying to do, it's a scenario that has been tested.
@Nico8340

**Comment by Lpsd** [comment]
Use `isDiscordRichPresenceConnected` to check periodically if the client has enabled rich presence and set your custom status.
