### ISSUE TITLE
MySQL SSL connection error: unknown error number

### ISSUE THREAD

**Issue by Xenius97** [multitheftauto/mtasa-blue#3270]
### Describe the bug

[2023-12-15 09:25:20] WARNING: [core]\ex_mysql\server\classes\mysql.lua:27: Bad usage @ 'dbConnect' [SSL connection error: unknown error number]

I think its caused by https://github.com/multitheftauto/mtasa-blue/commit/6f1ccc8e778166025d19867ac043f891ad2c238f

### Steps to reproduce

dbConnect()

### Version

22331

### Security Policy

- [X] I have read and understood the Security Policy and this issue is not security related.

**Comment by Xenius97** [comment]
mysql log:
```
2023-12-15T08:23:52.857366Z 0 [System] [MY-010116] [Server] e:\wamp64\bin\mysql\mysql8.0.31\bin\mysqld.exe (mysqld 8.0.31) starting as process 11848
2023-12-15T08:23:52.914364Z 1 [System] [MY-013576] [InnoDB] InnoDB initialization has started.
2023-12-15T08:23:53.873515Z 1 [System] [MY-013577] [InnoDB] InnoDB initialization has ended.
2023-12-15T08:23:54.591678Z 0 [Warning] [MY-010068] [Server] CA certificate ca.pem is self signed.
2023-12-15T08:23:54.592137Z 0 [System] [MY-013602] [Server] Channel mysql_main configured to support TLS. Encrypted connections are now supported for this channel.
2023-12-15T08:23:54.621375Z 0 [System] [MY-010931] [Server] e:\wamp64\bin\mysql\mysql8.0.31\bin\mysqld.exe: ready for connections. Version: '8.0.31'  socket: ''  port: 3306  MySQL Community Server - GPL.
2023-12-15T21:12:51.100215Z 0 [System] [MY-013105] [Server] e:\wamp64\bin\mysql\mysql8.0.31\bin\mysqld.exe: Normal shutdown.
```

**Comment by Xenius97** [comment]
Seems like disabling SSL solved

```ini
[mysqld]
ssl=off
```

**Comment by TracerDS** [comment]
> Seems like disabling SSL solved
> 
> ```ini
> [mysqld]
> ssl=off
> ```

Disabling SSL might be a security issue in the near future. Its better to fix it from the origin instead of taking the easy way out

**Comment by Xenius97** [comment]
Okay, i think latest libmysql update broke mysql SSL, thats why didn't work.

**Comment by Lpsd** [comment]
I don't think SSL ever worked with our MySQL implementation, see #2772

**Comment by Xenius97** [comment]
No errors with older server version

**Comment by Allerek** [comment]
> No errors with older server version

Quick guess that in older versions when you tried SSL but failed it just tried non-ssl connection. Now it might try to enforce SSL and not fall back to non-ssl on failure.

**Comment by theSarrum** [comment]
I have an idea why this is happening. All this time, an old version of libmysql.dll (6.1.3.0) was shipped with the Windows server. After [this change](https://github.com/multitheftauto/mtasa-blue/commit/6f1ccc8e778166025d19867ac043f891ad2c238f) botder noticed it and updated [the old files](https://github.com/multitheftauto/mtasa-blue/commit/6108f0f02b4ae49101498f40600664327ca6d032).

You might ask, what could have changed between 6.1.3.0 and the current version (6.1.11.0)? My guess is that the issue is that SSL was not used before, but with the new version it is now enabled by default.

Why is there a connection issue? The issue is that the MySQL connector supports only TLSv1 and TLSv1.1 protocols when compiled with yaSSL. Starting from MySQL 8.0.28, [TLSv1 and TLSv1.1 are no longer supported](https://dev.mysql.com/doc/refman/8.0/en/encrypted-connection-protocols-ciphers.html#:~:text=As%20of%20MySQL%208.0.28%2C%20MySQL%20no%20longer%20supports%20the%20TLSv1%20and%20TLSv1.1%20protocols.%20From%20this%20release%2C%20clients%20cannot%20make%20a%20TLS/SSL%20connection%20with%20the%20protocol%20set%20to%20TLSv1%20or%20TLSv1.1.).

If this is indeed the case, there are 2 possible solutions:
1) Build libmysql with OpenSSL, [which would enable TLSv1.2 support](https://dev.mysql.com/doc/refman/5.7/en/ssl-libraries.html#:~:text=OpenSSL%20supports%20TLSv1%2C%20TLSv1.1%2C%20and%20TLSv1.2%20protocols.%20yaSSL%20supports%20only%20TLSv1%20and%20TLSv1.1%20protocols.);
2) [Disable TLS encryption](https://dev.mysql.com/doc/c-api/5.7/en/mysql-options.html#:~:text=MYSQL_OPT_SSL_MODE%20(argument%20type%3A%20unsigned%20int%20*)):
```cpp
int ssl_mode = SSL_MODE_DISABLED;
mysql_options(m_handle, MYSQL_OPT_SSL_MODE, &ssl_mode);
```

If we choose the second option, it is probably better to add an option for dbConnect.

**Comment by TracerDS** [comment]
We should go with the first one. Not having SSL is... A shame to say at least

**Comment by emmmhx** [comment]
@Xenius97 What version of mysql server you are using now? I need a stable one for the server.

**Comment by Xenius97** [comment]
> @Xenius97 What version of mysql server you are using now? I need a stable one for the server.

8.2, latest WampServer (local)

**Comment by TheNormalnij** [comment]
Some linux servers have related issue
```
ERROR: Could not load /game/mods/deathmatch/dbconmy.so - libssl.so.1.1: cannot open shared object file: No such file or directory
[23-12-28 21:34:49] WARNING: [System]/nelski/login_server.lua:4: Bad usage @ 'dbConnect' [Could not connect]
```

**Comment by TracerDS** [comment]
When the MySQL server enforces SSL, this will still happen again no matter if you enable SSL via options or not
