### ISSUE TITLE
MTA error CL22  (Antivirus blocking) 

### ISSUE THREAD

**Issue by Daylon92** [multitheftauto/mtasa-blue#3299]
### Describe the bug

When I run MTA the following error appears: MTA: San Andreas  [CL22]  (CTRL+C to copy)
Could not start Grand Theft Auto: San Andreas.  Please try restarting, or if the problem persists,contact MTA at www.multitheftauto.com. 
[Error 5: Acesso negado. (ShellExecute)]
Want to get online help with this problem?
![Mta error CL22](https://github.com/multitheftauto/mtasa-blue/assets/157773696/8edb9ed7-dab1-42a1-bd23-331f059290e9)

### Steps to reproduce

1 - I open MTA San Andreas
2 - An error message appears

(Solution):
3 - Close the Kaspersky antivirus program
4 - I open MTA San Andreas, done the magic, it enters normally

### Version

Client Multi Theft Auto 1.6

### Additional context

The only solution I found to play MTA San Andreas was to close Kaspersky antivirus program, only then can I access MTA. Previously it didn't cause this error, but it seems that the latest MTA updates are causing an incompatibility with Kaspersky.

### Security Policy

- [x] I have read and understood the Security Policy and this issue is not security related.

**Comment by Dutchman101** [comment]
> Previously it didn't cause this error, but it seems that the latest MTA updates are causing an incompatibility with Kaspersky

It's bad behavior from Kaspersky (false positive/interfering with MTA), not the other way around. We reported it to Kaspersky, let's hope they care to fix it as quickly as possible. Until then, users can switch to a different security product (like: ESET-NOD32 or Windows Defender) or if they know what they are doing, disable it while playing.

Because this isn't an MTA issue, its being closed
