### ISSUE TITLE
Lua debugger

### ISSUE THREAD

**Issue by gtkvba** [multitheftauto/mtasa-blue#3302]
### Is your feature request related to a problem? Please describe.

I'm always frustrated when it comes to script troubleshooting. Often, the issue stems from the MTA itself and its poorly written code. I encountered a problem with my script, and surprisingly, the cause was quite simple - isPedInVehicle was somehow returning false even when the player was in the vehicle. It took me hours to identify the cause (adding print statements in each function XD, mta script debugging in a nutshell). The code was working until one day.

### Describe the solution you'd like

We should make a functioning Lua clientside/serverside script debugger with features such as:

-     Stepping through code
-     breakpoints
-     stack traces and Lua constants

Debugger would save a lot of time and unnecessary problems. 

### Security Policy

- [X] I have read and understood the Security Policy and this issue is not about a cheat or security vulnerability.

**Comment by TracerDS** [comment]
How, in your opinion, would debugging look like?
You dont need a debugger to write good scripts. Only knowledge and output functions is all you need

**Comment by gtkvba** [comment]
> How, in your opinion, would debugging look like? You dont need a debugger to write good scripts. Only knowledge and output functions is all you need

Read the issue once again, it wasnt even related to the script itself but to buggy isPedInVehicle implementation.
Code was functioning fine until one day, without any changes made for at least eight months. Despite efforts, I couldn't reproduce the issue in my external development environment, even with identical scripts and input data (and server revision). This left me with one option the most hilarious one - adding print statements to every function on the main server and restarting the scripts, which impacted player gameplay. It all points to one solution: implementing a debugger.

I think that a good debugger is a principle of creating stable software.

How would it look like?

The client would have a debugger tool as an IDE plug-in, which would connect through a socket to the MTA process, and the communication would begin. The server would decide which client can launch the debugger.

**Comment by TheNormalnij** [comment]
@gtkvba Did you try [this debugger](https://marketplace.visualstudio.com/items?itemName=TheNormalnij.mtard)?

**Comment by Dutchman101** [comment]
Not to be mean, but this sounds like a skill issue to me.. general debugging skills are to be applied to a stack in which one is specialized.

You wrote that you've spent hours adding print statements to get closer to the problem, that's an inefficient debugging session, as you momentarily lacked insight (a sense) of what it could be, as in: what it's likely to be/what makes sense to be the root cause of the chain of failures down the road of the execution of your script. This lack of insight led to wasting time, as it prevented you from adding debug lines in the right places until later on, after much straining.

Proficiency in debugging comes with the ability to see right through certain things and get a good approximation of the problem based on the incorrect behavior and the first results of looking into it/adding tests, and being able to see the bigger picture & knowing what you're working with (and its design) is also crucial for that.

Closing the issue; it's mostly POV and TheNormalnij pointed you in the right direction: if you are looking for such a debugging tool, and you think it lacks functionality that you need, i suggest you contribute to the [MTATD repository](https://github.com/TheNormalnij/MTATD) to have it reflected in the [VScode plugin](https://marketplace.visualstudio.com/items?itemName=TheNormalnij.mtard). It's prefered to have MTA Lua debuggers in code editors that are commonplace, over in MTA.

**Comment by gtkvba** [comment]
How the fuck u want me to debug code which should work as intended?  The issue was in MTA Itself. Sound like a big skill issue to me lmao

**Comment by gtkvba** [comment]
> @gtkvba Did you try [this debugger](https://marketplace.visualstudio.com/items?itemName=TheNormalnij.mtard)?

I haven't tried it because it's server-based, and MTA doesn't have any implementation to do it on the client-side. That's why I created this issue. Also, your project has many issues, like a lack of remote debugging.

**Comment by TheNormalnij** [comment]
> > @gtkvba Did you try [this debugger](https://marketplace.visualstudio.com/items?itemName=TheNormalnij.mtard)?
> 
> I haven't tried it because it's server-based, and MTA doesn't have any implementation to do it on the client-side. That's why I created this issue. Also, your project has many issues, like a lack of remote debugging.

My debugger works on client-side too.
