### ISSUE TITLE
Only 3 water cannons on Fire Truck can be used at the same time

### ISSUE THREAD

**Issue by idarrr** [multitheftauto/mtasa-blue#3315]
### Describe the bug

idk if this was intended but only 3 water cannons are spraying out the water
![image](https://github.com/multitheftauto/mtasa-blue/assets/24439261/dcffbad6-69ca-4ca6-972a-ac09bd55c68b)

### Steps to reproduce

1. Spawn 5 Fire Trucks
2. Warp 5 peds into each Fire Trucks
3. Use setPedControlState(ped, "vehicle_fire", true)
4. Only 3 water cannons are spraying out the water

Or use this resource:
[watercannon.zip](https://github.com/multitheftauto/mtasa-blue/files/14298367/watercannon.zip)
1. Goto coordinate 0, 0, 0,
2. Start the resource

### Version

Client: Multi Theft Auto v1.6-release-22388 (Windows)
Server: MTA:SA Server v1.6-release-22388 (Windows)

### Security Policy

- [X] I have read and understood the Security Policy and this issue is not security related.

**Comment by FileEX** [comment]
I don't think this can be considered a bug in the MTA. GTA SA has a coded water cannons limit of 3.

![image](https://github.com/multitheftauto/mtasa-blue/assets/26044224/41ce06af-e182-4245-b19d-8563f8c15966)

https://github.com/gta-reversed/gta-reversed-modern/blob/1b37b015fbda7957ebbc36dbe8d5e4a90ebb6891/source/game_sa/WaterCannons.h#L8

**Comment by Dark-Dragon** [comment]
> I don't think this can be considered a bug in the MTA. GTA SA has a coded water cannons limit of 3.
> [...]

Well yeah, but by that logic for instance not being able to enter a vehicle as a passenger wouldn't be an issue either, because it's not in the singleplayer. In a singleplayer environment there is no need for more than a few water cannons to exist, but in the context of a multiplayer there is, so while it's not a bug, because it's working perfectly as intended when the code was written, it's a restriction MTA should try to lift if possible, because it will be perceived as an unintended side effect of the nature of turning a singleplayer game into a multiplayer one. So this issue definitely has a right to exist, at least from my perspective.

**Comment by FileEX** [comment]
Yes, you are right, but a fundamental question should be asked here - Will increasing the limit not cause further, much bigger problems, such as crashes or bugs with effects? After all, for some reason the game developers introduced such a restriction. This needs to be checked carefully to be able to clearly answer the question of whether the MTA can increase the water cannon limit.
