### ISSUE TITLE
MTA Serial Validation no longer working on Linux.

### ISSUE THREAD

**Issue by Gravarty** [multitheftauto/mtasa-blue#3351]
### Describe the bug

I've been playing MTA on Linux for a while now, I know how to set up the server, validate my serial, etc. But  for some reason it can't no longer be verified and the classic "**There was a problem validating your serial.**" shows up. I've tried to start a server on my other Linux machines (Ubuntu LTS and Arch) and starting MTA via Wine, the error message still shows up. 

### Steps to reproduce

Follow the official tutorial on how to set up and run a MTA Server:
https://wiki.multitheftauto.com/wiki/Installing_and_Running_MTASA_Server_on_GNU_Linux

The server will startup without issues:
**Querying MTA master server... success!**

Start MTA and notice the serial still can't be validated.

### Version

Client **1.6.0** on **Arch Linux 6.8.1** and **Ubuntu LTS 22.04.04** installed using **Lutris** version **7.2.2** 32-Bit

![bug](https://github.com/multitheftauto/mtasa-blue/assets/16298668/4966a949-061c-47cd-9d35-d3b5b3e8da49)

EDIT: The default resources aren't need for verfication, but i tried it anyway and this also doesn't fix the problem.

**Comment by oppotaku** [comment]
I've tried every method mentioned in multiple issues and in the support discord, still no luck on my system.

**Comment by Gravarty** [comment]
> I've tried every method mentioned in multiple issues and in the support discord, still no luck on my system.

Yeah, same. It's a shame that this problem is not noticed by the MTA team. I understand that MTA is a Windows app and running it under Wine means "you're doing it on your own without any support". It's just the serial verification thing that was introduced to keep MTA away from cloud gaming i think.

**Comment by Ianec21** [comment]
Any update on this?

**Comment by ja0n** [comment]
I tried to debug this issue but have hit a dead end as the error seems to come from `netc.dll` which is closed source (for security reasons or something like that)

Anyway, following the lead that if you start the MTA Client without internet connection it "works" I did some experiments and found a workaround.
You can run it with systemd-run setting IPAddressDeny, which seems enough to not trigger the issue:
```
systemd-run --scope -p IPAddressDeny=any wine ~/.wine/drive_c/Program\ Files\ \(x86\)/MTA\ San\ Andreas\ 1.6/Multi\ Theft\ Auto.exe
```

A tip: for easiness you can edit the .desktop shortcut file to use the systemd-run in `~/.local/share/applications/wine/Programs/`

**Comment by gamelaster** [comment]
Strange, but for me, this works just great, together with Client working on Linux through Wine. Latest ArchLinux (x86_64)

**Comment by Gravarty** [comment]
I guess it's broken again? Server running fine, but still can't validate serial.

![Image](https://github.com/user-attachments/assets/e29ae860-5ec0-4f91-be75-3a882a98aafa)

**Comment by gamelaster** [comment]
@Gravarty what OS, which Wine version? BTW. is this Linux server or Windows server through Wine? (can't recognize from photo 😅 )

**Comment by Gravarty** [comment]
Sorry, had to edit the image again because of private infos xD

Yes, it's the Linux server running on Arch Linux. Doesn't work with Wine 10, Proton - Experimental or Hotfix.

![Image](https://github.com/user-attachments/assets/b02fbed2-f56c-4a14-b979-b6954353768c)

**Comment by gamelaster** [comment]
@Gravarty can you try just pure Wine 10 without Lutris? Since I do not use Lutris at all.

**Comment by Gravarty** [comment]
The error still appears when launching MTA directly using a freshly created Wine 10 prefix.

**Comment by Pieter-Dewachter** [comment]
FYI with the help of @ffsPLASMA I figured out that the guide using Bottles / Soda does actually work.
Before that I had tried using Lutris, Steam and Wine directly - without avail.

Guide: https://wiki.multitheftauto.com/wiki/Client_on_Linux_using_Bottles/Soda_Manual

**Comment by gamelaster** [comment]
@Pieter-Dewachter what issue you had with pure Wine? Still works great on my side.

**Comment by Pieter-Dewachter** [comment]
@gamelaster I got the exact same error as the poster of the issue, serial validation was failing on me.

**Comment by ghost** [comment]
This happens with Wine 10.12 with ntsync on Bottles. I tried to switch to Soda 9.x but then it closes before the MTA main menu can even open. Running the MTA server before doesn't change anything.

**Comment by gamelaster** [comment]
@hunter0one-gh what storage drives do you have? There is known issue about this (cannot find another GH issue where it is mentioned, will post it later).

**Comment by ghost** [comment]
> [@hunter0one-gh](https://github.com/hunter0one-gh) what storage drives do you have? There is known issue about this (cannot find another GH issue where it is mentioned, will post it later).

I think you are talking about #4097 . I have a 2 TB NVME I use for root and home partitions as well as a SATA SSD which is only 500 GB. 

I thought it may be filesystem related because I use XFS and if a drive is big enough (more than 1 TB), XFS will automatically use 64-bit inodes which [causes issues](https://www.mjr19.org.uk/sw/inodes64.html) in [some older software](https://github.com/ValveSoftware/Source-1-Games/issues/1685) but I transferred the entire Bottles prefix over to the 500 GB SSD and it still does the same thing, although even that filesystem appears to be mounted with inode64 so maybe it could still be the problem (just a complete guess). What filesystems do @Gravarty or others use, and how large is it?

**Comment by gamelaster** [comment]
@hunter0one-gh yeah, I meant https://github.com/multitheftauto/mtasa-blue/issues/4097#issuecomment-2973685878 . Well, since you have SATA SSD, you should have sata / scsi in /dev/disk/by-id/ ... strange

**Comment by abusager13** [comment]
![Image](https://github.com/user-attachments/assets/8ced1113-c802-4bdb-9d79-d81adb8b5178)

**Comment by ghost** [comment]
@gamelaster 

I completely missed that comment. Yeah, I have devices starting with ata in `/dev/disk/by-id` and it still happens.

**Comment by ghost** [comment]
I switched my home partition on my NVME to EXT4 and MTA works now. I was using XFS before.

**Comment by t3nks** [comment]
Hi All i managed to fix this. 
Using proton 9 and the steam version of the game i was able to get it working.  Ill upload the script i created to fix this.
Ive only managed to test this on my computer so if there problems give me a shout and ill try to help. 

https://github.com/t3nks/MTA-Linux

Hope this helps <3

**Comment by volcie** [comment]
Out of nowhere MTA:SA stopped working.. after dealing with the issue several months ago (I just fucked around and tried all possible solutions until it decided to work on its own). I had to deal with the issue today. Same prefix, Same everything. I restart MTA:SA to be greeted with the error.

One minute before giving up, I read the wiki one last time until i stumbled upon this:
>  On some Linux systems, MTA may fail the serial validation step during first startup. This workaround might work if your machine uses only NVMe storage devices.

I plugged in a hard disk via USB.. and it worked, finally!

**Comment by Dutchman101** [comment]
Just a kind reminder: Linux isn't officially supported by MTA. It's on a best-effort basis.

**Comment by ElJhois** [comment]
Hi, I was able to solve the problem, at least in my case. I use PoP_OS (I don't know if it will work on other distros), and suddenly MTA closed and started giving me the serial validation error. I reinstalled everything related to GTAsa and MTA, and nothing worked until I did a few things. I'm not really sure which of those things worked, so I took the time to create a text document summarizing what I did, hoping this might help someone else. Keep in mind that the guide is in my native language, Spanish. Feel free to translate and publish a version in your language or English if you find it useful. Below is the link so you can see the guide. Sorry if the English is bad, but it was translated with Google Translate, haha. https://docs.google.com/document/d/13tqammUBmEl8jn7EdoCZddal3LfksCK6O4x_x0qhGGk/edit?usp=sharing

**Comment by Jairo1010te** [comment]
For those who tried the solution:
systemd-run --scope -p IPAddressDeny=any wine ~/.wine/drive_c/Program\ Files\ (x86)/MTA\ San\ Andreas\ 1.6/Multi\ Theft\ Auto.exe
There is a problem connecting to the servers or even finding them when starting MTA, very similar to turning off the internet and starting MTA via Wine. Both open without the serial problem but do not connect to any server.
Furthermore, I tested some other solutions such as creating a new partition using a pendrive and running the MTA server from it, but it didn't work.
I tried using the solution presented in the comment above, since it also popped up, but it also ended up having no effect.
]para os que tentaram a solução 
systemd-run --scope -p IPAddressDeny=any wine ~/.wine/drive_c/Program\ Files\ \(x86\)/MTA\ San\ Andreas\ 1.6/Multi\ Theft\ Auto.exe
ha um problema ao se conectar aos servidores ou mesmo encontralos ao iniciar o mta, muito semelhante ao  desligar a internet e iniciar o mta via wine, ambos abrem sem o problema do serial mas nao se conectam a nenhum servidor
Ademais, testei algumas outras soluções como criar uma nova partição usando um pendrive e executar através dele o server do mta nao funcionou
testei usar a solução a solução apresentado pelo comentário acima já que também possou pop os mas da mesma forma acabou não surtindo efeito
