### ISSUE TITLE
Please add a "do not show anymore" button on this screen.

### ISSUE THREAD

**Issue by Nukkeh** [multitheftauto/mtasa-blue#3362]
### Is your feature request related to a problem? Please describe.

![image](https://github.com/multitheftauto/mtasa-blue/assets/102784397/ca0b06d4-344d-411f-bee6-754d028946ee)

### Security Policy

- [X] I have read and understood the Security Policy and this issue is not about a cheat or security vulnerability.

**Comment by TracerDS** [comment]
...or maybe do what the error tells you to do?
Delete or move all Asi files from your gta and/or mta directories

**Comment by dmi7ry** [comment]
This could potentially create a problem later where the window won't show up and the player won't know what the problem is.

**Comment by Lpsd** [comment]
Yeah, I don't think this is a good idea. The warning is there for a reason. 

I'd actually rather suggest we remove the "no" option and force users to stop using ASIs altogether, but that might be a controversial change in the eyes of certain users (even though we don't provide support for such mods and actively promote having a clean/non-modded SA installation).

**Comment by PlatinMTA** [comment]
I don't recall ever having issues because I had some .asi files in my directory. No crashes, no compatibility issues across multiple years, mods and installations.

Users usually tend to crash for modifying their .img and .ifp files, and we only have a warning for that after the crash, not before.

For the informed user this popup is annoying as it is, and I dont believe it should be that controversial to just add an option to not show it anymore. Maybe if we are so concerned about users knowing why their MTA is not working we could re-enable it after a crash.

**Comment by Nukkeh** [comment]
i don't want to remove the .asi files because they are corrections to the game bugs, as i play SA-MP as well, if i remove them my first person mod will stop working as well

**Comment by TracerDS** [comment]
You could make an unmodded copy of the game and use it for mta

**Comment by ghost** [comment]
Duplicate of #1200

**Comment by lopezloo** [comment]
Duplicate of #1200
