### ISSUE TITLE
[Request] Anti Cheat Report System

### ISSUE THREAD

**Issue by ALBANDER2022** [multitheftauto/mtasa-blue#3366]
### Is your feature request related to a problem? Please describe.

[Request] Anti Cheat Report System

### Describe the solution you'd like

1- report cheater serial to ban him global ban

2-Ease of communication between players and MTA Devs , MTA Anti Cheat Team

3- Report MTA SA Cheats and hacks in Anti Cheat Report System to block them

4- this is urgent priority

### Security Policy

- [X] I have read and understood the Security Policy and this issue is not about a cheat or security vulnerability.

**Comment by ghost** [comment]
You should not post these types of issues and requests on this platform, as they are not related to our code base.
All cheats that could give players an advantage in gameplay can be prevented with proper precautions and game mode, so it is the responsibility of server owners to be aware of these and patch security holes in their own code.

**Comment by TracerDS** [comment]
https://forum.multitheftauto.com/topic/139550-cheater-reports-ban-appeals-in-2023/
![image](https://github.com/multitheftauto/mtasa-blue/assets/43095317/6dfca180-e752-426c-b4a6-16643a7924d8)

**Comment by ALBANDER2022** [comment]
useless topic , useless post , useless article ,  i'm sorry

**Comment by ALBANDER2022** [comment]
Why close my issue ?

**Comment by MegadreamsBE** [comment]
This section is not meant for suggestions for MTA's anti-cheat and its policies. This is meant for suggestions and issues related to the code base of MTA specifically.

**Comment by ALBANDER2022** [comment]
i pm to dutchman101 and ccw they are not reply to me at this moment

dutchman101 From Anti Cheat Team

**Comment by sbx320** [comment]
The answer to your feature request is stated in the closure reason: _Not Planned_.

Spamming MTA Team members in PMs about it will not change that.

**Comment by ALBANDER2022** [comment]
why Not Planned ?

it is useful feature in my mind

**Comment by ghost** [comment]
> why Not Planned ?
> 
> it is useful feature in my mind

The issue was closed primarily because requests of this type should not be reported here - this repository contains our codebase, the issues and pull requests published here apply only to it.

The topic has already been heavily discussed, the entire team of Multi Theft Auto - including the team responsible for anti-cheat - consists of volunteers who work on the project in their spare time. Currently, anti-cheat team does not accept reports and appeals, if there is a change in this regard, you will definitely be notified, as this is a public interest.
