### ISSUE TITLE
setHeliBladeCollisionsEnabled partially working

### ISSUE THREAD

**Issue by pcamposu** [multitheftauto/mtasa-blue#3631]
### Describe the bug

It appears that the function setElementCollisionsEnabled correctly disables collisions for the front helicopter model in the game, but it fails to disable collisions for the tail rotor section of the helicopter.

### Steps to reproduce

1. Create Element
2. setElementCollisionsEnabled to false
3. setHeliBladeCollisionsEnabled to false

### Version

Client: v1.6-release-22650
Server: v1.6-release-22650

### Additional context

![image](https://github.com/user-attachments/assets/a0974bd4-80c8-48ac-86b8-a29d27ab982b)

### Security Policy

- [X] I have read and understood the Security Policy and this issue is not security related.

**Comment by FileEX** [comment]
I cannot reproduce.
![image](https://github.com/user-attachments/assets/d97c353c-bd50-4723-896d-8c3852d73d54)

The rear blade has no collision because it is not possible to kill the ped with the rear blade.

I also checked the situation from the screenshot and the rear blades do not collide with each other, even if blade collision is enabled, probably the problem indicated in the screenshot concerns the collision of the helicopter itself and not its blades.

![image](https://github.com/user-attachments/assets/7a87f62d-c23b-45d3-b6fd-48abeb6b5c4a)

**Comment by pcurz** [comment]
Can you please test with race_ghost, or with the helicopter flying?

**Comment by pcamposu** [comment]
Can you try with the race_ghost resource? or make the helicopter turn on, i don't really think it's just a problem with that resource, if so then close this issue. Here is the resource with that collision disabled, in playback_client.lua line 16.

[race_ghost.zip](https://github.com/user-attachments/files/16735246/race_ghost.zip)

**Comment by FileEX** [comment]
Unfortunately still cannot reproduce. Maybe you can record a video?

**Comment by pcamposu** [comment]
I can record a video once I have some free time and will share it with you as soon as I can.

**Comment by pcamposu** [comment]
Ok so i tried in a clear area like the airport, and can't reproduce. closing.

https://youtu.be/5TpNFTijcHo
