### ISSUE TITLE
Teargas smoke invisible if you didn't see it get deployed

### ISSUE THREAD

**Issue by ArranTuna** [multitheftauto/mtasa-blue#368]
**Describe the bug**
Teargas smoke does not appear if you were not in the deployment area when the teargas went off.

**To Reproduce**

1. Use freeroam
2. Throw teargas off the Los Santos skyscraper
3. `j` for jetpack
4. chase after it, ditch the jetpack in the air and fall after it so you can get there in time
5. `j` for jetpack right before hitting ground and have a look

**Expected behavior**
You should be able to see the smoke after it has streamed in

**Screenshots**

**MTA Client (please complete the following information):** 1.0

**MTA Server (please complete the following information):** 1.0

**Additional context**
This makes the weapon sort of unfair. If a person dropped it around an important area and then a person started coming toward that area, they'd have to notice just a tiny can sitting on the floor. It still causes damage. Is it possible to sync the smoke back up? Even the deployer loses sight of the smoke if he leaves the area.

From https://bugs.mtasa.com/view.php?id=1681

**Comment by Einheit-101** [comment]
This issue is related with https://github.com/multitheftauto/mtasa-blue/issues/369
It is simply because projectiles outside of stream distance seem to be ignored. onClientProjectileCreation does not trigger when a projectile from another player gets created outside stream distance. 
Even when localPlayer creates it, the projectile outside stream distance will simply fall through the ground because collisions are not loaded....

Also, setElementFrozen() does not work for projectiles.

**Comment by sbx320** [comment]
Duplicate of #369 as noted above

**Comment by qaisjp** [comment]
Duplicate of #369
