### ISSUE TITLE
My server was blocked for no reason

### ISSUE THREAD

**Issue by CrosRoad95** [multitheftauto/mtasa-blue#3887]
### Describe the bug

As you can see: 
https://www.youtube.com/watch?v=dfFoTLGvRQ0

Can't connect this server, fresh server with default configuration.

Also, my production server:  mtasa://83.168.69.118:22003 suffer from same issue. NOOBODY can join, even players who played before.

### Steps to reproduce

1. do nothing

### Version

any

### Relevant log output

```shell

```

### Security Policy

- [x] I have read and understood the Security Policy and this issue is not security related.

What rule my server broke? gambling? i have no gambling, i have even no firearm, maybe child porn? maybe someone dmca my server? What rule did i break?

**Comment by Dutchman101** [comment]
This (RealmRPG blocking) was done as part of your ban from all MTA services. You didn't really have players or co-developers yet, and of course you can transfer/sell your server to someone else, for them to continue it with a different host. However, with you being permanently banned across MTA, you need a minimal set of reasons to persist in trying to be on MTA, and evade your global ban.

Call it encouragement. Also, you only surrounded yourself with fellow toxic-minded users, so it's better for it to just disappear before it ever gets anywhere.

Even though this isn't the place for neither your inquiry or notifying the public about what happened to CrosRoad95, it's a good place to lay it out for referencing and be done with it..

CrosRoad95 is banned from all MTA services, including the game, discord and forums, for reasons that include:

- Being malicious to MTA and its servers/users. By banning malicious individuals, we seek to protect our community.
- Being a cheat developer, and exploit tool developer
- Publishing his cheats and exploits to a selection of problematic, toxic polish users (his friends circle) to go on and abuse it against servers, sometimes with a delayed disclosure (obviously not responsible disclosure) to give them enough time to abuse it and harm servers & players
- Being a cybercriminal/hacker; he routinely attacks MTA servers. This is very severe, he goes on there to look for vulnerabilities and attacks them with it, defacement style. We tried to change his mind on this practise many times, stripped his roles to avoid associating with him in his most active periods of malicious activity against MTA servers, but he could never change and **tries to justify it as "Stupid server owners, they deserve it"** which obviously doesn't float.
- Hacking activity aimed at accounts that belong to the MTA staff team, after his constant problematic behavior and erratic provocations against AC team (obviously because he's a cheat developer.. and doesn't like AC, or being reprimanded & often temp-banned about his malicious activity that AC team/Abuse department becomes aware of) led to him being banned from MTA discord. This activity, the final straw, came after a long line of intolerable toxicity and actions intended to harm the platform.

Things like this have been going on for years with CrosRoad95, and he got too many chances, including with gloves as he did contribute quite a lot and was helpful in a development perspective, and we tried everything we could not to have to cut him out and lose him. However, even though he's a talented developer, he has a mindset and character that's absolutely incompatible with our moral and ethical standards, and he's a huge liability to MTA's reputation as well should we not have cut him out.

**This is what happened to CrosRoad, and why.** He has a lot of conspiracy theories, though, and seeks to collect large numbers of polish users to make our life harder. I advise users to not only listen to what he has to say. End of story.

MTA doesn't take such actions lightly, and it's always for a reason, even if the perpetrator is much louder before we even (may or may not) provide clarity to the public. This whole thing spanned years and was carefully considered.
