### ISSUE TITLE
Secret flying train track

### ISSUE THREAD

**Issue by qaisjp** [multitheftauto/mtasa-blue#412]
**Describe the bug**
There is what seems to be a "secret" train track. It's up in the air and goes at a diagonal.

When in the air, going downwards will cause the train to "nicely" rotate and join the "main track".

Going upwards (at a fast speed) causes the train to simply warp (at a certain point) to a certain node (that node appears to be the node where it "nicely rotates")

From https://bugs.mtasa.com/view.php?id=9150

**To Reproduce**

Only works client side.

```
crun v = localPlayer.vehicle
crun v.track = 0
crun v.derailed = false -- in case you want to use v.trainSpeed later
crun v.trainPosition = 18105
crun v.track = 1
```

**Comment by AlexTMjugador** [comment]
This "secret" train track really sounds like the one used internally in singleplayer to spawn trains on the left side of the tracks during the [Snail Trail](https://www.youtube.com/watch?v=nC9zUfKIFag) mission. Some people in GTA Forums [discussed it](https://gtaforums.com/topic/304820-floating-invisible-train-track-san-fierro/). If that's the case, I don't think it is a bug. In fact, this track can be used by spawning a train near enough the "secret" train track.

**Comment by Cazomino05** [comment]
All train tracks have to be circular (meaning the first and last node are connected), this track as mentioned by the previous poster is actually a hangover from that mission and the developers never intended for it to be a complete track.

From memory this is done by a linked list but I'm literally talking several years ago here so pinch of salt and all that.

Because it needs to be circular it just ends where the mission ends and then it simply links the last and first nodes to create a circle. This means once the train gets to the last node it carries on in a very linear path towards the first node and hence it appears to be "flying" (it even goes through mountains etc because trains don't have collisions).

**Comment by qaisjp** [comment]
Btw this issue _isn't_ the train track that everyone is talking about, I'll try and make a video when I get the chance.

**Comment by qaisjp** [comment]
I don't think I can reproduce this anymore
