### ISSUE TITLE
Installer fails to launch if mandatory ASLR is enabled

### ISSUE THREAD

**Issue by jlillis** [multitheftauto/mtasa-blue#435]
**Describe the bug**
The MTA installer will fail to launch with error 0xc000007b if mandatory ASLR is enabled.

**To Reproduce**
1. Enable mandatory ASLR in the Windows Defender Security Center.
2. Attempt to run the MTA installer - it will fail.
3. Disable mandatory ASLR.
4. The installer should work again.

**Expected behavior**
The installer should work with mandatory ASLR enabled.

**Screenshots**
The installer error:
![image](https://user-images.githubusercontent.com/2784366/45262092-46192f00-b3dd-11e8-97e0-007adc31da55.png)
The mandatory ASLR setting:
![image](https://user-images.githubusercontent.com/2784366/45262094-6fd25600-b3dd-11e8-9542-608f95f52197.png)

**MTA Client (please complete the following information):**
 - Version 1.5.6
 - Running in Wine? No

**MTA Server (please complete the following information):**
 - OS: Windows 10 x64
 - Version 1.5.6

**Additional context**
When I googled "0xc000007b error" to try to fix my problem, this forum post pointed me in the right direction: https://portableapps.com/node/57109

Followed by this: https://portableapps.com/node/57104

After doing a little research into what might be causing this, I found this bug report on NSIS: https://sourceforge.net/p/nsis/bugs/1188/

According to this changelog, this bug was fixed in version 3.03 of NSIS - MTA still uses 2.46.5, which was released back in 2009. Maybe it's time for an update?

**Comment by Dutchman101** [comment]
I've noticed an increase in the amount of users who run into this issue because of "Mandatory ASLR" being enabled, just to note that the Windows 10 default for that setting is disabled so i wonder how users end up with it being enabled. Probably some specific tool (e.g system maintenance / "speed up" / security software) that's enabling it on PCs globally.

MTA can miss out on a bunch of new players, obviously not everyone seeks support. So we should really be interested in fixing it.

> MTA still uses 2.46.5, which was released back in 2009. Maybe it's time for an update?

Yes, this issue tracks updating NSIS: #2158 and i hope someone with NSIS experience takes interest in carrying it out

**Comment by patrikjuvonen** [comment]
Resolved in r21722
