### ISSUE TITLE
Chatbox spam by weird characters

### ISSUE THREAD

**Issue by ArranTuna** [multitheftauto/mtasa-blue#557]
**Describe the bug**
Recently some players found out how to spam -every- MTA chatbox with a weird symbol.

See the screenshot for an example.

**To reproduce**
Unknown as the mantis report did not contain the stated characters but the lua code below might help.

**Expected behaviour**

**Screenshots**
![image](https://user-images.githubusercontent.com/253404/45919550-ff244280-be8e-11e8-8aec-0921c0c750bd.png)

**Version**

**Additional context**
StuartUK:
This should remove allot of it they are most of the characters I found
```lua
function removeChatSpam(msg)
	local newMsg = ""
	for i = 1, utfLen(msg) do
		local char = utfCode(utfSub(msg,i,i))
		if(not (char >= 768 and char <= 879)) then
			newMsg = newMsg .. utfSub(msg,i,i)
		end
	end
	return newMsg
end
```

From https://bugs.mtasa.com/view.php?id=8114

**Comment by LosFaul** [comment]
This exists in endless other programs too and has something to do with special control characters.
So, it's more or less an issue of UTF-8/Unicode

**Comment by qaisjp** [comment]
I think it might be a good idea to include a fix for this in freeroam.

**Comment by Dutchman101** [comment]
> I think it might be a good idea to include a fix for this in freeroam.

I doubt that freeroam is the only gamemode in official resources with its own chathandler..
Is there a particular reason for only suggesting freeroam?

Also, if you think fixing it in resources is the proper approach, then maybe we should add it regardless of official gamemode, which means we'd be adding chathandlers to any gamemode that does not have it.

**Comment by qaisjp** [comment]
Reproducible using: `run outputChatBox("ą̷̳͎͚̫̱̼͚́̏͗́͋͆̆̋͋̑͛̅͗̀͌͐͒̓͋̋̅̑͒̔̉̓͒̀̃̊̒͌͆̆͐̒̂͒̄̉̂̆̾̋͋̊̂̈́̈́̈͘̚̕͘̚͘͝͝͝͝͝")`. This is called "zalgo text".

My [initial reasoning for fixing this in resources](https://github.com/multitheftauto/mtasa-blue/issues/557#issuecomment-423824460) is that I don't think we shouldn't attempt to "fix" text with excessive diacritics as we cannot guarantee we are affecting legitimate use. A proper fix is to crop text rendering instead, as detailed below.

-----

This can be fixed by ensuring `CChatLineSection::Draw` is passed an appropriate render boundary.

This issue can be hackily fixed by changing [line 1120] of [`CChatLine::Draw`] from:

```cpp
(*iter).Draw(..., RenderBounds);
```

to:

```cpp
(*iter).Draw(..., CRect2D(vecPosition.fX, vecPosition.fY, RenderBounds.fY1, vecPosition.fY+13));
```

This is obviously not a suitable fix as `13` above should be [`CChat::GetDrawList fLineDifference`]... and the `RenderBounds` should be correct in the first place.

The `RenderBounds` is originally created in [`CChat::GetDrawList`] and passed through [`CChat::DrawDrawList`].

Two options:
- Add a render bounds field per SDrawListLineItem
- Do what [`CChatInputLine::Draw`] does and just get the font height when drawing (see #885)

[line 1120]: https://github.com/multitheftauto/mtasa-blue/blob/6778def0fba7764e9e0e6117e766f8511ba02408/Client/core/CChat.cpp#L1120
[`CChatLine::Draw`]: https://github.com/multitheftauto/mtasa-blue/blob/6778def0fba7764e9e0e6117e766f8511ba02408/Client/core/CChat.cpp#L1114
[`CChat::GetDrawList fLineDifference`]: https://github.com/multitheftauto/mtasa-blue/blob/6778def0fba7764e9e0e6117e766f8511ba02408/Client/core/CChat.cpp#L279
[`CChat::DrawDrawList`]: https://github.com/multitheftauto/mtasa-blue/blob/6778def0fba7764e9e0e6117e766f8511ba02408/Client/core/CChat.cpp#L266
[`CChat::GetDrawList`]: https://github.com/multitheftauto/mtasa-blue/blob/6778def0fba7764e9e0e6117e766f8511ba02408/Client/core/CChat.cpp#L304
[`CChatInputLine::Draw`]: https://github.com/multitheftauto/mtasa-blue/blob/6778def0fba7764e9e0e6117e766f8511ba02408/Client/core/CChat.cpp#L1149
