### ISSUE TITLE
Bug in the map editor

### ISSUE THREAD

**Issue by Crewl** [multitheftauto/mtasa-blue#632]
maybe it is not a bug but when using the map editor and create an object as an example ID 980, the object appears with a rotation that should not, should appear horizontally or vertically depending on the object.
I think this has happened with the new 1.5.6 update of MTA, the map editor I run in the MTA options and not on a server.

**Comment by Dutchman101** [comment]
I tried to reproduce what you're describing by trying to find a difference in behaviour between a pretty old version of map editor resources and the current one, which I failed to recognize.

In order to raise the chances we get to understand what you feel is wrong, please follow our bug report guidelines; create your issue in the appropiate project (mtasa-resources) using the correct issue report template, so that you can provide sufficient information and reproduction steps.

After all, the rotation of objects like the one you mentioned has to be (logically) modified for it to fit your mapping purposes, and you can rotate it 360 degrees in less than 4 seconds. While I can't see the difference with earlier versions, I really wonder how something like this could ever be an issue because while mapping something you'll inevitably have to interact with all objects individually anyways.. but ofcourse that can just be a misunderstanding due to a lack of issue details.
@Crewl
