### ISSUE TITLE
Screen tearing

### ISSUE THREAD

**Issue by Grafu** [multitheftauto/mtasa-blue#643]
**Describe the bug**

Screen keeps tearing while playing MTA.

**To reproduce**

Move camera around.

**Expected behaviour**

Screen should not have break lines when rendered. Those break lines messes up screen when moving camera.

**Screenshots**

Screenshotting does not capture the tear, so uploading what screen tearing looks like.
![image](https://user-images.githubusercontent.com/11540828/46674937-0c0e9900-cbe6-11e8-8704-dbc61ac829d2.png)

**Version**

MTA:SA Server v1.5.6-release-14489
Multi Theft Auto v1.5.6-release-1466

Windows 10

**Comment by ghost** [comment]
Are you sure that this is not releated to your OS / Hardware ? By rendered - do you mean the default rendering behaviour or are you talking about dx(Create/Update)ScreenSource ?

- LuX

**Comment by Grafu** [comment]
Default behavior. I am not sure if it's related to hardware or OS. I have friends who are also complaining about this.

**Comment by AlexTMjugador** [comment]
As far as I know, MTA/GTA don't deal with VSync or buffering to face this problem by default, so I'd say it's normal for it to happen depending on what the graphics driver decides to do by default. What happens if VSync or triple buffering are forced on the graphics driver settings? [A quick Google search shows how to do that](https://www.google.com/search?q=force+vsync+driver).

**Comment by Dutchman101** [comment]
GTA is an old game, MTA fixes some GTA issues and improves upon its engine, but things like this were a goal of MTA:EIR which unfortunately never got finished.

I'm not too sure about what you mean, but can you please confirm the issue also appears in GTA?
If so, then this is unfortunately invalid as we do not focus on deep renderer issues that EIR planned to fix in GTA.

**Comment by qaisjp** [comment]
We still accept these sort of issues, it's just likely that it will take us a long time to fix them (or impossible).

Eir does *not* influence what we *cannot* do in MTA, it instead shows us what we could one day introduce.

**Comment by Einheit-101** [comment]
GSync and Freesync have been created to prevent this. However i feel that GSync doesnt really work perfectly because i still see some tearing.

**Comment by Grafu** [comment]
The tearing is still present with VSync and Trible Buffering enabled in Nvidia control panel for GTA SA.

**Comment by ccw808** [comment]
Using full screen standard?
Does the tear appear every frame in the same place?

**Comment by Grafu** [comment]
Using full screen standard. Tearing appears in different places.

**Comment by Dutchman101** [comment]
I must be honest, today I was running MTA on my laptop (Nvidia) and noticed a type of tearing that I had never seen before. I started up a recorder and suddenly it was way harder to reproduce, even in the same location and after closing the recording app. Maybe certain (lightning) circumstances played a role, as I didnt see it after that point. It happened on the surface of a customly placed GTA speaker box object, the edges teared into the plain surroundings.

I am just saying that maybe a recent change has somehow caused what you're describing, as I saw something (very odd) that may be the thing you're describing for a first time. If you have a solid reproduction for your perceived issue, then please take to a physical recording unit as you said that screenshots or similar wouldn't capture the distortion.


@Grafu, you also said: "I have friends who are also complaining about this." > was this recent, is there a clear surge in this type of complaints that you heard? If so, can you ask each one of them approximately when it started to happen? (and answer this for yourself)

**Comment by Grafu** [comment]
![image](https://user-images.githubusercontent.com/11540828/46866155-e6bd9d00-ce28-11e8-848c-ff238cadde62.png)

**Comment by patrikjuvonen** [comment]
Will be hard to trace the source in the future if we don't know when the tearing started to occur. If someone with tearing could say an approximate date or test some old builds and see which change approximately caused it?

**Comment by Wolfee-J** [comment]
I don't recall seeing any screen tearing in the past (And am now experiencing it myself with the latest update 'I haven't updated for a while because I've just been on my private Dev server most of the time') so some update in Early October did it.

**Comment by Grafu** [comment]
I wouldn't be that sure about October. I am experiencing this issue quite a long time, maybe some earlier Windows 10 update could affect this. + The tearing appears in similar place most of the time (around 25% from the screen top).

**Comment by ArranTuna** [comment]
I have experienced frame tearing in other games but I have somehow never once in 10 years of playing MTA, ever seen a single frame get teared. Weird that it happens to some people, but not me.

**Comment by Wolfee-J** [comment]
For those who are having the issue, what graphics card do you have? (I have Nvidia GTX 950)

**Comment by Kenix157** [comment]
I got this problem and friend too.

Here is all info:

MTA Client Version:
Multi Theft Auto v1.5.6-release-16068.3

MTA Diag:
Mine: https://pastebin.mtasa.com/691300845
Friend's: [MTADiag-Log-2018-12-17_20-47-31.txt](https://github.com/multitheftauto/mtasa-blue/files/2694823/MTADiag-Log-2018-12-17_20-47-31.txt)

**Comment by Grafu** [comment]
Nvidia GeForce 960M GTX

**Comment by Kenix157** [comment]
Nvidia GeForce 840M

**Comment by Kenix157** [comment]
Maybe everyone should attach a mta diag log? For developers it's will be useful.

**Comment by CrosRoad95** [comment]
i too have this issue, i have intergrated graphics card, changed to window mode fixed this problem

**Comment by Wolfee-J** [comment]
@CrosRoad95 What type of graphics card do you have (Brand)

**Comment by CrosRoad95** [comment]
intel(R) HD Graphics 4600

**Comment by Kenix157** [comment]
MTA doesn't work correctly if i change to different window modes.

**Comment by StifflersMom** [comment]
![grafik](https://user-images.githubusercontent.com/12788736/51012747-0024d100-155f-11e9-9508-eaede85d2136.png)

I can reproduce this in full screen and windowed mode and Intel HD graphics with a view angle of 45° down and moving sideways in map editor. The Build 16266 does not fix this. 

This issue never appears on my nvidia GTX 660.

Edit: I tested the same with a MTA 1.3.0 - I get the same screen tearing issues.
The OS is Windows 7 Ultimate (x64), GPU is Intel HD 2000 (very old)

**Comment by Wolfee-J** [comment]
@patrikjuvonen Question was asked due to the time this issue started to happen, frame limiter is what is causing this issue in the first place and 'Weird Camera Movement' was fixed by reverting a change to the frame limiter.

**Comment by botder** [comment]
The current code, which includes the fix to 'Weird Camera Movement', uses the new frame limiter, it's not reverted.

**Comment by patrikjuvonen** [comment]
@CodyJL The discussion went off-topic since the original issue was about the instability of the camera, which was resolved. It is fine to reference that issue as it had to do with other commits done at the same time partially relevant to that issue too (to make sure we don't break it again), but it is important to separate the discussion around this issue from that one since it wouldn't make a difference there anymore.

Anyway, let's go back on topic...

**Comment by Dutchman101** [comment]
To keep it overviewable (about the "Screen tearing" issue):

- Not everyone is affected, it seems to head towards the Nvidia/Intel HD GPU spectrum and also specific devices.

- People that are affected have **tested builds prior to any FPS limiter changes** (including the earliest one from October 2018) and **also with MTA 1.3.0**; the behaviour is the same and they are still affected.
I understand that @CodyJL doesn't know about that, because he's not in Discord or slack development channel. There has been more discussion and tests such as the one I mentioned in there, for clarity it should also be posted here which is what I'm doing right now.

Overall, what it looks like, is that graphics drivers for specific Nvidia or Intel HD GPU's matter, and the risk OS is involved (Windows 10 major build update) is also present, as has previously been determined. I would request further testing by having affected users downgrade to an pre-Windows 1803 build and using graphics drivers dated from earlier than the build's release.

If we cannot get a breakthrough by doing this, then I'm afraid this issue has to be closed because it's not shown to be a result of changes in MTA.

**Comment by Haxardous** [comment]
I've been looking into this, it seems that this happens only on "Standard" fullscreen mode (noticeable at 60fps limit) & you can barely see the tearing on 85FPS & plus. This can be fixed by switching to fullscreen windowed mode **but**, it'll look "laggy" but it's not. like the screen is dropping but not the frames (can be noticeable from the screen only), also it can be fixed by turning the "Triple buffering" option on via the graphics card control panel, unfortunately this will display a hard input latency & make the game literally unplayable.

**Comment by lopezloo** [comment]
Seems to be basically fixed by fixing #1905?

**Comment by Haxardous** [comment]
> Seems to be basically fixed by fixing #1905?

Yes, it should be fixed by now after 1905 -- as it fixes the hertz being below the monitor's refresh rate and displaying screen tearing.

**Comment by lopezloo** [comment]
I'm closing it then.
