### ISSUE TITLE
Crash after connect with server

### ISSUE THREAD

**Issue by PenkuS** [multitheftauto/mtasa-blue#770]
**Describe the bug**
When I join the server, I get a kick through the crash.

**To reproduce**
I have problems after the last update of mta and I can not connect to the server.

**Expected behaviour**
I am looking forward to fixing this error because I can not get into the server because of this error.

**Screenshots**
![screenshot_80](https://user-images.githubusercontent.com/46631222/51076763-36686a80-169d-11e9-8dda-3dd0f31b339e.png)

**Version**
mtasa-1.5.6-rc-16262-20190110

**Additional context**
I am asking for quick help.

**Comment by Dutchman101** [comment]
Please use the available support resources (MTA discord #support, forums client support) first before opening a bugtracker issue for a crash. I took a look regardless;

- The crash isn't tied to build you mentioned, because it's been seen before on other revisions.
- It looks like something related to your GPU (driver), see below image (for devs);
[https://i.imgur.com/whGZLRa.png](https://i.imgur.com/whGZLRa.png)

It crashes at this line in CEF: [https://bitbucket.org/chromiumembedded/cef/src/28d24e22d63b61ad3001d347b43b59d449c0aed7/libcef/browser/osr/render_widget_host_view_osr.cc?fileviewer=file-view-default#render_widget_host_view_osr.cc-546](https://bitbucket.org/chromiumembedded/cef/src/28d24e22d63b61ad3001d347b43b59d449c0aed7/libcef/browser/osr/render_widget_host_view_osr.cc?fileviewer=file-view-default#render_widget_host_view_osr.cc-546) which is tied to this process:
`  // If the RenderFrame that needs to navigate is not live (its process was just
  // created or has crashed), initialize it.
  if (!navigation_rfh->IsRenderFrameLive()) {
    if (!ReinitializeRenderFrame(navigation_rfh)) // <<<`

Full stack trace of crash: [https://pastebin.com/GDhQJ4Fy](https://pastebin.com/GDhQJ4Fy)

It's a pretty rare crash on MTA.
There are just 2 possibilities: a problem with your PC (most namely GPU) or a bug in CEF. In the latter case this belongs on the [CEF bug tracker](https://bitbucket.org/chromiumembedded/cef/issues), although its unlikely from what is visible. I cannot really judge, perhaps someone else can investigate further and forward it if neccesary.

Feel free to ask for support on the locations I mentioned earlier (so that we can help you troubleshoot and eventually solve it on your PC), closing this issue.

keyword: libcef.dll (0x0397FA1C)
for the record, 1 dump of this: [https://upload.mtasa.com/u/248787781/client_1.5.6-release-16262.0.000_libcef_0397fa1c_3_CPxMb_4EDF2C8E_5747_020_81FA8_20190112_1717.dmp_](https://upload.mtasa.com/u/248787781/client_1.5.6-release-16262.0.000_libcef_0397fa1c_3_CPxMb_4EDF2C8E_5747_020_81FA8_20190112_1717.dmp_)
