### ISSUE TITLE
better physics by bullet3 sdk

### ISSUE THREAD

**Issue by CrosRoad95** [multitheftauto/mtasa-blue#803]
**Is your feature request related to a problem? Please describe.**
Current collision system is sh**ty

**Describe the solution you'd like**
Add bullet3 physics to mta https://github.com/bulletphysics/bullet3

**Describe alternatives you've considered**
/

**Additional context**
i heard that saml1er going to do something with it.
this could work based on attachElement, if you create collision (independent of model id ) then you can attach object ( with disabled original collision ) to collision.

it could also introduce some helper functions such as create bullet3 collision from .col files

**Comment by qaisjp** [comment]
I don't think completely replacing the physics engine is something that we will ever do, even if it sounds like it would be good.

If someone would like to actually work on replacing the physics engine, please create a new issue with a proposal which we can then evaluate.

Otherwise I'm closing this issue, as it will likely be left open forever.
