### ISSUE TITLE
SetTimer warn about interval is below 50 even isn't number

### ISSUE THREAD

**Issue by CrosRoad95** [multitheftauto/mtasa-blue#859]
**Describe the bug**
Read topic

**To reproduce**
just run "setTimer(outputChatBox, "String here", "string here")

**Expected behaviour**
Only first warn should appear

**Screenshots**
![image](https://user-images.githubusercontent.com/22455534/55165229-558b7a00-516d-11e9-8891-b229504426b4.png)

**Version**
doesn't matter

**Additional context**
no

**Comment by qaisjp** [comment]
See:
- https://github.com/multitheftauto/mtasa-blue/commit/51a2c78c9d24f3f7321d25694653a24e39cfda86 "Fix bad numberstrings becoming 0", and
- https://github.com/multitheftauto/mtasa-blue/commit/73692fd0883c6afbab58971c6f77b3cf62b88f6e "Make bad numberstrings warn instead of error"

So what's happening here is that the string is being converted to `0`. We could add extra checks to setTimer but imo it's not worth it since we'd have to undo those changes later.

I'd propose making this warning an error in 1.6 tho. This error has been around since 1.5.3.

**Comment by qaisjp** [comment]
Closed in favour of #1043. Thanks for the issue @CrosRoad95.
