### ISSUE TITLE
Как это исправить?

### ISSUE THREAD

**Issue by RexusHD** [multitheftauto/mtasa-blue#924]
![image](https://user-images.githubusercontent.com/50492071/57534393-24a48480-736a-11e9-98fc-e799745694a3.png)

**Comment by dmi7ry** [comment]
Для начала, не нужно писать на русском — вас никто не поймёт.
А что делать, написано в окне: `Reinstall MTA`, то есть, переустановите МТА (у вас устаревшая версия).

eng: Firstly, don't write on Russian otherwise nobody will understand you.
What you need to do is written in the window: reinstall MTA (your version is too old)

**Comment by sbx320** [comment]
Please only file issues in English. Also the error message tells you how to solve your issue.
