### ISSUE TITLE
AntiCheat SD #33 is faulty - it triggers if the program is installed/autostarts, not if its currently running

### ISSUE THREAD

**Issue by tsbreuer** [multitheftauto/mtasa-blue#956]
**Describe the bug**
According to wiki, SD #33 should disallow usage of NetLimiter type apps, but its not checking if its actually running - only if its installed.

**To reproduce**
Simply grab Netlimiter 4, kill it, and try to join a server with the AC flag enabled. 

**Expected behaviour**
It should only trigger if the mentioned program/service is running according to wiki (MTA should NOT be checking what i have installed, only what i have running):
_Disallow software of the category 'Net limiter' (ideal for lagswitching or causing structural lag, but may also be used for benign purposes)_

**Screenshots**
Video reproducing it after showing Netlimiter was not running at all: https://youtu.be/8mVidMggoug

**Version**
1.5.6

**Comment by Dutchman101** [comment]
Please refer to [https://updatesa.mtasa.com/sa/trouble/?tr=netlimiter](https://updatesa.mtasa.com/sa/trouble/?tr=netlimiter) which aims to explain why, on servers that enabled SD #33, Locktime Netlimiter gets blocked even if you're not interacting with the main program: it can still apply and enforce traffic rules in the background, or automatically on PC startup, when the service process is running.




> but its not checking if its actually running - only if its installed.

> It should only trigger if the mentioned program/service is running according to wiki (MTA should NOT be checking what i have installed, only what i have running):

That's incorrect - the background process (NLsvc) is running, it doesn't block it just because it's installed. Please follow the instructions from that link to resolve it so you can play on servers that have the right to make absolutely sure you're not lagswitching (which, for this specific software, as I said isn't limited to having the app open in your screen).

Note that other software of the type netlimiter (bandwidth shaper) that are covered by SD #33, so far don't work in the same way (silently applying traffic rules) as Locktime Netlimiter and thus don't need to be blocked on autostart or background/service process. This means that if for some reason you don't want to disable autostart, you can start using alternatives instead.

**Comment by tsbreuer** [comment]
> Locktime Netlimiter gets blocked even if you're not interacting with the main program

No it doesnt. I'm stopping the service - which enforces said rules, not killing the app that does the setting up. If i stop the service, netlimiter stops doing whatever it was configured to. 

Literally video of me showing how stopping the service kills the cap:

https://youtu.be/y-psmCaI4Qg


> Please refer to https://updatesa.mtasa.com/sa/trouble/?tr=netlimiter

That only tells me "uninstall this software"

So, the actual answer is what i expected: you're soft-banning from most servers anyone having netlimiter installed. Nice.

Edit: just in case you want to spew some bullshit about how the Service is not killing the NLsvc.exe, he's a side by side with the task manager stopping and starting the service:

https://www.youtube.com/watch?v=3indtKI7mZA&feature=youtu.be

**Comment by Dutchman101** [comment]
> No it doesnt. I'm stopping the service - which enforces said rules, not killing the app that does the setting up. If i stop the service, netlimiter stops doing whatever it was configured to.
> 

Yes, stopping the service (not having it running together with MTA) is all you need to stop getting blocked. That is because as you said, it makes netlimiter stop doing whatever it was configured to. Please note that if you stop the service/background process, you'll need to relaunch MTA for the kick to go away; like with all prohibited tools. Also if you have the main Netlimiter application open, make sure to close it aswell.


> Literally video of me showing how stopping the service kills the cap:
> https://youtu.be/y-psmCaI4Qg

Yes, this is in line with the truth like mentioned up here. The bandwidth capping stopped because you stopped the service, which is its expected result.

> > Please refer to https://updatesa.mtasa.com/sa/trouble/?tr=netlimiter
> 
> That only tells me "uninstall this software"
> 

No, it merely offers it as a last-resort solution, as not everyone may understand how to disable the service or its autostart. It's not the recommended way to resolve it. I will see if the help page can be improved to make it more clear.

> So, the actual answer is what i expected: you're soft-banning from most servers anyone having netlimiter installed. Nice.

There are just a handful of servers that currently use the detection. It's called special detection for a reason.. and also, resolution for you is more than reasonable, and so is that specific server's right to stop this type of lagswitching.

> Edit: just in case you want to spew some bullshit about how the Service is not killing the NLsvc.exe, he's a side by side with the task manager stopping and starting the service:
> 
> https://www.youtube.com/watch?v=3indtKI7mZA&feature=youtu.be

I can see only expected results there: the background process stops as soon the service is stopped. Which in turn, like i described in point 1, stops you from being blocked.

Also, please mind a respectful attitude.. this was already a storm in a glass of water (either you legitimately don't get it, or have a lagswitching agenda) but let's not go beyond that. Even though the complaint is invalid, I'm still here trying to help you.

If your goal is resolution of the difficulties you're experiencing on said server, then you should simply:

- rightclick the service you stopped in your first video, then properties, and setting it to "disabled" instead of "automatic" or "manual"
- use alternative bandwidth shaper that doesn't silently apply defined traffic rules on startup

**Comment by tsbreuer** [comment]
> Yes, stopping the service (not having it running together with MTA) is all you need to stop getting blocked. That is because as you said, it makes netlimiter stop doing whatever it was configured to. Please note that if you stop the service/background process, you'll need to relaunch MTA for the kick to go away; like with all prohibited tools.

No mention anywhere a restart is needed to make MTA notice the change. Not in game, not on the web page, not even on the link you provided after i posted the isuse. IMO - it should say it somewhere at least. (Yes, this fixes the issue, restarting the game with the service off)

Plus, i just checked - starting the service while MTA is running **will** trigger the AC flag. So, why is it not turning it off when the service is stopped after a while?

**Comment by Dutchman101** [comment]
> No mention anywhere a restart is needed to make MTA notice the change. Not in game, not on the web page, not even on the link you provided after i posted the isuse. IMO - it should say it somewhere at least. (Yes, this fixes the issue, restarting the game with the service off)

Yes, that's less than ideal however the case with all AC and SD detections; if you run a cheat or prohibited tool, the kick will stick until MTA restart, even after closing the offending cheat or tool. This is the result of a technical limitation with our AC & memory scanner, and up for future improvement. 

> Plus, i just checked - starting the service while MTA is running **will** trigger the AC flag.

Obviously, when someone doesn't use prohibited tools or cheats at the moment MTA is running/already connected to a server, it should still detect them when they open it even if that's mid-gameplay.

> So, why is it not turning it off when the service is stopped after a while?
Please refer to my answer about AC limitations for any detection that fires, requiring a restart.

**Comment by xLuxy** [comment]
> starting the service while MTA is running **will** trigger the AC flag. So, why is it not turning it off when the service is stopped after a while?

MTA can't prevent services from running. (ex: MTA wasn't started as Admin which you would need to stop a windows service) That's why MTA AC keeps kicking / flagging you as a Cheater.

**Comment by tsbreuer** [comment]
My point still stands: it should be metioned either on the kick reason in-game, on the wiki, or in the link provided that the flags will stick until a restart is done.

**Comment by Dutchman101** [comment]
> > starting the service while MTA is running **will** trigger the AC flag. So, why is it not turning it off when the service is stopped after a while?
> 
> MTA can't prevent services from running. (ex: MTA wasn't started as Admin which you would need to stop a windows service) That's why MTA AC keeps kicking / flagging you as a Cheater.

If he meant something like that, this is also true.. besides that, such functionality simply isn't included; we don't want MTA to become a PUP (avoid tampering with anything on the player's PC like changing or stopping services). We just give the player an opportunity to stop using something that is prohibited.


> My point still stands: it should be metioned either on the kick reason in-game, on the wiki, or in the link provided that the flags will stick until a restart is done.

Not all AC & SD kicks have a trouble page to open, and as it affects all detections, it would require either resolving our technical limitation, changing the kick messages to include it or adding a trouble page for everything.

I will definately look into that, beginning with figuring out if we can improve AC to revoke kicks once the offending tool is closed, without restarting MTA. In reality however, we see that 9 out of the 10 players already close MTA after stopping what triggered the kick. 
Thanks for the suggestion!

Update (sept 2019): requiring a restart after closing offending software for the kick to go away, is **intended behavior**, as has been determined by the lead anti-cheat developer. This is for security reasons that we will not disclose. We are not planning to change that. It has been like that for years, for any software, cheat or tool that causes any type of kick. After this issue (about Netlimiter) was deemed invalid, the subject just shifted, but now we can also conclude on that.

As you can see, not starting MTA until you have closed any offending software (or restarting MTA once, costing you 10 seconds, if you turned out to have), is not much of an effort. So there is no reason to complain.. although I know you did only because you didn't like the Netlimiter situation being aswell as intended (or 'lost' this argument as it was an invalid issue report)
