### ISSUE TITLE
getVehicleName/getVehicleNameFromModel/getVehicleNameFromID Translations

### ISSUE THREAD

**Issue by Allerek** [multitheftauto/mtasa-blue#979]
This functions returns should be translated to actual user lang.
(For S-Side to the Geo Location of server IP or just to default-english).
I know that i can just make a table with a own names but that will be propably easy for developers to introduce.
Could be useful.

Have a nice day.

**Comment by Pirulax** [comment]
Totally possible, but implementing everything in MTA is unnecessary.

**Comment by qaisjp** [comment]
Can you give some examples of "translated vehicle names"? I don't think these are translatable as they are _proper nouns_.

If I am wrong and they are translatable, I think this fits better as a default resource.

**Comment by CrosRoad95** [comment]
all this kind of functions should be removed and devoted to programmers

**Comment by Allerek** [comment]
> Can you give some examples of "translated vehicle names"? I don't think these are translatable as they are _proper nouns_.
> 
> If I am wrong and they are translatable, I think this fits better as a default resource.

'Police LS/SF/LV'='Radiowóz LS/SF/LV'
'Ambulance'='Ambulans/Karetka Pogotowia'
'Cement Truck'='Betoniarka' 
Thats actually PL but i think every other language have its own replacements.
etc

**Comment by patrikjuvonen** [comment]
Only original shipped game languages should be supported in my opinion if they have translations for vehicle names. Other languages should be done in scripts. I think this current behavior however doesn't need changing.

**Comment by FileEX** [comment]
In my pov this is completely unnecessary. Because, as you say, you can do it via lua. It is possible, but it is simply unnecessary to translate all vehicle names for all languages. I also think that it is rare for a scripter/programmer to need vehicle names in her own language.  Optionally, it would be useful to add a table of translated vehicle names to each language on the wiki. You also can do this, for your own language, then all scripters/programmers from your country will be able to use it.
